// src/gfortran_runtime.h
// Auto-generated by glaurung source-recovery (Tasks P + Bug X).
//
// Canonical libgfortran I/O descriptor used by every recovered
// Fortran `MAIN__` body. Layout matches libgfortran 8-13's
// `st_parameter_dt` at the offsets gfortran-emitted code touches
// directly:
//
//     +0x00  flags + unit   (8 bytes, written as one `mov rax`)
//     +0x08  filename       (const char *)
//     +0x10  line           (int)
//     ...    private state  (opaque to the recovered tree)
//
// Bug X: an earlier version had `int unit` as a separate field
// after `long flags`, which pushed filename to offset 0x10 due to
// 8-byte alignment padding. The recovered C compiled clean but
// SIGSEGV'd at runtime because libgfortran walked the descriptor
// at the wrong offsets. Anonymous union below collapses
// flags+unit into 8 bytes (the gfortran 8-byte init idiom) so
// filename lands at +0x08, matching what gfortran's own MAIN__
// emits.
//
// The rewriter occasionally chooses different field spellings
// across runs (`flags` vs. `common_flags`); the union exposes
// both with shared storage so any naming compiles.
#pragma once

#include <stdint.h>

typedef struct st_parameter_dt {
    /* Offset 0: 8 bytes of flags + unit. gfortran's MAIN__ writes
     * this as a single `movabs $K, %rax; mov %rax, (descriptor)`
     * pair where K = unit << 32 | flags. The anonymous union lets
     * the recovered C use either the bare `flags` long (which
     * happens to encode both fields when initialised with the
     * 0x600000080-style literal) or split int spellings. */
    union {
        long flags;          /* rewriter's primary spelling */
        long common_flags;   /* rewriter's alternate spelling */
        struct {
            int flags_lo;    /* logical 32-bit flags word */
            int unit;        /* libgfortran unit number */
        };
    };
    const char *filename;  /* +0x08 — source filename for errors */
    int        line;       /* +0x10 — source line for errors */
    /* libgfortran private state (iomsg / iostat / format / namelist /
     * advance / internal_unit / size / rec / iolength / ...).
     * Treated as opaque by the recovered tree; the runtime fills it.
     * Pad sized to ~1024 bytes total to match libgfortran's
     * actual descriptor size on x86_64. */
    char       _pad[1004];
} st_parameter_dt;

/* Older rewrites use the gfortran-internal struct tag `gfc_dt`. */
typedef st_parameter_dt gfc_dt;
