# Generated by tools/gen_native_stub.py -- DO NOT EDIT BY HAND.
#
# Mirrors the compiled PyO3 extension `glaurung._native`. Regenerate with
#     uv run maturin develop --release && uv run python tools/gen_native_stub.py
# `python/tests/test_native_stub_current.py` fails when this file drifts from
# the built module.
#
# Parameter and return types are `Any`: PyO3 exposes arity, parameter names
# and defaults, but no types. Arity and keyword names are therefore checked;
# types deliberately are not.


from typing import Any

def emulate_function(binary_path: Any, entry_va: Any, arch: Any = "x86_64", max_steps: Any = 100000) -> Any: ...
