# Generated by tools/gen_native_stub.py -- DO NOT EDIT BY HAND.
#
# Mirrors the compiled PyO3 extension `glaurung._native`. Regenerate with
#     uv run maturin develop --release && uv run python tools/gen_native_stub.py
# `python/tests/test_native_stub_current.py` fails when this file drifts from
# the built module.
#
# Parameter and return types are `Any`: PyO3 exposes arity, parameter names
# and defaults, but no types. Arity and keyword names are therefore checked;
# types deliberately are not.


from typing import Any

def ctph_hash_bytes(data: Any, window_size: Any = 8, digest_size: Any = 4, precision: Any = 8) -> Any: ...
def ctph_hash_path(path: Any, max_read_bytes: Any = 10485760, max_file_size: Any = 104857600, window_size: Any = 8, digest_size: Any = 4, precision: Any = 8) -> Any: ...
def ctph_pairwise_matrix(digests: Any, max_pairs: Any = 250000) -> Any: ...
def ctph_recommended_params(length: Any) -> Any: ...
def ctph_similarity(a: Any, b: Any) -> Any: ...
def ctph_top_k(query_digest: Any, candidates: Any, k: Any = 5, min_score: Any = 0.6, max_candidates: Any = 10000) -> Any: ...
