# Generated by tools/gen_native_stub.py -- DO NOT EDIT BY HAND.
#
# Mirrors the compiled PyO3 extension `glaurung._native`. Regenerate with
#     uv run maturin develop --release && uv run python tools/gen_native_stub.py
# `python/tests/test_native_stub_current.py` fails when this file drifts from
# the built module.
#
# Parameter and return types are `Any`: PyO3 exposes arity, parameter names
# and defaults, but no types. Arity and keyword names are therefore checked;
# types deliberately are not.


from typing import Any

class Budgets:
    """Resource usage and safety budgets."""

    bytes_read: Any
    hit_byte_limit: Any
    limit_bytes: Any
    limit_time_ms: Any
    max_recursion_depth: Any
    recursion_depth: Any
    time_ms: Any

    def __init__(self, bytes_read: Any, time_ms: Any, recursion_depth: Any) -> None: ...

class ConfidenceSignal:
    """A single confidence signal contribution."""

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @staticmethod
    def create(*args: Any, **kwargs: Any) -> Any: ...

class ContainerChild:
    """Child artifact discovered within a container or overlay."""

    children: Any
    metadata: Any
    offset: Any
    size: Any
    type_name: Any

    def __init__(self, type_name: Any, offset: Any, size: Any) -> None: ...

class ContainerMetadata:
    """Optional metadata extracted from container formats without full extraction."""

    def __init__(self, file_count: Any = None, total_uncompressed_size: Any = None, total_compressed_size: Any = None) -> None: ...

class DetectedString:
    """A detected string with language information."""

    confidence: Any
    encoding: Any
    language: Any
    offset: Any
    script: Any
    text: Any

    def __init__(self, text: Any, encoding: Any, language: Any = None, script: Any = None, confidence: Any = None, offset: Any = None) -> None: ...
    def __repr__(self) -> Any: ...
    def __str__(self) -> Any: ...

class EntropyAnalysis:
    """Full entropy analysis record."""

    anomalies: Any
    classification_kind: Any
    packed_indicators: Any
    summary: Any

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class EntropyAnomaly:
    """Sudden entropy jump info."""

    delta: Any
    from_value: Any
    index: Any
    to: Any
    to_value: Any

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __repr__(self) -> Any: ...

class EntropyClass:
    """Entropy classification bucket with associated measured value."""

    value: Any

    class Code(EntropyClass):
        def __init__(self, _0: Any) -> None: ...
        def __getitem__(self, key: Any, /) -> Any: ...
        def __len__(self) -> Any: ...

    class Compressed(EntropyClass):
        def __init__(self, _0: Any) -> None: ...
        def __getitem__(self, key: Any, /) -> Any: ...
        def __len__(self) -> Any: ...

    class Encrypted(EntropyClass):
        def __init__(self, _0: Any) -> None: ...
        def __getitem__(self, key: Any, /) -> Any: ...
        def __len__(self) -> Any: ...

    class Random(EntropyClass):
        def __init__(self, _0: Any) -> None: ...
        def __getitem__(self, key: Any, /) -> Any: ...
        def __len__(self) -> Any: ...

    class Text(EntropyClass):
        def __init__(self, _0: Any) -> None: ...
        def __getitem__(self, key: Any, /) -> Any: ...
        def __len__(self) -> Any: ...

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class EntropyConfig:
    """Entropy analysis configuration."""

    header_size: Any
    max_windows: Any
    overall: Any
    step: Any
    thresholds: Any
    weights: Any
    window_size: Any

    def __init__(self) -> None: ...

class EntropySummary:
    """Entropy summary for an input."""

    max: Any
    mean: Any
    min: Any
    overall: Any
    std_dev: Any
    window_size: Any
    windows: Any

    def __init__(self, overall: Any = None, window_size: Any = None, windows: Any = None) -> None: ...

class EntropyThresholds:
    """Entropy classification thresholds."""

    cliff_delta: Any
    code: Any
    compressed: Any
    encrypted: Any
    high_body: Any
    low_header: Any
    text: Any

    def __init__(self) -> None: ...

class EntropyWeights:
    """Entropy scoring weights."""

    cliff_detected: Any
    encrypted_random: Any
    header_body_mismatch: Any
    high_entropy: Any

    def __init__(self) -> None: ...

class HeaderConfig:
    """Header analysis configuration."""

    base_confidence: Any
    detailed_confidence: Any

    def __init__(self) -> None: ...

class HeuristicsConfig:
    """Heuristics configuration for string extraction and analysis."""

    endianness_threshold: Any
    endianness_weight: Any
    min_string_length: Any
    string_sample_limit: Any
    string_sample_max_len: Any

    def __init__(self) -> None: ...

class IOConfig:
    """I/O configuration for file reading and buffering."""

    max_entropy_size: Any
    max_file_size: Any
    max_header_size: Any
    max_read_bytes: Any
    max_sniff_size: Any
    sniff_buffer_size: Any

    def __init__(self) -> None: ...

class IocSample:
    """A single IOC match sample"""

    kind: Any
    offset: Any
    text: Any

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class OverlayAnalysis:
    """Analysis results for overlay data found in binary files."""

    detected_format: Any
    entropy: Any
    has_signature: Any
    header: Any
    is_archive: Any
    offset: Any
    sha256: Any
    size: Any

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __repr__(self) -> Any: ...

class OverlayFormat:
    """Known overlay formats that can be detected."""

    AppImage: OverlayFormat
    CAB: OverlayFormat
    Certificate: OverlayFormat
    ISO9660: OverlayFormat
    InnoSetup: OverlayFormat
    NSIS: OverlayFormat
    RAR: OverlayFormat
    SevenZip: OverlayFormat
    SquashFS: OverlayFormat
    Unknown: OverlayFormat
    ZIP: OverlayFormat

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __int__(self) -> Any: ...
    def __repr__(self) -> Any: ...
    def __str__(self) -> Any: ...

class PackedIndicators:
    """Heuristics to detect packing/compression patterns."""

    entropy_cliff: Any
    has_high_entropy_body: Any
    has_low_entropy_header: Any
    verdict: Any

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class PackerConfig:
    """Packer detection configuration."""

    packer_signal_weight: Any
    scan_limit: Any
    upx_detection_weight: Any
    upx_version_weight: Any

    def __init__(self) -> None: ...

class PackerMatch:
    """Packer detection entry."""

    confidence: Any
    name: Any

    def __init__(self, name: Any, confidence: Any) -> None: ...

class ParserConfig:
    """Parser configuration."""

    python_bytecode_confidence: Any

    def __init__(self) -> None: ...

class ParserKind:
    """Which structured parser produced a result."""

    Goblin: ParserKind
    Nom: ParserKind
    Object: ParserKind
    PELite: ParserKind

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __eq__(self, value: Any, /) -> Any: ...
    def __ge__(self, value: Any, /) -> Any: ...
    def __gt__(self, value: Any, /) -> Any: ...
    def __int__(self) -> Any: ...
    def __le__(self, value: Any, /) -> Any: ...
    def __lt__(self, value: Any, /) -> Any: ...
    def __ne__(self, value: Any, /) -> Any: ...
    def __repr__(self) -> Any: ...
    def __str__(self) -> Any: ...

class ParserResult:
    """Result of attempting to parse with a specific parser."""

    def __init__(self, parser: Any, ok: Any, error: Any) -> None: ...

class RecursionSummary:
    """Rollup summary for recursion/children stats"""

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class ScoringConfig:
    """Scoring and confidence configuration."""

    arch_consistency_penalty: Any
    format_consistency_penalty: Any
    infer_weight: Any
    mime_weight: Any
    other_weight: Any
    parser_success_confidence: Any

    def __init__(self) -> None: ...

class SigningSummary:
    """Signing presence summary (triage-level, presence only)"""

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class SimilarityConfig:
    """Similarity (CTPH) configuration."""

    digest_size: Any
    enable_ctph: Any
    precision: Any
    window_size: Any

    def __init__(self) -> None: ...

class SimilaritySummary:
    """Similarity summary (fuzzy and import-based hashes)"""

    ctph: Any
    imphash: Any

    def __init__(self, imphash: Any, ctph: Any) -> None: ...

class SnifferSource:
    """Source of a sniffer hint."""

    Infer: SnifferSource
    MimeGuess: SnifferSource
    Other: SnifferSource

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __eq__(self, value: Any, /) -> Any: ...
    def __ge__(self, value: Any, /) -> Any: ...
    def __gt__(self, value: Any, /) -> Any: ...
    def __int__(self) -> Any: ...
    def __le__(self, value: Any, /) -> Any: ...
    def __lt__(self, value: Any, /) -> Any: ...
    def __ne__(self, value: Any, /) -> Any: ...
    def __repr__(self) -> Any: ...
    def __str__(self) -> Any: ...

class StringsSummary:
    """Strings summary at triage time."""

    ascii_count: Any
    ioc_counts: Any
    ioc_samples: Any
    language_counts: Any
    samples: Any
    script_counts: Any
    strings: Any
    utf16be_count: Any
    utf16le_count: Any
    utf8_count: Any

    def __init__(self, ascii_count: Any, utf16le_count: Any, utf16be_count: Any, strings: Any = None, language_counts: Any = None, script_counts: Any = None) -> None: ...

class SymbolSummary:
    """Summary of symbols extracted from a binary"""

    aslr: Any
    cfg: Any
    debug_info_present: Any
    demangled_export_names: Any
    demangled_import_names: Any
    entry_section: Any
    export_names: Any
    exports_count: Any
    import_names: Any
    imports_count: Any
    libs_count: Any
    nx: Any
    pie: Any
    relocations_present: Any
    relro: Any
    rpaths: Any
    runpaths: Any
    stripped: Any
    suspicious_imports: Any
    tls_callback_count: Any
    tls_callback_vas: Any
    tls_used: Any

    def __init__(self, imports_count: Any, exports_count: Any, libs_count: Any, stripped: Any, tls_used: Any, debug_info_present: Any, suspicious_imports: Any = None, entry_section: Any = None, import_names: Any = None, export_names: Any = None, nx: Any = None, aslr: Any = None, relro: Any = None, pie: Any = None, cfg: Any = None, rpaths: Any = None, runpaths: Any = None) -> None: ...

class TriageConfig:
    """Master configuration for the triage pipeline."""

    entropy: Any
    headers: Any
    heuristics: Any
    io: Any
    packers: Any
    parsers: Any
    scoring: Any
    similarity: Any

    def __init__(self) -> None: ...

class TriageError:
    """Concrete error with optional message."""

    kind: Any
    message: Any

    def __init__(self, kind: Any, message: Any = None) -> None: ...
    def __repr__(self) -> Any: ...
    @staticmethod
    def create(*args: Any, **kwargs: Any) -> Any: ...

class TriageErrorKind:
    """Standardized error kinds encountered during triage."""

    BadMagic: TriageErrorKind
    BudgetExceeded: TriageErrorKind
    IncoherentFields: TriageErrorKind
    Other: TriageErrorKind
    ParserMismatch: TriageErrorKind
    ShortRead: TriageErrorKind
    SnifferMismatch: TriageErrorKind
    Truncated: TriageErrorKind
    UnsupportedVariant: TriageErrorKind

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __eq__(self, value: Any, /) -> Any: ...
    def __ge__(self, value: Any, /) -> Any: ...
    def __gt__(self, value: Any, /) -> Any: ...
    def __int__(self) -> Any: ...
    def __le__(self, value: Any, /) -> Any: ...
    def __lt__(self, value: Any, /) -> Any: ...
    def __ne__(self, value: Any, /) -> Any: ...
    def __repr__(self) -> Any: ...
    def __str__(self) -> Any: ...

class TriageHint:
    """A single sniffer hint derived from content or extension."""

    extension: Any
    label: Any
    mime: Any
    source: Any

    def __init__(self, source: Any, mime: Any = None, extension: Any = None, label: Any = None) -> None: ...
    def __repr__(self) -> Any: ...
    @staticmethod
    def create(*args: Any, **kwargs: Any) -> Any: ...

class TriageVerdict:
    """A single classification hypothesis with confidence."""

    arch: Any
    bits: Any
    confidence: Any
    endianness: Any
    format: Any

    def __init__(self, format: Any, arch: Any, bits: Any, endianness: Any, confidence: Any, signals: Any = None) -> None: ...

class TriagedArtifact:
    """Overall triage report for an input artifact."""

    budgets: Any
    containers: Any
    entropy: Any
    entropy_analysis: Any
    errors: Any
    format_specific: Any
    heuristic_arch: Any
    heuristic_endianness: Any
    hints: Any
    id: Any
    overlay: Any
    packers: Any
    parse_status: Any
    path: Any
    recursion_summary: Any
    schema_version: Any
    sha256: Any
    signing: Any
    similarity: Any
    size_bytes: Any
    strings: Any
    symbols: Any
    verdicts: Any

    def __init__(self, schema_version: Any, id: Any, path: Any, size_bytes: Any, sha256: Any = None, hints: Any = ..., verdicts: Any = ..., entropy: Any = None, entropy_analysis: Any = None, strings: Any = None, symbols: Any = None, similarity: Any = None, signing: Any = None, packers: Any = None, containers: Any = None, recursion_summary: Any = None, overlay: Any = None, format_specific: Any = None, parse_status: Any = None, budgets: Any = None, errors: Any = None, heuristic_endianness: Any = None, heuristic_arch: Any = None, disasm_preview: Any = None) -> None: ...
    def ctph_similarity(self, other: Any) -> Any: ...
    @staticmethod
    def from_json(*args: Any, **kwargs: Any) -> Any: ...
    def to_json(self) -> Any: ...

def analyze_bytes(data: Any, max_read_bytes: Any = 10485760, max_recursion_depth: Any = 1, min_string_length: Any = 4, max_string_samples: Any = 40, enable_language: Any = True, max_lang_detect: Any = 100, enable_classification: Any = True, max_classify: Any = 200, max_ioc_per_string: Any = 16, config: Any = None) -> Any: ...
def analyze_entropy_bytes(data: Any, window_size: Any = 8192, step: Any = 8192, max_windows: Any = 256, header_size: Any = 1024) -> Any: ...
def analyze_path(*args: Any, **kwargs: Any) -> Any: ...
def compute_entropy(data: Any, window_size: Any = 8192, step: Any = 8192, max_windows: Any = 256, overall: Any = True, header_size: Any = 1024) -> Any: ...
def detect_language(text: Any, min_size: Any = 4, min_conf: Any = 0.5, agree_conf: Any = 0.4) -> Any: ...
def detect_language_lingua(text: Any) -> Any: ...
def detect_language_whatlang(text: Any) -> Any: ...
def detect_languages(texts: Any, min_size: Any = 4, min_conf: Any = 0.5, agree_conf: Any = 0.4) -> Any: ...
def entropy_of_bytes(data: Any) -> Any: ...
def list_symbols(path: Any, max_read_bytes: Any = 10485760, max_file_size: Any = 104857600) -> Any: ...
def list_symbols_demangled(path: Any, max_read_bytes: Any = 10485760, max_file_size: Any = 104857600) -> Any: ...
def triage(*args: Any, **kwargs: Any) -> Any: ...
