"""minisign key, signature and verification, in the standard file formats.

The distribution channel signs **the manifest only**. One Ed25519 signature
transitively covers every blob in the set, because each blob is named by and
verified against the sha256 the manifest records -- Nix's model, where the
binary cache is dumb static HTTP and all trust lives in a detached signature.
That is the whole reason blobs need no signature of their own.

minisign rather than GPG because the artefacts are tiny, the formats are two
base64 lines, and the *trusted comment* field exists for exactly the problem
this channel has. minisign's own documentation says the trusted comment is
signed "to prevent downgrade attacks", so the set version and the monotonic
serial go there: an attacker who replays an older, still-validly-signed
manifest cannot rewrite the serial without invalidating the global signature.

File formats, as implemented here
---------------------------------

Public key (`.pub`), two lines::

    untrusted comment: <text>
    base64( "Ed" | key_id[8] | public_key[32] )                    # 42 bytes

Signature (`.minisig`), four lines::

    untrusted comment: <text>
    base64( alg[2] | key_id[8] | signature[64] )                   # 74 bytes
    trusted comment: <text>
    base64( global_signature[64] )

where `alg` is `b"Ed"` for a signature over the file bytes and `b"ED"` for
minisign's default prehashed mode, a signature over BLAKE2b-512 of the file.
The *global* signature covers `signature || trusted_comment`, which is what
binds the trusted comment to the signature.

Secret key (`.key`)::

    untrusted comment: <text>
    base64( "Ed" | kdf_alg[2] | "B2" | salt[32] | ops[8] | mem[8]
            | key_id[8] | secret_key[64] | checksum[32] )         # 158 bytes

Only minisign's password-less form (`kdf_alg` zeroed, as written by
`minisign -G -W`) is produced and read here: the scrypt-encrypted form needs
an interactive password, which a publish tool cannot supply, and the
maintainer's real key can be generated by minisign itself. The *public* key
and the *signature* are the interop surface that matters -- anyone can check
our releases with stock `minisign -Vm manifest.json -p glaurung-sigs.pub`.
"""

from __future__ import annotations

import base64
import binascii
import hashlib
import secrets
from dataclasses import dataclass
from pathlib import Path

from . import ed25519

__all__ = [
    "MinisignError",
    "PublicKey",
    "SecretKey",
    "Signature",
    "generate_keypair",
    "sign_file",
    "verify_file",
]

#: `signature_algorithm`: legacy (sign the file) and prehashed (sign its
#: BLAKE2b-512 digest). minisign has defaulted to prehashed since 0.10; both
#: are accepted on verify so a signature from an older minisign still checks.
ALG_LEGACY = b"Ed"
ALG_PREHASHED = b"ED"

#: `kdf_algorithm`: scrypt, or the password-less form. See the module docstring.
KDF_SCRYPT = b"Sc"
KDF_NONE = b"\x00\x00"

#: `cksum_algorithm`: BLAKE2b-256 over `sig_alg | key_id | secret_key`.
CKSUM_BLAKE2B = b"B2"

_UNTRUSTED_PREFIX = "untrusted comment: "
_TRUSTED_PREFIX = "trusted comment: "


class MinisignError(Exception):
    """A key or signature file is malformed, or a signature does not verify."""


# --- Ed25519 backend selection ----------------------------------------------
#
# `cryptography` when importable (C, constant time), the pure-Python fallback
# otherwise. `ed25519_backend()` is public so a test can assert both paths
# agree rather than only exercising whichever the dev machine happens to have.


def _cryptography_ed25519():
    try:
        from cryptography.hazmat.primitives.asymmetric import ed25519 as impl
    except ImportError:
        return None
    return impl


def ed25519_backend() -> str:
    """`"cryptography"` or `"pure-python"`, whichever verification will use."""
    return "cryptography" if _cryptography_ed25519() is not None else "pure-python"


def ed25519_verify(public_key: bytes, message: bytes, signature: bytes) -> bool:
    """Verify with the preferred backend. Never raises."""
    impl = _cryptography_ed25519()
    if impl is None:
        return ed25519.verify(public_key, message, signature)
    try:
        impl.Ed25519PublicKey.from_public_bytes(public_key).verify(signature, message)
    except Exception:
        return False
    return True


def ed25519_sign(seed: bytes, message: bytes) -> bytes:
    """Sign with the preferred backend."""
    impl = _cryptography_ed25519()
    if impl is None:
        return ed25519.sign(seed, message)
    return impl.Ed25519PrivateKey.from_private_bytes(seed).sign(message)


def ed25519_public_from_seed(seed: bytes) -> bytes:
    impl = _cryptography_ed25519()
    if impl is None:
        return ed25519.public_from_seed(seed)
    from cryptography.hazmat.primitives import serialization

    return (
        impl.Ed25519PrivateKey.from_private_bytes(seed)
        .public_key()
        .public_bytes(
            encoding=serialization.Encoding.Raw,
            format=serialization.PublicFormat.Raw,
        )
    )


# --- file parsing helpers ----------------------------------------------------


def _b64(data: bytes) -> str:
    return base64.standard_b64encode(data).decode("ascii")


def _unb64(text: str, what: str) -> bytes:
    try:
        return base64.standard_b64decode(text.strip())
    except (ValueError, binascii.Error) as exc:
        raise MinisignError(f"{what}: not valid base64") from exc


def _lines(text: str, what: str, minimum: int) -> list[str]:
    lines = [ln for ln in text.splitlines() if ln.strip()]
    if len(lines) < minimum:
        raise MinisignError(
            f"{what}: expected at least {minimum} lines, got {len(lines)}"
        )
    return lines


def _strip_prefix(line: str, prefix: str, what: str) -> str:
    if not line.startswith(prefix):
        raise MinisignError(f"{what}: line does not start with {prefix!r}")
    return line[len(prefix) :]


# --- public key --------------------------------------------------------------


@dataclass(frozen=True)
class PublicKey:
    """A minisign public key: an 8-byte key id and 32 bytes of Ed25519."""

    key_id: bytes
    key: bytes
    untrusted_comment: str = "minisign public key"

    def __post_init__(self) -> None:
        if len(self.key_id) != 8:
            raise MinisignError(f"key id must be 8 bytes, got {len(self.key_id)}")
        if len(self.key) != ed25519.PUBLIC_KEY_BYTES:
            raise MinisignError(f"public key must be 32 bytes, got {len(self.key)}")

    @property
    def key_id_hex(self) -> str:
        """minisign spells the key id big-endian-reversed in its comments."""
        return self.key_id[::-1].hex().upper()

    def to_text(self) -> str:
        payload = ALG_LEGACY + self.key_id + self.key
        return f"{_UNTRUSTED_PREFIX}{self.untrusted_comment}\n{_b64(payload)}\n"

    @classmethod
    def from_text(cls, text: str) -> "PublicKey":
        lines = _lines(text, "public key", 2)
        comment = _strip_prefix(lines[0], _UNTRUSTED_PREFIX, "public key")
        raw = _unb64(lines[1], "public key")
        if len(raw) != 42:
            raise MinisignError(f"public key payload must be 42 bytes, got {len(raw)}")
        if raw[:2] != ALG_LEGACY:
            raise MinisignError(f"unsupported public-key algorithm {raw[:2]!r}")
        return cls(key_id=raw[2:10], key=raw[10:], untrusted_comment=comment)

    @classmethod
    def read(cls, path: str | Path) -> "PublicKey":
        return cls.from_text(Path(path).read_text(encoding="utf-8"))


# --- secret key --------------------------------------------------------------


@dataclass(frozen=True)
class SecretKey:
    """A password-less minisign secret key.

    `secret_key` is libsodium's 64-byte form (seed then public key), so the
    seed the RFC 8032 primitives want is `secret_key[:32]`.
    """

    key_id: bytes
    secret_key: bytes
    untrusted_comment: str = "minisign encrypted secret key"

    def __post_init__(self) -> None:
        if len(self.key_id) != 8:
            raise MinisignError(f"key id must be 8 bytes, got {len(self.key_id)}")
        if len(self.secret_key) != ed25519.SECRET_KEY_BYTES:
            raise MinisignError(
                f"secret key must be 64 bytes, got {len(self.secret_key)}"
            )

    @property
    def seed(self) -> bytes:
        return self.secret_key[:32]

    def public_key(self, comment: str | None = None) -> PublicKey:
        return PublicKey(
            key_id=self.key_id,
            key=self.secret_key[32:],
            untrusted_comment=comment
            or f"minisign public key {self.key_id[::-1].hex().upper()}",
        )

    def _checksum(self) -> bytes:
        return hashlib.blake2b(
            ALG_LEGACY + self.key_id + self.secret_key, digest_size=32
        ).digest()

    def to_text(self) -> str:
        payload = (
            ALG_LEGACY
            + KDF_NONE
            + CKSUM_BLAKE2B
            + bytes(32)  # kdf salt: unused in the password-less form
            + bytes(8)  # kdf opslimit
            + bytes(8)  # kdf memlimit
            + self.key_id
            + self.secret_key
            + self._checksum()
        )
        return f"{_UNTRUSTED_PREFIX}{self.untrusted_comment}\n{_b64(payload)}\n"

    @classmethod
    def from_text(cls, text: str) -> "SecretKey":
        lines = _lines(text, "secret key", 2)
        comment = _strip_prefix(lines[0], _UNTRUSTED_PREFIX, "secret key")
        raw = _unb64(lines[1], "secret key")
        if len(raw) != 158:
            raise MinisignError(f"secret key payload must be 158 bytes, got {len(raw)}")
        if raw[:2] != ALG_LEGACY:
            raise MinisignError(f"unsupported secret-key algorithm {raw[:2]!r}")
        if raw[2:4] == KDF_SCRYPT:
            raise MinisignError(
                "this secret key is password-protected; decrypt it with the "
                "minisign binary, or generate a password-less key with "
                "`minisign -G -W`"
            )
        if raw[2:4] != KDF_NONE:
            raise MinisignError(f"unsupported kdf algorithm {raw[2:4]!r}")
        if raw[4:6] != CKSUM_BLAKE2B:
            raise MinisignError(f"unsupported checksum algorithm {raw[4:6]!r}")
        key = cls(key_id=raw[54:62], secret_key=raw[62:126], untrusted_comment=comment)
        if key._checksum() != raw[126:158]:
            raise MinisignError("secret key checksum mismatch (file is corrupt)")
        return key

    @classmethod
    def read(cls, path: str | Path) -> "SecretKey":
        return cls.from_text(Path(path).read_text(encoding="utf-8"))

    def write(self, path: str | Path) -> Path:
        """Write with `0600` from creation -- never world-readable, even briefly."""
        target = Path(path)
        target.parent.mkdir(parents=True, exist_ok=True)
        # Create with the restrictive mode rather than chmod-after-write, which
        # leaves a window in which the key is readable.
        fd = __import__("os").open(
            target,
            __import__("os").O_WRONLY
            | __import__("os").O_CREAT
            | __import__("os").O_TRUNC,
            0o600,
        )
        with __import__("os").fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(self.to_text())
        return target


def generate_keypair(
    *, comment: str = "glaurung signature-set signing key"
) -> tuple[SecretKey, PublicKey]:
    """A fresh Ed25519 keypair with a random 8-byte key id."""
    seed = secrets.token_bytes(ed25519.SEED_BYTES)
    public = ed25519_public_from_seed(seed)
    key_id = secrets.token_bytes(8)
    secret = SecretKey(
        key_id=key_id,
        secret_key=seed + public,
        untrusted_comment=f"minisign secret key ({comment})",
    )
    return secret, secret.public_key(
        f"minisign public key {key_id[::-1].hex().upper()} ({comment})"
    )


# --- signatures --------------------------------------------------------------


@dataclass(frozen=True)
class Signature:
    """A parsed `.minisig`."""

    algorithm: bytes
    key_id: bytes
    signature: bytes
    trusted_comment: str
    global_signature: bytes
    untrusted_comment: str = "signature from glaurung"

    @property
    def prehashed(self) -> bool:
        return self.algorithm == ALG_PREHASHED

    def to_text(self) -> str:
        payload = self.algorithm + self.key_id + self.signature
        return (
            f"{_UNTRUSTED_PREFIX}{self.untrusted_comment}\n"
            f"{_b64(payload)}\n"
            f"{_TRUSTED_PREFIX}{self.trusted_comment}\n"
            f"{_b64(self.global_signature)}\n"
        )

    @classmethod
    def from_text(cls, text: str) -> "Signature":
        lines = _lines(text, "signature", 4)
        untrusted = _strip_prefix(lines[0], _UNTRUSTED_PREFIX, "signature")
        raw = _unb64(lines[1], "signature")
        if len(raw) != 74:
            raise MinisignError(f"signature payload must be 74 bytes, got {len(raw)}")
        algorithm = raw[:2]
        if algorithm not in (ALG_LEGACY, ALG_PREHASHED):
            raise MinisignError(f"unsupported signature algorithm {algorithm!r}")
        trusted = _strip_prefix(lines[2], _TRUSTED_PREFIX, "signature")
        global_sig = _unb64(lines[3], "global signature")
        if len(global_sig) != ed25519.SIGNATURE_BYTES:
            raise MinisignError(
                f"global signature must be 64 bytes, got {len(global_sig)}"
            )
        return cls(
            algorithm=algorithm,
            key_id=raw[2:10],
            signature=raw[10:],
            trusted_comment=trusted,
            global_signature=global_sig,
            untrusted_comment=untrusted,
        )

    @classmethod
    def read(cls, path: str | Path) -> "Signature":
        return cls.from_text(Path(path).read_text(encoding="utf-8"))


def _message(content: bytes, prehashed: bool) -> bytes:
    return hashlib.blake2b(content, digest_size=64).digest() if prehashed else content


def sign_bytes(
    secret: SecretKey,
    content: bytes,
    *,
    trusted_comment: str,
    untrusted_comment: str = "signature from glaurung",
    prehashed: bool = True,
) -> Signature:
    """Sign `content`, binding `trusted_comment` with the global signature."""
    algorithm = ALG_PREHASHED if prehashed else ALG_LEGACY
    signature = ed25519_sign(secret.seed, _message(content, prehashed))
    global_signature = ed25519_sign(
        secret.seed, signature + trusted_comment.encode("utf-8")
    )
    return Signature(
        algorithm=algorithm,
        key_id=secret.key_id,
        signature=signature,
        trusted_comment=trusted_comment,
        global_signature=global_signature,
        untrusted_comment=untrusted_comment,
    )


def sign_file(
    secret: SecretKey,
    path: str | Path,
    *,
    trusted_comment: str,
    untrusted_comment: str = "signature from glaurung",
    prehashed: bool = True,
    output: str | Path | None = None,
) -> Path:
    """Sign `path`, writing `<path>.minisig` (or `output`). Returns that path."""
    source = Path(path)
    signature = sign_bytes(
        secret,
        source.read_bytes(),
        trusted_comment=trusted_comment,
        untrusted_comment=untrusted_comment,
        prehashed=prehashed,
    )
    target = (
        Path(output)
        if output is not None
        else source.with_name(source.name + ".minisig")
    )
    target.write_text(signature.to_text(), encoding="utf-8")
    return target


def verify_bytes(
    content: bytes,
    signature: Signature,
    public_keys: list[PublicKey],
) -> PublicKey:
    """Verify `content` against any of `public_keys`. Returns the one that matched.

    Raises :class:`MinisignError` on any failure. Both signatures are checked:
    the file signature, and the global signature over
    `signature || trusted_comment` that binds the trusted comment (where the
    set version and serial live) to the file signature.
    """
    if not public_keys:
        raise MinisignError("no trusted public keys are configured")
    candidates = [k for k in public_keys if k.key_id == signature.key_id]
    if not candidates:
        known = ", ".join(sorted(k.key_id_hex for k in public_keys)) or "(none)"
        raise MinisignError(
            f"signature is from key {signature.key_id[::-1].hex().upper()}, "
            f"which is not trusted; trusted keys: {known}"
        )
    message = _message(content, signature.prehashed)
    for key in candidates:
        if not ed25519_verify(key.key, message, signature.signature):
            continue
        if not ed25519_verify(
            key.key,
            signature.signature + signature.trusted_comment.encode("utf-8"),
            signature.global_signature,
        ):
            raise MinisignError(
                "the trusted comment is not covered by a valid global "
                "signature -- the version/serial may have been tampered with"
            )
        return key
    raise MinisignError("signature does not verify against the trusted key")


def verify_file(
    path: str | Path,
    signature_path: str | Path,
    public_keys: list[PublicKey],
) -> PublicKey:
    """:func:`verify_bytes` for a file plus its `.minisig`."""
    return verify_bytes(
        Path(path).read_bytes(), Signature.read(signature_path), public_keys
    )
