# Generated by tools/gen_native_stub.py -- DO NOT EDIT BY HAND.
#
# Mirrors the compiled PyO3 extension `glaurung._native`. Regenerate with
#     uv run maturin develop --release && uv run python tools/gen_native_stub.py
# `python/tests/test_native_stub_current.py` fails when this file drifts from
# the built module.
#
# Parameter and return types are `Any`: PyO3 exposes arity, parameter names
# and defaults, but no types. Arity and keyword names are therefore checked;
# types deliberately are not.

# `glaurung/__init__.py` registers `glaurung._native.analysis` in
# `sys.modules` as `glaurung.analysis`, so `import glaurung.analysis` works at
# runtime and must type-check. Each name is listed rather than
# star-imported, so a name vanishing from the extension shows up as a
# diff in this file.

from glaurung._native import analysis as _mod

CFR_CONFIDENT_SIGNIFICANCE = _mod.CFR_CONFIDENT_SIGNIFICANCE
CFR_SCHEME = _mod.CFR_SCHEME
CfrSignature = _mod.CfrSignature
CfrWeights = _mod.CfrWeights
FLIRT_MASKED_PATTERN_SCHEME = _mod.FLIRT_MASKED_PATTERN_SCHEME
GSIG_FORMAT_VERSION = _mod.GSIG_FORMAT_VERSION
IDENTITY_GATE_KIND = _mod.IDENTITY_GATE_KIND
STRUCTURAL_SCHEME = _mod.STRUCTURAL_SCHEME
StructuralSignature = _mod.StructuralSignature
VALUE_SCHEME = _mod.VALUE_SCHEME
ValueFingerprint = _mod.ValueFingerprint
WarpConstraint = _mod.WarpConstraint
WarpFunction = _mod.WarpFunction
analyze_functions_bytes = _mod.analyze_functions_bytes
analyze_functions_bytes_with_stats = _mod.analyze_functions_bytes_with_stats
analyze_functions_path = _mod.analyze_functions_path
analyze_functions_path_with_stats = _mod.analyze_functions_path_with_stats
cfr_build_weights = _mod.cfr_build_weights
cfr_confidence = _mod.cfr_confidence
cfr_distance = _mod.cfr_distance
cfr_signatures_path = _mod.cfr_signatures_path
cfr_similarity = _mod.cfr_similarity
cil_methods_path = _mod.cil_methods_path
data_xrefs_path = _mod.data_xrefs_path
detect_entry_bytes = _mod.detect_entry_bytes
detect_entry_path = _mod.detect_entry_path
elf_got_map_path = _mod.elf_got_map_path
elf_plt_map_path = _mod.elf_plt_map_path
find_code_pointers_bytes = _mod.find_code_pointers_bytes
find_code_pointers_path = _mod.find_code_pointers_path
flirt_gsig_write_from_json_str = _mod.flirt_gsig_write_from_json_str
flirt_library_info_path = _mod.flirt_library_info_path
flirt_library_match_bytes = _mod.flirt_library_match_bytes
flirt_library_to_json_str = _mod.flirt_library_to_json_str
flirt_match_functions_with_evidence_path = _mod.flirt_match_functions_with_evidence_path
flirt_signatures_from_archive_path = _mod.flirt_signatures_from_archive_path
gopclntab_names_path = _mod.gopclntab_names_path
identity_gate_build = _mod.identity_gate_build
identity_gate_contains = _mod.identity_gate_contains
identity_gate_n_keys = _mod.identity_gate_n_keys
index_java_archive_bytes = _mod.index_java_archive_bytes
index_java_archive_path = _mod.index_java_archive_path
ioctl_surface_map_bytes = _mod.ioctl_surface_map_bytes
ioctl_surface_map_path = _mod.ioctl_surface_map_path
macho_stubs_map_path = _mod.macho_stubs_map_path
parse_java_class_bytes = _mod.parse_java_class_bytes
parse_java_class_path = _mod.parse_java_class_path
parse_lua_bytecode_path = _mod.parse_lua_bytecode_path
pe_iat_map_path = _mod.pe_iat_map_path
pe_import_call_sites_path = _mod.pe_import_call_sites_path
pe_list_resources_bytes = _mod.pe_list_resources_bytes
pe_list_resources_path = _mod.pe_list_resources_path
pe_tls_path = _mod.pe_tls_path
pe_view_resource_path = _mod.pe_view_resource_path
rerank_candidates = _mod.rerank_candidates
structural_ranking_similarity = _mod.structural_ranking_similarity
structural_signatures_path = _mod.structural_signatures_path
va_to_file_offset_path = _mod.va_to_file_offset_path
value_distance = _mod.value_distance
value_fingerprints_path = _mod.value_fingerprints_path
value_similarity = _mod.value_similarity
warp_function_guids_path = _mod.warp_function_guids_path
warp_scheme = _mod.warp_scheme
