# Generated by tools/gen_native_stub.py -- DO NOT EDIT BY HAND.
#
# Mirrors the compiled PyO3 extension `glaurung._native`. Regenerate with
#     uv run maturin develop --release && uv run python tools/gen_native_stub.py
# `python/tests/test_native_stub_current.py` fails when this file drifts from
# the built module.
#
# Parameter and return types are `Any`: PyO3 exposes arity, parameter names
# and defaults, but no types. Arity and keyword names are therefore checked;
# types deliberately are not.

# `glaurung/__init__.py` registers `glaurung._native.debug` in
# `sys.modules` as `glaurung.debug`, so `import glaurung.debug` works at
# runtime and must type-check. Each name is listed rather than
# star-imported, so a name vanishing from the extension shows up as a
# diff in this file.

from glaurung._native import debug as _mod

analyze_pe_pdb_cache_path = _mod.analyze_pe_pdb_cache_path
extract_dwarf_signatures_path = _mod.extract_dwarf_signatures_path
extract_dwarf_types_path = _mod.extract_dwarf_types_path
