# Generated by tools/gen_native_stub.py -- DO NOT EDIT BY HAND.
#
# Mirrors the compiled PyO3 extension `glaurung._native`. Regenerate with
#     uv run maturin develop --release && uv run python tools/gen_native_stub.py
# `python/tests/test_native_stub_current.py` fails when this file drifts from
# the built module.
#
# Parameter and return types are `Any`: PyO3 exposes arity, parameter names
# and defaults, but no types. Arity and keyword names are therefore checked;
# types deliberately are not.

# `glaurung/__init__.py` registers `glaurung._native.disasm` in
# `sys.modules` as `glaurung.disasm`, so `import glaurung.disasm` works at
# runtime and must type-check. Each name is listed rather than
# star-imported, so a name vanishing from the extension shows up as a
# diff in this file.

from glaurung._native import disasm as _mod

PyDisassembler = _mod.PyDisassembler
disassemble_window = _mod.disassemble_window
disassemble_window_at = _mod.disassemble_window_at
disassembler_for_path = _mod.disassembler_for_path
