# Generated by tools/gen_native_stub.py -- DO NOT EDIT BY HAND.
#
# Mirrors the compiled PyO3 extension `glaurung._native`. Regenerate with
#     uv run maturin develop --release && uv run python tools/gen_native_stub.py
# `python/tests/test_native_stub_current.py` fails when this file drifts from
# the built module.
#
# Parameter and return types are `Any`: PyO3 exposes arity, parameter names
# and defaults, but no types. Arity and keyword names are therefore checked;
# types deliberately are not.

# `glaurung/__init__.py` registers `glaurung._native.ir` in
# `sys.modules` as `glaurung.ir`, so `import glaurung.ir` works at
# runtime and must type-check. Each name is listed rather than
# star-imported, so a name vanishing from the extension shows up as a
# diff in this file.

from glaurung._native import ir as _mod

DecompilerSession = _mod.DecompilerSession
decompile_all = _mod.decompile_all
decompile_at = _mod.decompile_at
decompile_many = _mod.decompile_many
decompile_range_at = _mod.decompile_range_at
lift_bytes = _mod.lift_bytes
lift_window_at = _mod.lift_window_at
take_render_verification = _mod.take_render_verification
