from __future__ import annotations

from pathlib import Path
from typing import Any, Callable, Iterable

def find_code_pointers(path: str | Path, **kwargs: Any) -> list[dict[str, Any]]: ...
def functions_by_seed_kind(
    path: str | Path, **kwargs: Any
) -> dict[str, list[dict[str, Any]]]: ...
def xrefs_to(path: str | Path, va: int, **kwargs: Any) -> list[dict[str, Any]]: ...
def import_callers(
    path: str | Path,
    import_name: str | None = ...,
    *,
    pdb_cache: str | Path | None = ...,
) -> list[dict[str, Any]]: ...
def pdata_at(path: str | Path, va: int, **kwargs: Any) -> dict[str, Any]: ...
def containing_function(
    path: str | Path, va: int, **kwargs: Any
) -> dict[str, Any] | None: ...
def bytes_at(
    path: str | Path, va: int, size: int = ..., **kwargs: Any
) -> dict[str, Any]: ...
def disasm_at(
    path: str | Path, va: int, count: int = ..., **kwargs: Any
) -> list[dict[str, Any]]: ...
def map_windows_driver_surface(path: str | Path, **kwargs: Any) -> dict[str, Any]: ...
def collect_windows_facts(path: str | Path, **kwargs: Any) -> dict[str, Any]: ...
def explain_va_from_facts(
    facts: dict[str, Any], va: int, *, byte_count: int = ...
) -> dict[str, Any]: ...
def classify_function_start_from_facts(
    facts: dict[str, Any],
    va: int,
    *,
    byte_count: int = ...,
) -> dict[str, Any]: ...
def classify_function_start(
    path: str | Path, va: int, *, byte_count: int = ..., **kwargs: Any
) -> dict[str, Any]: ...
def explain_va(
    path: str | Path, va: int, *, byte_count: int = ...
) -> dict[str, Any]: ...
def diff_ghidra(
    path: str | Path, ghidra_json: str | Path, **kwargs: Any
) -> dict[str, Any]: ...
def run_fact_rules(
    path: str | Path,
    rules: Iterable[Callable[[dict[str, Any]], Any]],
    **kwargs: Any,
) -> list[Any]: ...
