"""`docs/reference/cli.md` must match what `tools/gen_cli_reference.py` produces.

The CLI reference used to be a hand-maintained 36-command cheatsheet (moved
under `docs/tutorial/` before landing at its current path) that listed "safe
invocation shapes, not every option" and had already drifted from the
40-command `_REGISTRY` in `python/glaurung/cli/main.py`.
`tools/gen_cli_reference.py` reads the real
`argparse` parsers instead, so this test -- same shape as
`test_native_stub_current.py` for the native stubs -- is what stops the
replacement from drifting the same way: it regenerates the page from the
live parser tree and fails on any difference other than the commit-sha
banner line, which changes on every commit by design.
"""

from __future__ import annotations

import importlib.util
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
GENERATOR = ROOT / "tools" / "gen_cli_reference.py"
OUT_PATH = ROOT / "docs" / "reference" / "cli.md"

SHA_LINE_RE = re.compile(
    r"^<!-- generated by [^ ]+ at [0-9a-f]+; do not edit -->$", re.MULTILINE
)


def _load_generator():
    spec = importlib.util.spec_from_file_location("_gen_cli_reference", GENERATOR)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _normalize(text: str) -> str:
    return SHA_LINE_RE.sub("<!-- generated; do not edit -->", text)


def test_generator_and_output_are_present() -> None:
    assert GENERATOR.is_file(), f"missing {GENERATOR}"
    assert OUT_PATH.is_file(), f"missing {OUT_PATH}"


def test_generated_reference_matches_committed_file() -> None:
    gen = _load_generator()
    generated = gen.generate()
    committed = OUT_PATH.read_text()
    assert _normalize(generated) == _normalize(committed), (
        f"{OUT_PATH.relative_to(ROOT)} is stale against tools/gen_cli_reference.py; "
        "regenerate with `uv run python tools/gen_cli_reference.py`"
    )


def test_kind_and_status_banner_present() -> None:
    head = "\n".join(OUT_PATH.read_text().splitlines()[:5])
    assert "**Kind:** reference" in head
    assert "**Status:** generated" in head


def test_every_registered_command_has_a_section() -> None:
    """Every command in `_REGISTRY` gets its own `## `glaurung <name>`` section.

    Guards against the generator silently dropping a command (e.g. a KeyError
    swallowed somewhere) rather than failing loudly.
    """
    import importlib

    climain = importlib.import_module("glaurung.cli.main")
    text = OUT_PATH.read_text()
    missing = [
        name for name in climain._REGISTRY if f"## `glaurung {name}`" not in text
    ]
    assert not missing, f"cli.md is missing sections for: {missing}"


def test_check_mode_exits_zero_against_the_committed_file() -> None:
    """`--check` is the gate other agents and CI actually run."""
    gen = _load_generator()
    assert gen.main(["--check"]) == 0
