"""Tests for `tools/fitness_report.py`: the file-size fitness measures from
`docs/design/decompiler-roadmap.md`'s "Code quality, composition, and
file-size program", and the committed-baseline ratchet over them.

The end-state targets in the roadmap are not met today (the tree is far from
them), so these tests do NOT assert the targets. They assert two different
things:

1. The pure measurement functions do what their docstrings say, on small
   synthetic inputs.
2. The measures computed from the real `src/` tree are never WORSE than the
   committed `tools/fitness_baseline.json` -- that is the ratchet. Rerun
   `tools/fitness_report.py --write-baseline` deliberately (with review) to
   record an intentional improvement or an explicitly accepted regression.
"""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent.parent
TOOL = ROOT / "tools" / "fitness_report.py"
BASELINE = ROOT / "tools" / "fitness_baseline.json"
SRC = ROOT / "src"


def _load_tool():
    spec = importlib.util.spec_from_file_location("fitness_report", TOOL)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def fr():
    return _load_tool()


# --- is_test_path -----------------------------------------------------------


def test_a_suffixed_test_file_is_excluded(fr):
    assert fr.is_test_path(Path("program/session_tests.rs"))
    assert fr.is_test_path(Path("ir/lift_arm32/packet_tests.rs"))


def test_a_bare_tests_module_is_excluded(fr):
    assert fr.is_test_path(Path("analysis/linux_ioctl/tests.rs"))
    assert fr.is_test_path(Path("ir/ast_tests/deep_regions.rs"))


def test_an_ordinary_product_file_is_not_excluded(fr):
    assert not fr.is_test_path(Path("ir/ast.rs"))
    assert not fr.is_test_path(Path("program/session.rs"))


def test_target_is_not_mistaken_for_test(fr):
    """`target` shares four letters with `test` -- must not collide."""
    assert not fr.is_test_path(Path("target/spec.rs"))


# --- is_generated ------------------------------------------------------------


def test_a_generated_marker_in_the_header_is_detected(fr):
    text = "// @generated by some-tool\nconst TABLE: &[u8] = &[0, 1, 2];\n"
    assert fr.is_generated(text)


def test_a_marker_past_the_header_window_does_not_exempt_the_file(fr):
    """Mixed-responsibility logic is not an exemption: only a genuinely
    generated file (marker up front) is exempt."""
    text = "\n".join(f"fn f{i}() {{}}" for i in range(30)) + "\n// @generated\n"
    assert not fr.is_generated(text)


def test_ordinary_source_is_not_generated(fr):
    assert not fr.is_generated("//! A module doc comment.\nfn f() {}\n")


# --- strip_test_items / product_loc ------------------------------------------


def test_a_cfg_test_mod_block_is_stripped(fr):
    text = (
        "fn product() {}\n"
        "\n"
        "#[cfg(test)]\n"
        "mod tests {\n"
        "    #[test]\n"
        "    fn it_works() {\n"
        "        assert_eq!(1, 1);\n"
        "    }\n"
        "}\n"
    )
    stripped = fr.strip_test_items(text)
    assert "product()" in stripped
    assert "it_works" not in stripped
    assert "assert_eq" not in stripped


def test_a_single_cfg_test_function_is_stripped(fr):
    """Not every test-only item lives inside `mod tests` -- e.g.
    `constraint_cache.rs`'s `reset_process_cache_for_test`."""
    text = (
        "fn product() {}\n"
        "\n"
        "#[cfg(test)]\n"
        "pub(crate) fn helper_for_test() {\n"
        "    do_a_thing();\n"
        "}\n"
        "\n"
        "fn more_product() {}\n"
    )
    stripped = fr.strip_test_items(text)
    assert "product()" in stripped and "more_product()" in stripped
    assert "helper_for_test" not in stripped


def test_a_braceless_cfg_test_item_is_stripped_to_its_semicolon(fr):
    text = "fn product() {}\n\n#[cfg(test)]\nuse super::helpers::*;\n\nfn more() {}\n"
    stripped = fr.strip_test_items(text)
    assert "helpers" not in stripped
    assert "product()" in stripped and "more()" in stripped


def test_nested_cfg_test_modules_are_fully_consumed(fr):
    text = (
        "fn product() {}\n"
        "#[cfg(test)]\n"
        "mod tests {\n"
        "    #[cfg(test)]\n"
        "    mod nested {\n"
        "        fn inner_test() {}\n"
        "    }\n"
        "    fn outer_test() {}\n"
        "}\n"
        "fn tail() {}\n"
    )
    stripped = fr.strip_test_items(text)
    assert stripped.strip().splitlines() == ["fn product() {}", "fn tail() {}"]


def test_product_loc_counts_only_surviving_lines(fr):
    text = "a\nb\n#[cfg(test)]\nmod tests {\nc\nd\n}\ne\n"
    assert fr.product_loc(text) == 3  # "a", "b", "e"


def test_a_wholly_test_file_has_zero_product_loc_after_stripping(fr):
    text = "#[cfg(test)]\nmod tests {\na\nb\nc\n}\n"
    assert fr.product_loc(text) == 0


# --- check_ratchet ------------------------------------------------------------


def _measures(fr, **overrides):
    base = dict.fromkeys(fr.RATCHET_KEYS, 0.0)
    base.update(overrides)
    return {"measures": base}


def test_an_identical_run_has_no_regressions(fr):
    current = _measures(fr, product_mean_loc=400.0, product_files_above_1000=20)
    baseline = _measures(fr, product_mean_loc=400.0, product_files_above_1000=20)
    assert fr.check_ratchet(current, baseline) == []


def test_a_higher_mean_is_a_regression(fr):
    baseline = {"measures": dict.fromkeys(fr.RATCHET_KEYS, 0.0)}
    current = {"measures": dict(baseline["measures"])}
    baseline["measures"]["product_mean_loc"] = 400.0
    current["measures"]["product_mean_loc"] = 420.0
    problems = fr.check_ratchet(current, baseline)
    assert problems == ["product_mean_loc: 400.0 -> 420.0 (worse)"]


def test_a_lower_mean_is_not_a_regression(fr):
    baseline = {"measures": dict.fromkeys(fr.RATCHET_KEYS, 0.0)}
    current = {"measures": dict(baseline["measures"])}
    baseline["measures"]["product_mean_loc"] = 400.0
    current["measures"]["product_mean_loc"] = 390.0
    assert fr.check_ratchet(current, baseline) == []


def test_one_more_file_above_1000_is_a_regression(fr):
    baseline = {"measures": dict.fromkeys(fr.RATCHET_KEYS, 0.0)}
    current = {"measures": dict(baseline["measures"])}
    baseline["measures"]["product_files_above_1000"] = 27
    current["measures"]["product_files_above_1000"] = 28
    assert fr.check_ratchet(current, baseline) == [
        "product_files_above_1000: 27 -> 28 (worse)"
    ]


def test_integer_counts_have_no_slack(fr):
    """Files-above-N counts are exact integers; any increase is real, unlike
    the float measures which get a tiny float-noise tolerance."""
    baseline = {"measures": dict.fromkeys(fr.RATCHET_KEYS, 0)}
    current = {"measures": dict(baseline["measures"])}
    baseline["measures"]["ir_files_above_1000"] = 5
    current["measures"]["ir_files_above_1000"] = 6
    assert fr.check_ratchet(current, baseline) != []


def test_a_tiny_float_wobble_is_not_a_regression(fr):
    baseline = {"measures": dict.fromkeys(fr.RATCHET_KEYS, 0.0)}
    current = {"measures": dict(baseline["measures"])}
    baseline["measures"]["product_median_loc"] = 250.0
    current["measures"]["product_median_loc"] = 250.0 + 1e-9
    assert fr.check_ratchet(current, baseline) == []


# --- the real ratchet ---------------------------------------------------------


def test_baseline_file_is_committed_and_well_formed(fr):
    baseline = fr.load_baseline(BASELINE)
    for key in fr.RATCHET_KEYS:
        assert isinstance(baseline["measures"][key], (int, float))


def test_the_real_src_tree_has_not_regressed_against_the_committed_baseline(fr):
    """The ratchet. This must NOT require the targets to be met -- only that
    no measure got worse than the committed baseline.

    Regenerate the baseline deliberately with
    `tools/fitness_report.py --write-baseline` (and review the diff) when a
    change is an intentional, accepted movement -- never to silence this
    test without looking at why a measure moved.
    """
    baseline = fr.load_baseline(BASELINE)
    current = fr.build_report(SRC)
    problems = fr.check_ratchet(current, baseline)
    assert problems == [], (
        "file-size fitness regressed against tools/fitness_baseline.json:\n"
        + "\n".join(problems)
    )


def test_the_committed_baseline_reproduces_todays_measured_values(fr):
    """Pin the exact current numbers so a silent drift in the measurement
    methodology itself (not the source tree) is caught too. Update this
    alongside the baseline file when it is deliberately regenerated."""
    with BASELINE.open(encoding="utf-8") as handle:
        baseline = json.load(handle)
    assert baseline["measures"] == {
        "ir_files_above_1000": 15,
        "ir_median_loc": pytest.approx(469.5),
        "product_files_above_1000": 29,
        "product_files_above_2000": 14,
        "product_mean_loc": pytest.approx(529.031545741325),
        "product_median_loc": 276,
        "product_pct_loc_above_1000": pytest.approx(44.87695509323029),
    }


# --- CLI smoke test -----------------------------------------------------------


def test_cli_check_ratchet_exits_zero_on_the_real_tree():
    import subprocess

    result = subprocess.run(
        ["python3", str(TOOL), "--check-ratchet"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, result.stdout + result.stderr
    assert "no regressions" in result.stdout
