"""Tests for `tools/fitness_report.py`: the file-size fitness measures from
`docs/design/decompiler-roadmap.md`'s "Code quality, composition, and
file-size program", and the committed-baseline ratchet over them.

The end-state targets in the roadmap are not met today (the tree is far from
them), so these tests do NOT assert the targets. They assert two different
things:

1. The pure measurement functions do what their docstrings say, on small
   synthetic inputs.
2. The measures computed from the real `src/` tree are never WORSE than the
   committed `tools/fitness_baseline.json` -- that is the ratchet. Rerun
   `tools/fitness_report.py --write-baseline` deliberately (with review) to
   record an intentional improvement or an explicitly accepted regression.
"""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent.parent
TOOL = ROOT / "tools" / "fitness_report.py"
BASELINE = ROOT / "tools" / "fitness_baseline.json"
SRC = ROOT / "src"


def _load_tool():
    spec = importlib.util.spec_from_file_location("fitness_report", TOOL)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def fr():
    return _load_tool()


# --- is_test_path -----------------------------------------------------------


def test_a_suffixed_test_file_is_excluded(fr):
    assert fr.is_test_path(Path("program/session_tests.rs"))
    assert fr.is_test_path(Path("ir/lift_arm32/packet_tests.rs"))


def test_a_bare_tests_module_is_excluded(fr):
    assert fr.is_test_path(Path("analysis/linux_ioctl/tests.rs"))
    assert fr.is_test_path(Path("ir/ast_tests/deep_regions.rs"))


def test_an_ordinary_product_file_is_not_excluded(fr):
    assert not fr.is_test_path(Path("ir/ast.rs"))
    assert not fr.is_test_path(Path("program/session.rs"))


def test_target_is_not_mistaken_for_test(fr):
    """`target` shares four letters with `test` -- must not collide."""
    assert not fr.is_test_path(Path("target/spec.rs"))


# --- is_generated ------------------------------------------------------------


def test_a_generated_marker_in_the_header_is_detected(fr):
    text = "// @generated by some-tool\nconst TABLE: &[u8] = &[0, 1, 2];\n"
    assert fr.is_generated(text)


def test_a_marker_past_the_header_window_does_not_exempt_the_file(fr):
    """Mixed-responsibility logic is not an exemption: only a genuinely
    generated file (marker up front) is exempt."""
    text = "\n".join(f"fn f{i}() {{}}" for i in range(30)) + "\n// @generated\n"
    assert not fr.is_generated(text)


def test_ordinary_source_is_not_generated(fr):
    assert not fr.is_generated("//! A module doc comment.\nfn f() {}\n")


# --- strip_test_items / product_loc ------------------------------------------


def test_a_cfg_test_mod_block_is_stripped(fr):
    text = (
        "fn product() {}\n"
        "\n"
        "#[cfg(test)]\n"
        "mod tests {\n"
        "    #[test]\n"
        "    fn it_works() {\n"
        "        assert_eq!(1, 1);\n"
        "    }\n"
        "}\n"
    )
    stripped = fr.strip_test_items(text)
    assert "product()" in stripped
    assert "it_works" not in stripped
    assert "assert_eq" not in stripped


def test_a_single_cfg_test_function_is_stripped(fr):
    """Not every test-only item lives inside `mod tests` -- e.g.
    `constraint_cache.rs`'s `reset_process_cache_for_test`."""
    text = (
        "fn product() {}\n"
        "\n"
        "#[cfg(test)]\n"
        "pub(crate) fn helper_for_test() {\n"
        "    do_a_thing();\n"
        "}\n"
        "\n"
        "fn more_product() {}\n"
    )
    stripped = fr.strip_test_items(text)
    assert "product()" in stripped and "more_product()" in stripped
    assert "helper_for_test" not in stripped


def test_a_braceless_cfg_test_item_is_stripped_to_its_semicolon(fr):
    text = "fn product() {}\n\n#[cfg(test)]\nuse super::helpers::*;\n\nfn more() {}\n"
    stripped = fr.strip_test_items(text)
    assert "helpers" not in stripped
    assert "product()" in stripped and "more()" in stripped


def test_nested_cfg_test_modules_are_fully_consumed(fr):
    text = (
        "fn product() {}\n"
        "#[cfg(test)]\n"
        "mod tests {\n"
        "    #[cfg(test)]\n"
        "    mod nested {\n"
        "        fn inner_test() {}\n"
        "    }\n"
        "    fn outer_test() {}\n"
        "}\n"
        "fn tail() {}\n"
    )
    stripped = fr.strip_test_items(text)
    assert stripped.strip().splitlines() == ["fn product() {}", "fn tail() {}"]


def test_product_loc_counts_only_surviving_lines(fr):
    text = "a\nb\n#[cfg(test)]\nmod tests {\nc\nd\n}\ne\n"
    assert fr.product_loc(text) == 3  # "a", "b", "e"


def test_a_wholly_test_file_has_zero_product_loc_after_stripping(fr):
    text = "#[cfg(test)]\nmod tests {\na\nb\nc\n}\n"
    assert fr.product_loc(text) == 0


# --- check_ratchet ------------------------------------------------------------


def _measures(fr, **overrides):
    base = dict.fromkeys(fr.RATCHET_KEYS, 0.0)
    base.update(overrides)
    return {"measures": base}


def test_an_identical_run_has_no_regressions(fr):
    current = _measures(fr, product_mean_loc=400.0, product_files_above_1000=20)
    baseline = _measures(fr, product_mean_loc=400.0, product_files_above_1000=20)
    assert fr.check_ratchet(current, baseline) == []


def test_a_higher_mean_is_a_regression(fr):
    baseline = {"measures": dict.fromkeys(fr.RATCHET_KEYS, 0.0)}
    current = {"measures": dict(baseline["measures"])}
    baseline["measures"]["product_mean_loc"] = 400.0
    current["measures"]["product_mean_loc"] = 420.0
    problems = fr.check_ratchet(current, baseline)
    assert problems == ["product_mean_loc: 400.0 -> 420.0 (worse)"]


def test_a_lower_mean_is_not_a_regression(fr):
    baseline = {"measures": dict.fromkeys(fr.RATCHET_KEYS, 0.0)}
    current = {"measures": dict(baseline["measures"])}
    baseline["measures"]["product_mean_loc"] = 400.0
    current["measures"]["product_mean_loc"] = 390.0
    assert fr.check_ratchet(current, baseline) == []


def test_one_more_file_above_1000_is_a_regression(fr):
    baseline = {"measures": dict.fromkeys(fr.RATCHET_KEYS, 0.0)}
    current = {"measures": dict(baseline["measures"])}
    baseline["measures"]["product_files_above_1000"] = 27
    current["measures"]["product_files_above_1000"] = 28
    assert fr.check_ratchet(current, baseline) == [
        "product_files_above_1000: 27 -> 28 (worse)"
    ]


def test_integer_counts_have_no_slack(fr):
    """Files-above-N counts are exact integers; any increase is real, unlike
    the float measures which get a tiny float-noise tolerance."""
    baseline = {"measures": dict.fromkeys(fr.RATCHET_KEYS, 0)}
    current = {"measures": dict(baseline["measures"])}
    baseline["measures"]["ir_files_above_1000"] = 5
    current["measures"]["ir_files_above_1000"] = 6
    assert fr.check_ratchet(current, baseline) != []


def test_a_tiny_float_wobble_is_not_a_regression(fr):
    baseline = {"measures": dict.fromkeys(fr.RATCHET_KEYS, 0.0)}
    current = {"measures": dict(baseline["measures"])}
    baseline["measures"]["product_median_loc"] = 250.0
    current["measures"]["product_median_loc"] = 250.0 + 1e-9
    assert fr.check_ratchet(current, baseline) == []


# --- the real ratchet ---------------------------------------------------------


def test_baseline_file_is_committed_and_well_formed(fr):
    baseline = fr.load_baseline(BASELINE)
    for key in fr.RATCHET_KEYS:
        assert isinstance(baseline["measures"][key], (int, float))


def test_the_real_src_tree_has_not_regressed_against_the_committed_baseline(fr):
    """The ratchet. This must NOT require the targets to be met -- only that
    no measure got worse than the committed baseline.

    Regenerate the baseline deliberately with
    `tools/fitness_report.py --write-baseline` (and review the diff) when a
    change is an intentional, accepted movement -- never to silence this
    test without looking at why a measure moved.
    """
    baseline = fr.load_baseline(BASELINE)
    current = fr.build_report(SRC)
    problems = fr.check_ratchet(current, baseline)
    assert problems == [], (
        "file-size fitness regressed against tools/fitness_baseline.json:\n"
        + "\n".join(problems)
    )


def test_the_committed_baseline_reproduces_todays_measured_values(fr):
    """Pin the exact current numbers so a silent drift in the measurement
    methodology itself (not the source tree) is caught too. Update this
    alongside the baseline file when it is deliberately regenerated.

    2026-08-16: the dec-renderer extraction moved these deliberately. It took
    `src/ir/ast.rs` from 11,582 product LOC to 9,461 by lifting a 2,170-line,
    one-owner renderer into `src/ir/ast/dec_render.rs` -- and made FOUR of the
    seven then-existing measures worse, because a split necessarily adds a file
    to both "files above N" buckets. That is the measurement failing to see the
    work, not the work going the wrong way, which is why `product_max_loc`
    joined the set in the same change: it is the only measure that moves in the
    direction the decomposition program moves.

    2026-08-16 (same day, next cut): the ctx-renderer extraction lifted the
    generic `render`/`render_with_types` engine (`write_expr_ctx`,
    `write_stmt_ctx`, and seven more items the call graph pulled in that
    weren't on the original candidate list) into `src/ir/ast/ctx_render.rs`,
    746 lines. `product_max_loc` moved again, 9,461 -> 8,762, and every other
    measure held or improved except `ir_median_loc` (491 -> 492), which ticked
    up by one line for the same file-count-bucket reason the four regressions
    above did: shrinking the largest file changes which file sits at the
    median position. Recorded as accepted, with drift, rather than chased.

    2026-08-17 (third cut): the untyped C renderer (`render_c`, `write_reg_c`,
    `write_expr_c`, `write_stmt_c`, `write_for_clause_c`) moved into
    `src/ir/ast/c_render.rs`, 562 lines. `binop_sym_c` and `cmpop_sym_c` sit at
    the same physical spot the candidate range named as its end, but the call
    graph says otherwise: `dec_render.rs` calls both directly, so they stayed
    in the parent as newly-recognised shared vocabulary rather than moving --
    keeping newly-widened visibility at zero. `product_max_loc` moved again,
    8,762 -> 8,247, and every other measure held except `ir_median_loc`
    (492 -> 493), the same one-line file-count-bucket tick the ctx cut hit.
    Recorded as accepted, with drift, rather than chased.

    2026-08-17 (first lifter cut): the x86 packed/SSE family moved out of
    `src/ir/lift_x86.rs` into `src/ir/lift_x86/packed.rs`, 846 lines, taking
    that file 4,998 -> 4,183 product LOC. NOT ONE OF THE EIGHT MEASURES CAN SEE
    IT AS AN IMPROVEMENT, and one of them calls it a regression. `product_max_loc`
    -- the measure added precisely so decomposition would be visible -- did not
    move, because `ir/ast.rs` at 7,920 is still the largest file and this cut was
    to the THIRD largest. Meanwhile `product_median_loc` went 276 -> 279: adding
    any file above the median shifts the median up, so every cut this program
    makes worsens it by construction. `product_max_loc` only sees the single
    worst owner; the program works the list top-down and the list is long. That
    is a gap in the measurement, recorded as accepted with drift rather than
    chased. Part of the move was pre-existing: the tree measured 277.5 before
    this cut, inside the 2-LOC median tolerance and so never recorded.
    `product_max_loc` (8,247 -> 7,920), `product_mean_loc` and
    `product_pct_loc_above_1000` also fold in improvements committed between the
    c_render cut and this one.

    2026-08-17 (third cfg cut): the authoritative PE metadata tables --
    `parse_pdata_function_starts`, `parse_pe_export_function_starts` and the
    three unwind-record predicates the `.pdata` walk chains through -- moved
    into `src/analysis/cfg/pe_tables.rs`, 426 product LOC. `analysis/cfg.rs`
    went 4,066 -> 3,684 and is still the largest product file, so this is the
    rarer case where `product_max_loc` DOES see the cut: 4,066 -> 3,684, and
    `product_loc_above_1000` fell by exactly the 382 lines that left the file
    (61,896 -> 61,514). The cluster is two disjoint line ranges, not one:
    `pe_va_to_file_off` sits physically between them and has 11 call sites, 7
    of them in the sibling `cfg/scan.rs`, so a contiguous cut would have taken
    it along and broken the sibling. `product_median_loc` ticked 305 -> 307,
    the same file-count-bucket effect every cut in this program produces; it is
    exempt from the ratchet and recorded here rather than chased.
    """
    with BASELINE.open(encoding="utf-8") as handle:
        baseline = json.load(handle)
    assert baseline["measures"] == {
        "ir_files_above_1000": 15,
        "ir_median_loc": 493,
        "product_files_above_1000": 29,
        "product_files_above_2000": 12,
        "product_loc_above_1000": 55210,
        "product_max_loc": 3357,
        "product_mean_loc": pytest.approx(476.64225352112675),
        "product_median_loc": 311,
        "product_pct_loc_above_1000": pytest.approx(32.6284809228878),
    }


# --- CLI smoke test -----------------------------------------------------------


def test_cli_check_ratchet_exits_zero_on_the_real_tree():
    import subprocess

    result = subprocess.run(
        ["python3", str(TOOL), "--check-ratchet"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, result.stdout + result.stderr
    assert "no regressions" in result.stdout


# --- median tolerance --------------------------------------------------------
#
# Medians are order statistics over a population whose SIZE changes when a file
# is added, so they move for reasons unrelated to the tree getting worse. Three
# legitimate improvements tripped a median ceiling on 2026-08-17, every one of
# them a change that made the largest owner SMALLER. See the comment on
# `_MEDIAN_KEYS` in the tool.


def test_medians_are_reported_but_never_ratcheted(fr):
    """A median is an order statistic over a population whose SIZE changes when a
    file is added, so it moves by an amount set by the local gap in the size
    distribution -- which is unbounded. A 2-LOC tolerance was tried and defeated
    within a day: calibrated where neighbours were 1 LOC apart, then hit a 17-LOC
    gap (`value_split.rs` 493, `regview.rs` 510) that moved `ir_median_loc` to
    501.5 with no file changing size near the median.

    They stay in TARGETS, reported against the end-state goal. They are not
    ceilings a change can violate."""
    baseline = {"measures": dict.fromkeys(fr.RATCHET_KEYS, 0.0)}
    current = {"measures": dict(baseline["measures"])}
    baseline["measures"]["product_median_loc"] = 276.0
    current["measures"]["product_median_loc"] = 999.0
    baseline["measures"]["ir_median_loc"] = 492.0
    current["measures"]["ir_median_loc"] = 501.5
    assert fr.check_ratchet(current, baseline) == []
    # ...but they are still MEASURED and still carry an end-state target.
    assert "product_median_loc" in fr.RATCHET_KEYS
    assert {"product_median_loc", "ir_median_loc"} <= {k for k, _l, _t in fr.TARGETS}


def test_the_measures_that_track_the_program_keep_zero_tolerance(fr):
    """`product_max_loc` is what the decomposition is FOR, and the "files above
    N" counts are exact. None of them may borrow the median's slack."""
    for key, before, after in (
        ("product_max_loc", 8247, 8248),
        ("product_files_above_1000", 30, 31),
        ("product_files_above_2000", 15, 16),
        ("ir_files_above_1000", 16, 17),
    ):
        baseline = {"measures": dict.fromkeys(fr.RATCHET_KEYS, 0)}
        current = {"measures": dict(baseline["measures"])}
        baseline["measures"][key] = before
        current["measures"][key] = after
        assert fr.check_ratchet(current, baseline) == [
            f"{key}: {before} -> {after} (worse)"
        ], key


def test_the_absolute_above_1000_measure_sees_a_cut_to_a_non_largest_file(fr):
    """Why `product_loc_above_1000` exists. `product_max_loc` watches only the
    single worst owner, so a cut to the THIRD-largest file leaves it unchanged
    and no measure records the work. Modelled on the real 2026-08-17 `lift_x86`
    packed-family cut: 815 LOC out of a 4,998-LOC file into an 846-LOC one."""
    baseline = {"measures": dict.fromkeys(fr.RATCHET_KEYS, 0)}
    current = {"measures": dict(baseline["measures"])}
    baseline["measures"]["product_max_loc"] = 7920
    current["measures"]["product_max_loc"] = 7920  # blind: not the largest file
    baseline["measures"]["product_loc_above_1000"] = 74204
    current["measures"]["product_loc_above_1000"] = 73389
    assert fr.check_ratchet(current, baseline) == []
    # And it is a real ceiling, not decoration: moving LOC the other way fails.
    current["measures"]["product_loc_above_1000"] = 74205
    assert fr.check_ratchet(current, baseline) == [
        "product_loc_above_1000: 74204 -> 74205 (worse)"
    ]


# --- cfg(all(test, ...)) ------------------------------------------------------
#
# Matching only the bare `#[cfg(test)]` spelling counted 1,053 lines of test code
# as PRODUCT code tree-wide -- 877 of them in one module in `src/analysis/cfg.rs`,
# which the bug inflated by 19%. Found 2026-08-17 while splitting that file.


def test_a_target_guarded_test_module_is_stripped(fr):
    """`src/analysis/cfg.rs`'s `#[cfg(all(test, target_arch = "x86_64"))] mod
    gcc_dispatch_corpus_tests` -- 877 lines, the single largest instance."""
    text = (
        "fn product() {}\n"
        '#[cfg(all(test, target_arch = "x86_64"))]\n'
        "mod gcc_dispatch_corpus_tests {\n"
        "    fn a_case() {}\n"
        "}\n"
        "fn more_product() {}\n"
    )
    stripped = fr.strip_test_items(text)
    assert "gcc_dispatch_corpus_tests" not in stripped
    assert "product()" in stripped and "more_product()" in stripped


def test_a_feature_guarded_test_module_is_stripped(fr):
    """`src/symbolic/solver/mod.rs` has two, 176 lines between them."""
    text = (
        "fn product() {}\n"
        '#[cfg(all(test, feature = "solver-z3"))]\n'
        "mod z3_tests {\n    fn t() {}\n}\n"
    )
    assert "z3_tests" not in fr.strip_test_items(text)


def test_cfg_not_test_is_product_code_and_is_kept(fr):
    """The most product-like code there is: it exists only in the SHIPPED build.
    A stripper that treated `not(test)` as test-only would delete it."""
    text = "#[cfg(not(test))]\nfn only_in_release() {\n    real_work();\n}\n"
    assert "only_in_release" in fr.strip_test_items(text)


def test_cfg_any_test_is_not_test_only_and_is_kept(fr):
    """`any(test, ...)` also holds when the other alternative does, so the item
    is present in non-test builds too."""
    text = '#[cfg(any(test, feature = "fuzzing"))]\nfn helper() {\n    x();\n}\n'
    assert "helper" in fr.strip_test_items(text)


def test_a_feature_literally_named_test_is_not_a_test_predicate(fr):
    text = '#[cfg(feature = "test")]\nfn shipped() {\n    x();\n}\n'
    assert "shipped" in fr.strip_test_items(text)


# --- per-owner trend ----------------------------------------------------------
#
# Every ratcheted measure is an aggregate over the whole tree, so a single file
# growing is only visible if no other file shrank by as much in the same
# baseline window. `check_owner_trend` is the per-file view. Added 2026-08-18
# after `src/ir/ast/dec_render.rs` went 1,727 -> 1,788 with the ratchet
# reporting "no regressions" throughout, and was noticed only by hand-auditing
# a stale table in the roadmap.


def test_one_owner_growing_is_reported(fr):
    baseline = {"oversized_files": {"ir/ast/dec_render.rs": 1727}}
    current = {"oversized_files": {"ir/ast/dec_render.rs": 1788}}
    assert fr.check_owner_trend(current, baseline) == [
        "ir/ast/dec_render.rs: 1727 -> 1788 (+61)"
    ]


def test_an_owner_that_shrank_is_not_reported(fr):
    baseline = {"oversized_files": {"ir/ast.rs": 2195}}
    current = {"oversized_files": {"ir/ast.rs": 1661}}
    assert fr.check_owner_trend(current, baseline) == []


def test_the_aggregate_ratchet_cannot_see_what_the_per_owner_view_sees(fr):
    """The reason this measure exists, as one assertion.

    `product_loc_above_1000` is a SUM over oversized files. One owner growing by
    61 while another is cut by 500 leaves the sum 439 lines BETTER, so the
    ratchet passes -- correctly, by its own definition. Modelled on the real
    2026-08-18 numbers: the committed baseline's sum was 55,210 against a
    measured 39,232, which is 15,978 lines of slack for any single file to grow
    into unseen.
    """
    measures_before = dict.fromkeys(fr.RATCHET_KEYS, 0)
    measures_before["product_loc_above_1000"] = 55210
    measures_after = dict(measures_before)
    measures_after["product_loc_above_1000"] = 55210 - 500 + 61
    baseline = {
        "measures": measures_before,
        "oversized_files": {"ir/ast/dec_render.rs": 1727, "analysis/cfg.rs": 3120},
    }
    current = {
        "measures": measures_after,
        "oversized_files": {"ir/ast/dec_render.rs": 1788, "analysis/cfg.rs": 2620},
    }
    assert fr.check_ratchet(current, baseline) == []  # blind, and not wrong
    assert fr.check_owner_trend(current, baseline) == [
        "ir/ast/dec_render.rs: 1727 -> 1788 (+61)"
    ]


def test_a_brand_new_owner_is_left_to_the_review_gate(fr):
    """A file that crossed 1,000 for the first time has no baseline size to have
    grown from. `test_large_module_review.py` already refuses it until a review
    is written, so reporting it here would be a second voice on one decision."""
    baseline = {"oversized_files": {"ir/ast.rs": 1661}}
    current = {"oversized_files": {"ir/ast.rs": 1661, "ir/brand_new.rs": 1200}}
    assert fr.check_owner_trend(current, baseline) == []


def test_growth_is_reported_largest_first(fr):
    baseline = {"oversized_files": {"a.rs": 1000, "b.rs": 2000, "c.rs": 3000}}
    current = {"oversized_files": {"a.rs": 1010, "b.rs": 2100, "c.rs": 3001}}
    assert fr.check_owner_trend(current, baseline) == [
        "b.rs: 2000 -> 2100 (+100)",
        "a.rs: 1000 -> 1010 (+10)",
        "c.rs: 3000 -> 3001 (+1)",
    ]


def test_the_trend_works_against_a_baseline_written_before_the_measure_existed(fr):
    """`oversized_files` is new; every committed baseline predating it carries
    only the top-15 `largest_files` list. The check falls back to that list
    rather than requiring a baseline regeneration first -- a measure whose first
    act is to rewrite its own reference point can only ever record the state it
    was born into."""
    baseline = {"largest_files": [{"path": "ir/ast/dec_render.rs", "loc": 1727}]}
    current = {"oversized_files": {"ir/ast/dec_render.rs": 1788}}
    assert fr.check_owner_trend(current, baseline) == [
        "ir/ast/dec_render.rs: 1727 -> 1788 (+61)"
    ]


def test_the_real_tree_records_every_oversized_file_not_just_the_top_15(fr):
    report = fr.build_report(SRC)
    oversized = report["oversized_files"]
    assert len(oversized) == report["measures"]["product_files_above_1000"]
    assert len(oversized) > len(report["largest_files"])
    assert all(loc > fr.OVERSIZED_LOC for loc in oversized.values())


def test_the_committed_baseline_shows_the_growth_this_measure_was_added_for(fr):
    """Not a synthetic case: the tree as committed. If this file is later split
    or its growth is deliberately accepted into a regenerated baseline, this
    assertion is the thing that must be updated, which is the point."""
    baseline = fr.load_baseline(BASELINE)
    current = fr.build_report(SRC)
    assert fr.check_ratchet(current, baseline) == []
    grown = fr.check_owner_trend(current, baseline)
    assert [row.split(":")[0] for row in grown] == ["ir/ast/dec_render.rs"]


def test_owner_growth_is_never_fatal(fr):
    """Deliberate: an oversized file grows when a defect inside it is fixed, and
    a gate that fails on that teaches people to stop fixing them. The claim is
    only that the growth is impossible to not see."""
    baseline = {
        "measures": dict.fromkeys(fr.RATCHET_KEYS, 0),
        "oversized_files": {"ir/ast/dec_render.rs": 1727},
    }
    current = {
        "measures": dict.fromkeys(fr.RATCHET_KEYS, 0),
        "oversized_files": {"ir/ast/dec_render.rs": 1788},
    }
    assert fr.check_owner_trend(current, baseline) != []
    assert fr.check_ratchet(current, baseline) == []
