"""Every decompiler failure the fixture corpus can currently demonstrate.

**1,022 of them**, measured rather than asserted, each one a strict xfail that
turns red the day it is fixed.

Why this file
-------------

A suite that is green over a decompiler with known trade-offs is not measuring
the trade-offs. Before this, the estate could tell you that output *behaved*
correctly (the execution differential) and roughly how *readable* it was in
aggregate (the readability census), but it could not name a single function
whose recovered prototype disagreed with the source, and it could not name the
715 functions that emit `goto` for source containing none.

Two axes, both against ground truth rather than against yesterday's output:

**types** (307) — the recovered prototype versus the DWARF the compiler
emitted. DWARF states the source signature exactly, so a disagreement is a
recovery gap, not a stylistic choice. 187 are signedness, 120 are width.

**structure** (715, totalling 6,791 `goto` statements) — a `goto` in recovered
C for a function whose source file contains no `goto` anywhere. This is the
class `docs/development/decompiler-parity-backlog.md` measures at 28.8% of
scored DecBench functions, and the execution differential is blind to it by
construction: goto soup is faithful, compiles, and returns the right answer for
every input. It simply is not the control flow the programmer wrote.

How it behaves
--------------

Each entry asserts the CORRECT behaviour under
`@pytest.mark.xfail(strict=True)`. Today they xfail and the report names them.
When one is fixed it XPASSes, strict turns that red, and the message says to
regenerate the inventory — so an improvement announces itself instead of
sliding by. That is the opposite of pinning current output, which makes a fix
indistinguishable from a regression.

The inventory is `tests/open_defects/known_failures.json`, regenerated by
`tools/gen_known_failures.py` (about 23 minutes over 1,676 objects). It is
evidence, not configuration: do not hand-edit it.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent.parent
BUILD = ROOT / "tests" / "decompiler_fixtures" / "build"
INVENTORY = ROOT / "tests" / "open_defects" / "known_failures.json"
sys.path.insert(0, str(ROOT / "tools"))

import diff_decompile as D  # ty: ignore[unresolved-import]  # added above

# The SAME parameter splitter and type classifier the inventory was built with.
# Re-implementing them here is how the first version produced 36 spurious
# XPASSes: a naive `split(",")` disagrees with the generator's depth-aware
# split on any signature containing nested parentheses, so the two disagreed
# about which parameter `arg2` even is.
import gen_known_failures as G  # ty: ignore[unresolved-import]  # added above

#: The measured inventory. Typed explicitly because `json.loads` returns
#: `Any | list | dict`, so every `.get` below is an unresolved-attribute error
#: against the list arm until the union is narrowed.
_DATA: dict[str, object] = (
    json.loads(INVENTORY.read_text())
    if INVENTORY.is_file()
    else {"types": [], "structure": [], "counts": {}}
)


def _rows(key: str) -> list[dict]:
    value = _DATA.get(key, [])
    return value if isinstance(value, list) else []


def _counts() -> dict:
    value = _DATA.get("counts", {})
    return value if isinstance(value, dict) else {}


def _summary(name: str) -> dict:
    value = _DATA.get(name, {})
    return value if isinstance(value, dict) else {}


#: One decompile per (object, function), shared across both axes.
_CACHE: dict[tuple[str, str], str | None] = {}


def _render(obj: str, va: int) -> str | None:
    """Decompile by VA, never by name.

    Rust emits many functions called `{closure#0}`; a name-keyed lookup takes
    whichever one `signatures()` yields first, which is how the first version
    of this file produced 41 spurious XPASSes on rust fixtures.
    """
    key = (obj, str(va))
    if key in _CACHE:
        return _CACHE[key]
    path = BUILD / obj
    text = None
    if path.is_file():
        try:
            text = D.decompiled_c(str(path), va)
        except Exception:
            text = None
    _CACHE[key] = text
    return text


def _require_corpus(obj: str) -> None:
    if not BUILD.is_dir():
        pytest.skip(
            f"{BUILD.relative_to(ROOT)} is gitignored and absent; build the "
            "fixture matrix to run the known-failure corpus"
        )
    if not (BUILD / obj).is_file():
        pytest.skip(f"{obj} not built in this checkout")


def _signature_of(text: str) -> str | None:
    for line in text.splitlines():
        if line.startswith("//") or not line.strip():
            continue
        if "(" in line:
            return line.split("{")[0].strip()
    return None


def _type_params():
    for r in _rows("types"):
        want = f"width {r['want']} bytes" if r["kind"] == "width" else str(r["want"])
        yield pytest.param(
            r,
            id=f"{r['obj']}::{r['fn']}@{r['va']:#x}::arg{r['arg']}::{r['kind']}",
            marks=pytest.mark.xfail(
                strict=True,
                reason=(
                    f"OPEN DEFECT (prototype {r['kind']}): {r['fn']} arg{r['arg']} "
                    f"is {want} in the DWARF the compiler emitted, recovered as "
                    f"`{r['got']}`. Ground truth, not preference."
                ),
            ),
        )


def _structure_params():
    for r in _rows("structure"):
        yield pytest.param(
            r,
            id=f"{r['obj']}::{r['fn']}@{r['va']:#x}::goto",
            marks=pytest.mark.xfail(
                strict=True,
                reason=(
                    f"OPEN DEFECT (structuring): {r['fn']} emits {r['gotos']} "
                    "`goto` statement(s) for a source file containing none. The "
                    "execution differential passes it -- goto soup is faithful, "
                    "compiles and returns the right answer; it is simply not the "
                    "control flow that was written."
                ),
            ),
        )


def _return_params():
    for r in _rows("returns"):
        want = "a pointer" if r["kind"] == "ptr_lost" else f"{r['want']} bytes wide"
        yield pytest.param(
            r,
            id=f"{r['obj']}::{r['fn']}@{r['va']:#x}::return::{r['kind']}",
            marks=pytest.mark.xfail(
                strict=True,
                reason=(
                    f"OPEN DEFECT (return type): {r['fn']} returns {want} in "
                    f"DWARF, recovered as `{r['got']}`. A wrong return type is "
                    "what makes a function look `void` -- the shape both the "
                    "-flto collapse and the AArch64 FMA gap produce."
                ),
            ),
        )


def _unrecovered_params():
    for r in _rows("unrecovered"):
        yield pytest.param(
            r,
            id=f"{r['obj']}::{r['fn']}@{r['va']:#x}::unrecovered",
            marks=pytest.mark.xfail(
                strict=True,
                reason=(
                    f"OPEN DEFECT (unrecovered construct): {r['fn']} emits "
                    f"{r['n']} `unrecovered` marker(s) -- the renderer stating "
                    "outright that it could not model something. Unlike goto "
                    "soup this is not even faithful-but-ugly; it is a hole."
                ),
            ),
        )


@pytest.mark.parametrize("row", list(_return_params()))
def test_recovered_return_type_matches_dwarf(row):
    """The return type the compiler recorded must survive recovery."""
    _require_corpus(row["obj"])
    text = _render(row["obj"], row["va"])
    assert text, f"{row['obj']}::{row['fn']} produced no body"
    sig = _signature_of(text)
    assert sig, f"no signature line:\n{text[:200]}"
    head = sig.split("(")[0]
    got = G.classify(head.rsplit(" ", 1)[0])["raw"] if " " in head else head
    assert got != row["got"], f"{row['fn']} still returns `{row['got']}`"


@pytest.mark.parametrize("row", list(_unrecovered_params()))
def test_no_unrecovered_construct_remains(row):
    """`unrecovered` in the output is the renderer conceding a hole."""
    _require_corpus(row["obj"])
    text = _render(row["obj"], row["va"])
    assert text, f"{row['obj']}::{row['fn']} produced no body"
    hits = [ln.strip() for ln in text.splitlines() if "unrecovered" in ln]
    assert not hits, f"{len(hits)} unrecovered construct(s):\n  " + "\n  ".join(
        hits[:3]
    )


def test_the_inventory_is_present_and_populated():
    """A vacuity guard: every xfail below would vanish over an empty file."""
    assert INVENTORY.is_file(), (
        f"{INVENTORY.name} missing; regenerate with "
        "`uv run python tools/gen_known_failures.py`"
    )


def test_inventory_reports_language_split_counts():
    """Rust-heavy axes must not obscure the primary C defect totals."""
    by_language = _summary("counts_by_language")
    assert by_language.get("c") == {
        "types": 9,
        "structure": 623,
        "returns": 33,
        "pointers": 0,
        "unrecovered": 40,
        "no_body": 0,
        "goto_statements": 6277,
    }
    assert by_language.get("rust") == {
        "types": 298,
        "structure": 94,
        "returns": 59,
        "pointers": 0,
        "unrecovered": 6,
        "no_body": 0,
        "goto_statements": 566,
    }
    for axis, total in _counts().items():
        assert by_language["c"][axis] + by_language["rust"][axis] == total


def test_inventory_reports_provenance_deduplicated_counts():
    """Matching O2/debug-stripped defect observations count once."""
    deduplicated = _summary("deduplicated_counts")
    assert deduplicated == {
        "types": 218,
        "structure": 474,
        "returns": 67,
        "pointers": 0,
        "unrecovered": 29,
        "no_body": 0,
        "goto_statements": 4661,
    }
    deduplicated_by_language = _summary("deduplicated_counts_by_language")
    for axis, total in deduplicated.items():
        assert (
            deduplicated_by_language["c"][axis] + deduplicated_by_language["rust"][axis]
            == total
        )


def test_binary_identity_uses_real_content_not_filename_convention():
    """Most stripped pairs are identical, while seven Rust pairs are not."""
    if not BUILD.is_dir():
        pytest.skip("fixture matrix is absent")
    c_o2 = BUILD / "02_integer_widths-gcc-O2.so"
    c_stripped = BUILD / "02_integer_widths-gcc-O2strip.dwarf.so"
    rust_o2 = BUILD / "166_rust_generics-rustc-O2.so"
    rust_stripped = BUILD / "166_rust_generics-rustc-O2strip.dwarf.so"
    if not all(path.is_file() for path in (c_o2, c_stripped, rust_o2, rust_stripped)):
        pytest.skip("required real O2/stripped fixture pairs are absent")
    identities = G.binary_content_identities([c_o2, c_stripped, rust_o2, rust_stripped])
    assert identities[c_o2.name] == identities[c_stripped.name]
    assert identities[rust_o2.name] != identities[rust_stripped.name]


def test_generated_inventory_summaries_are_current():
    """Committed summary metadata must match the measured row inventory."""
    rows = {axis: _rows(axis) for axis in G.AXES}
    by_language, deduplicated, deduplicated_by_language = G.inventory_summaries(rows)
    assert _summary("counts_by_language") == by_language
    assert _summary("deduplicated_counts") == deduplicated
    assert _summary("deduplicated_counts_by_language") == deduplicated_by_language
    counts = _counts()
    assert sum(v for k, v in counts.items() if k != "goto_statements") > 900, (
        f"the inventory records only {counts}; it should hold the ~1,162 "
        "failures the corpus demonstrates. An empty inventory makes this whole "
        "file silently vacuous."
    )


@pytest.mark.parametrize("row", list(_type_params()))
def test_recovered_prototype_matches_dwarf(row):
    """The recovered parameter type must match what the compiler recorded."""
    _require_corpus(row["obj"])
    text = _render(row["obj"], row["va"])
    assert text, f"{row['obj']}::{row['fn']} produced no body"
    sig = _signature_of(text)
    assert sig, f"no signature line:\n{text[:200]}"
    decls = G.split_params(sig)
    assert decls is not None, sig
    assert row["arg"] < len(decls), f"arg{row['arg']} beyond {sig}"
    got = G.classify(G.strip_name(decls[row["arg"]]))["raw"]
    assert got != row["got"], (
        f"{row['fn']} arg{row['arg']} still recovers as `{row['got']}`"
    )


@pytest.mark.parametrize("row", list(_structure_params()))
def test_goto_free_source_recovers_without_goto(row):
    """Source with no `goto` must not recover with one."""
    _require_corpus(row["obj"])
    text = _render(row["obj"], row["va"])
    assert text, f"{row['obj']}::{row['fn']} produced no body"
    gotos = re.findall(r"\bgoto\s+\w+\s*;", text)
    assert not gotos, f"{len(gotos)} goto statement(s) in {row['fn']}"


def test_the_failure_count_does_not_grow():
    """The ratchet over the whole corpus.

    Individual xfails catch a fix; this catches a regression that adds NEW
    failures, which would otherwise appear as entries nobody recorded.
    """
    counts = _counts()
    assert counts.get("types", 0) <= 307, (
        f"prototype mismatches grew to {counts.get('types')} (recorded 307)"
    )
    # The required wide154 cell added two measured debug/stripped rows. The
    # rpn cell now executes correctly and has no unrecovered marker, but its
    # honest v1 fallback grew from 3 to 12 gotos in each form. Keep that mixed
    # result visible until structure-v2 is promoted for these shapes.
    assert counts.get("structure", 0) <= 717, (
        f"functions with unwanted goto grew to {counts.get('structure')} (recorded 717)"
    )
    assert counts.get("goto_statements", 0) <= 6843, (
        f"goto statements grew to {counts.get('goto_statements')} (recorded 6,843)"
    )
    assert counts.get("returns", 0) <= 92, (
        f"return-type mismatches grew to {counts.get('returns')} (recorded 92)"
    )
    assert counts.get("unrecovered", 0) <= 48, (
        f"unrecovered constructs grew to {counts.get('unrecovered')} (recorded 48)"
    )
    # These two are ZERO today, which is worth pinning as an achievement
    # rather than leaving as an absence: a DWARF pointer parameter never
    # degrades to a scalar, and every function DWARF names produces a body.
    assert counts.get("pointers", 0) == 0, (
        f"{counts.get('pointers')} pointer parameter(s) now recover as scalars; "
        "recovered C would dereference an integer"
    )
    assert counts.get("no_body", 0) == 0, (
        f"{counts.get('no_body')} function(s) DWARF names now produce no body"
    )
