"""`docs/reference/cargo-features.md` must match `Cargo.toml` / `src/lib.rs`.

CLAUDE.md's own history is the reason this is generated rather than
hand-written: ledger 02 §1.1 found the feature count, the gate lane count,
and the "what does `cargo test --features python-ext` build" claim all
drifting from `Cargo.toml`/`src/lib.rs`/`scripts/feature-build-gate.sh`
independently. `tools/gen_feature_reference.py` computes the feature
closure the way Cargo does instead of asserting it, so this test -- same
shape as `test_native_stub_current.py` -- fails whenever the committed page
stops matching what the generator derives.
"""

from __future__ import annotations

import importlib.util
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
GENERATOR = ROOT / "tools" / "gen_feature_reference.py"
OUT_PATH = ROOT / "docs" / "reference" / "cargo-features.md"

SHA_LINE_RE = re.compile(
    r"^<!-- generated by [^ ]+ at [0-9a-f]+; do not edit -->$", re.MULTILINE
)


def _load_generator():
    spec = importlib.util.spec_from_file_location("_gen_feature_reference", GENERATOR)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _normalize(text: str) -> str:
    return SHA_LINE_RE.sub("<!-- generated; do not edit -->", text)


def test_generator_and_output_are_present() -> None:
    assert GENERATOR.is_file(), f"missing {GENERATOR}"
    assert OUT_PATH.is_file(), f"missing {OUT_PATH}"


def test_generated_reference_matches_committed_file() -> None:
    gen = _load_generator()
    generated = gen.generate()
    committed = OUT_PATH.read_text()
    assert _normalize(generated) == _normalize(committed), (
        f"{OUT_PATH.relative_to(ROOT)} is stale against tools/gen_feature_reference.py; "
        "regenerate with `uv run python tools/gen_feature_reference.py`"
    )


def test_kind_and_status_banner_present() -> None:
    head = "\n".join(OUT_PATH.read_text().splitlines()[:5])
    assert "**Kind:** reference" in head
    assert "**Status:** generated" in head


def test_every_cargo_feature_has_a_table_row() -> None:
    gen = _load_generator()
    cargo = gen._load_cargo_toml()
    text = OUT_PATH.read_text()
    missing = [name for name in cargo["features"] if f"`{name}`" not in text]
    assert not missing, f"cargo-features.md is missing rows for: {missing}"


def test_python_ext_does_not_pull_in_symbolic() -> None:
    """The specific, previously-costly claim CLAUDE.md records: `cargo test
    --features python-ext` does not compile `src/symbolic/`. Pin it directly
    against the computed closure, not just against the rendered page, so a
    change to the generator's resolution logic cannot quietly invert it.
    """
    gen = _load_generator()
    cargo = gen._load_cargo_toml()
    closure = gen._closure(["default", "python-ext"], cargo["features"])
    assert "symbolic" not in closure
    assert "exec" in closure


def test_check_mode_exits_zero_against_the_committed_file() -> None:
    gen = _load_generator()
    assert gen.main(["--check"]) == 0
