"""Tests for `tools/fitness_report.py`: the file-size fitness measures from
`docs/design/decompiler-roadmap.md`'s "Code quality, composition, and
file-size program", and the committed-baseline ratchet over them.

The end-state targets in the roadmap are not met today (the tree is far from
them), so these tests do NOT assert the targets. They assert two different
things:

1. The pure measurement functions do what their docstrings say, on small
   synthetic inputs.
2. The measures computed from the real `src/` tree are never WORSE than the
   committed `tools/fitness_baseline.json` -- that is the ratchet. Rerun
   `tools/fitness_report.py --write-baseline` deliberately (with review) to
   record an intentional improvement or an explicitly accepted regression.
"""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent.parent
TOOL = ROOT / "tools" / "fitness_report.py"
BASELINE = ROOT / "tools" / "fitness_baseline.json"
SRC = ROOT / "src"


def _load_tool():
    spec = importlib.util.spec_from_file_location("fitness_report", TOOL)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def fr():
    return _load_tool()


# --- is_test_path -----------------------------------------------------------


def test_a_suffixed_test_file_is_excluded(fr):
    assert fr.is_test_path(Path("program/session_tests.rs"))
    assert fr.is_test_path(Path("ir/lift_arm32/packet_tests.rs"))


def test_a_bare_tests_module_is_excluded(fr):
    assert fr.is_test_path(Path("analysis/linux_ioctl/tests.rs"))
    assert fr.is_test_path(Path("ir/ast_tests/deep_regions.rs"))


def test_an_ordinary_product_file_is_not_excluded(fr):
    assert not fr.is_test_path(Path("ir/ast.rs"))
    assert not fr.is_test_path(Path("program/session.rs"))


def test_target_is_not_mistaken_for_test(fr):
    """`target` shares four letters with `test` -- must not collide."""
    assert not fr.is_test_path(Path("target/spec.rs"))


# --- is_generated ------------------------------------------------------------


def test_a_generated_marker_in_the_header_is_detected(fr):
    text = "// @generated by some-tool\nconst TABLE: &[u8] = &[0, 1, 2];\n"
    assert fr.is_generated(text)


def test_a_marker_past_the_header_window_does_not_exempt_the_file(fr):
    """Mixed-responsibility logic is not an exemption: only a genuinely
    generated file (marker up front) is exempt."""
    text = "\n".join(f"fn f{i}() {{}}" for i in range(30)) + "\n// @generated\n"
    assert not fr.is_generated(text)


def test_ordinary_source_is_not_generated(fr):
    assert not fr.is_generated("//! A module doc comment.\nfn f() {}\n")


# --- strip_test_items / product_loc ------------------------------------------


def test_a_cfg_test_mod_block_is_stripped(fr):
    text = (
        "fn product() {}\n"
        "\n"
        "#[cfg(test)]\n"
        "mod tests {\n"
        "    #[test]\n"
        "    fn it_works() {\n"
        "        assert_eq!(1, 1);\n"
        "    }\n"
        "}\n"
    )
    stripped = fr.strip_test_items(text)
    assert "product()" in stripped
    assert "it_works" not in stripped
    assert "assert_eq" not in stripped


def test_a_single_cfg_test_function_is_stripped(fr):
    """Not every test-only item lives inside `mod tests` -- e.g.
    `constraint_cache.rs`'s `reset_process_cache_for_test`."""
    text = (
        "fn product() {}\n"
        "\n"
        "#[cfg(test)]\n"
        "pub(crate) fn helper_for_test() {\n"
        "    do_a_thing();\n"
        "}\n"
        "\n"
        "fn more_product() {}\n"
    )
    stripped = fr.strip_test_items(text)
    assert "product()" in stripped and "more_product()" in stripped
    assert "helper_for_test" not in stripped


def test_a_braceless_cfg_test_item_is_stripped_to_its_semicolon(fr):
    text = "fn product() {}\n\n#[cfg(test)]\nuse super::helpers::*;\n\nfn more() {}\n"
    stripped = fr.strip_test_items(text)
    assert "helpers" not in stripped
    assert "product()" in stripped and "more()" in stripped


def test_nested_cfg_test_modules_are_fully_consumed(fr):
    text = (
        "fn product() {}\n"
        "#[cfg(test)]\n"
        "mod tests {\n"
        "    #[cfg(test)]\n"
        "    mod nested {\n"
        "        fn inner_test() {}\n"
        "    }\n"
        "    fn outer_test() {}\n"
        "}\n"
        "fn tail() {}\n"
    )
    stripped = fr.strip_test_items(text)
    assert stripped.strip().splitlines() == ["fn product() {}", "fn tail() {}"]


def test_product_loc_counts_only_surviving_lines(fr):
    text = "a\nb\n#[cfg(test)]\nmod tests {\nc\nd\n}\ne\n"
    assert fr.product_loc(text) == 3  # "a", "b", "e"


def test_a_wholly_test_file_has_zero_product_loc_after_stripping(fr):
    text = "#[cfg(test)]\nmod tests {\na\nb\nc\n}\n"
    assert fr.product_loc(text) == 0


# --- check_ratchet ------------------------------------------------------------


def _measures(fr, **overrides):
    base = dict.fromkeys(fr.RATCHET_KEYS, 0.0)
    base.update(overrides)
    return {"measures": base}


def test_an_identical_run_has_no_regressions(fr):
    current = _measures(fr, product_mean_loc=400.0, product_files_above_1000=20)
    baseline = _measures(fr, product_mean_loc=400.0, product_files_above_1000=20)
    assert fr.check_ratchet(current, baseline) == []


def test_a_higher_mean_is_a_regression(fr):
    baseline = {"measures": dict.fromkeys(fr.RATCHET_KEYS, 0.0)}
    current = {"measures": dict(baseline["measures"])}
    baseline["measures"]["product_mean_loc"] = 400.0
    current["measures"]["product_mean_loc"] = 420.0
    problems = fr.check_ratchet(current, baseline)
    assert problems == ["product_mean_loc: 400.0 -> 420.0 (worse)"]


def test_a_lower_mean_is_not_a_regression(fr):
    baseline = {"measures": dict.fromkeys(fr.RATCHET_KEYS, 0.0)}
    current = {"measures": dict(baseline["measures"])}
    baseline["measures"]["product_mean_loc"] = 400.0
    current["measures"]["product_mean_loc"] = 390.0
    assert fr.check_ratchet(current, baseline) == []


def test_one_more_file_above_1000_is_a_regression(fr):
    baseline = {"measures": dict.fromkeys(fr.RATCHET_KEYS, 0.0)}
    current = {"measures": dict(baseline["measures"])}
    baseline["measures"]["product_files_above_1000"] = 27
    current["measures"]["product_files_above_1000"] = 28
    assert fr.check_ratchet(current, baseline) == [
        "product_files_above_1000: 27 -> 28 (worse)"
    ]


def test_integer_counts_have_no_slack(fr):
    """Files-above-N counts are exact integers; any increase is real, unlike
    the float measures which get a tiny float-noise tolerance."""
    baseline = {"measures": dict.fromkeys(fr.RATCHET_KEYS, 0)}
    current = {"measures": dict(baseline["measures"])}
    baseline["measures"]["ir_files_above_1000"] = 5
    current["measures"]["ir_files_above_1000"] = 6
    assert fr.check_ratchet(current, baseline) != []


def test_a_tiny_float_wobble_is_not_a_regression(fr):
    baseline = {"measures": dict.fromkeys(fr.RATCHET_KEYS, 0.0)}
    current = {"measures": dict(baseline["measures"])}
    baseline["measures"]["product_median_loc"] = 250.0
    current["measures"]["product_median_loc"] = 250.0 + 1e-9
    assert fr.check_ratchet(current, baseline) == []


# --- the real ratchet ---------------------------------------------------------


def test_baseline_file_is_committed_and_well_formed(fr):
    baseline = fr.load_baseline(BASELINE)
    for key in fr.RATCHET_KEYS:
        assert isinstance(baseline["measures"][key], (int, float))


def test_the_real_src_tree_has_not_regressed_against_the_committed_baseline(fr):
    """The ratchet. This must NOT require the targets to be met -- only that
    no measure got worse than the committed baseline.

    Regenerate the baseline deliberately with
    `tools/fitness_report.py --write-baseline` (and review the diff) when a
    change is an intentional, accepted movement -- never to silence this
    test without looking at why a measure moved.
    """
    baseline = fr.load_baseline(BASELINE)
    current = fr.build_report(SRC)
    problems = fr.check_ratchet(current, baseline)
    assert problems == [], (
        "file-size fitness regressed against tools/fitness_baseline.json:\n"
        + "\n".join(problems)
    )


def test_the_committed_baseline_reproduces_todays_measured_values(fr):
    """Pin the exact current numbers so a silent drift in the measurement
    methodology itself (not the source tree) is caught too. Update this
    alongside the baseline file when it is deliberately regenerated.

    2026-09-01 (second, same day): `product_mean_loc` 407.982 -> 408.342 and
    `product_pct_loc_above_1000` 18.033 -> 18.017, from the PE symbol-summary
    fixes -- `symbol_table_entries` in `src/lib.rs`, `codeview_payload_ranges`
    in `src/symbols/pe.rs`, and a `pdb_path` getter. About 147 product lines
    across three existing files, which is why the mean moved and no
    file-count bucket did: nothing crossed a threshold, and the percentage of
    LOC in large files actually improved because the additions landed in files
    under 1,000 lines. Much of the addition is comment explaining three real
    defects (a hardcoded `false`, a missing getter, and an RSDS scan reading
    199,416 bytes short of the record); trimming that prose to hold a mean
    would be the wrong trade.

    2026-09-01: `product_mean_loc` 407.863 -> 407.982, from the CTPH parameter
    validation that turned three PanicExceptions into ValueErrors. The first
    measurement of this change was larger and WRONG: `src/target/conformance.rs`
    is 602 lines of pure `#[cfg(test)]`, but `is_test_path` classifies test-only
    files by NAME, and `conformance` matches none of the `test`/`tests`/`_test`/
    `_tests` forms the codebase already uses (`session_tests.rs`, `ast_tests/`).
    Renaming it to `conformance_tests.rs` moved 602 lines out of the product
    count where they never belonged -- the measure was right and the filename
    was wrong. What remains is the real product addition.

    2026-08-31: `product_loc_above_1000` 33,255 -> 33,327 (+72), from three new
    IR modules and the doc comments explaining them, landing partly inside two
    files that were already over 1,000 lines (`ir/name_resolve.rs`,
    `ir/ast/dec_render.rs`). Two helpers were moved into the modules that own
    them first, which took the growth down from +88; the rest is prose
    explaining a soundness trap and an object-parse ceiling, and is worth its
    lines. Every other measure improved or held -- `product_mean_loc` 408.64 ->
    407.86, `product_median_loc` 305 -> 303, `ir_median_loc` 405 -> 404 --
    because the new modules are small. Recorded through `--write-baseline`, so
    it also appears in the baseline's own `accepted_regressions` history rather
    than only here.

    2026-08-16: the dec-renderer extraction moved these deliberately. It took
    `src/ir/ast.rs` from 11,582 product LOC to 9,461 by lifting a 2,170-line,
    one-owner renderer into `src/ir/ast/dec_render.rs` -- and made FOUR of the
    seven then-existing measures worse, because a split necessarily adds a file
    to both "files above N" buckets. That is the measurement failing to see the
    work, not the work going the wrong way, which is why `product_max_loc`
    joined the set in the same change: it is the only measure that moves in the
    direction the decomposition program moves.

    2026-08-16 (same day, next cut): the ctx-renderer extraction lifted the
    generic `render`/`render_with_types` engine (`write_expr_ctx`,
    `write_stmt_ctx`, and seven more items the call graph pulled in that
    weren't on the original candidate list) into `src/ir/ast/ctx_render.rs`,
    746 lines. `product_max_loc` moved again, 9,461 -> 8,762, and every other
    measure held or improved except `ir_median_loc` (491 -> 492), which ticked
    up by one line for the same file-count-bucket reason the four regressions
    above did: shrinking the largest file changes which file sits at the
    median position. Recorded as accepted, with drift, rather than chased.

    2026-08-17 (third cut): the untyped C renderer (`render_c`, `write_reg_c`,
    `write_expr_c`, `write_stmt_c`, `write_for_clause_c`) moved into
    `src/ir/ast/c_render.rs`, 562 lines. `binop_sym_c` and `cmpop_sym_c` sit at
    the same physical spot the candidate range named as its end, but the call
    graph says otherwise: `dec_render.rs` calls both directly, so they stayed
    in the parent as newly-recognised shared vocabulary rather than moving --
    keeping newly-widened visibility at zero. `product_max_loc` moved again,
    8,762 -> 8,247, and every other measure held except `ir_median_loc`
    (492 -> 493), the same one-line file-count-bucket tick the ctx cut hit.
    Recorded as accepted, with drift, rather than chased.

    2026-08-17 (first lifter cut): the x86 packed/SSE family moved out of
    `src/ir/lift_x86.rs` into `src/ir/lift_x86/packed.rs`, 846 lines, taking
    that file 4,998 -> 4,183 product LOC. NOT ONE OF THE EIGHT MEASURES CAN SEE
    IT AS AN IMPROVEMENT, and one of them calls it a regression. `product_max_loc`
    -- the measure added precisely so decomposition would be visible -- did not
    move, because `ir/ast.rs` at 7,920 is still the largest file and this cut was
    to the THIRD largest. Meanwhile `product_median_loc` went 276 -> 279: adding
    any file above the median shifts the median up, so every cut this program
    makes worsens it by construction. `product_max_loc` only sees the single
    worst owner; the program works the list top-down and the list is long. That
    is a gap in the measurement, recorded as accepted with drift rather than
    chased. Part of the move was pre-existing: the tree measured 277.5 before
    this cut, inside the 2-LOC median tolerance and so never recorded.
    `product_max_loc` (8,247 -> 7,920), `product_mean_loc` and
    `product_pct_loc_above_1000` also fold in improvements committed between the
    c_render cut and this one.

    2026-08-17 (third cfg cut): the authoritative PE metadata tables --
    `parse_pdata_function_starts`, `parse_pe_export_function_starts` and the
    three unwind-record predicates the `.pdata` walk chains through -- moved
    into `src/analysis/cfg/pe_tables.rs`, 426 product LOC. `analysis/cfg.rs`
    went 4,066 -> 3,684 and is still the largest product file, so this is the
    rarer case where `product_max_loc` DOES see the cut: 4,066 -> 3,684, and
    `product_loc_above_1000` fell by exactly the 382 lines that left the file
    (61,896 -> 61,514). The cluster is two disjoint line ranges, not one:
    `pe_va_to_file_off` sits physically between them and has 11 call sites, 7
    of them in the sibling `cfg/scan.rs`, so a contiguous cut would have taken
    it along and broken the sibling. `product_median_loc` ticked 305 -> 307,
    the same file-count-bucket effect every cut in this program produces; it is
    exempt from the ratchet and recorded here rather than chased.

    2026-08-19: regenerated after `ir/ast/dec_render.rs` was RE-REVIEWED at
    2,013 LOC. It crossed 2,000 during a day of decompiler-correctness work
    (1,797 -> 1,839 -> 1,946 -> 2,013 across four commits), taking
    `product_files_above_2000` 3 -> 4. The baseline was NOT refreshed to silence
    the per-owner trend line -- the re-review came first, redid the call-graph
    and co-change measurement at the new size, and renewed the "no further
    split" verdict on fresh evidence: the strongly-connected component grew in
    step (11 fns/903 lines -> 12/1,029, 53.7% -> 54.1% of item lines), and no
    candidate cut improved. Only then was the size blessed. That ORDER is the
    whole discipline; reversing it is how a ratchet becomes a record of the last
    time someone ran the generator.

    Regenerated a second time the same day, after `src/ir/callee_return_bank.rs`
    (646 lines) landed for the callee side of multi-bank aggregate returns. A NEW
    FILE ABOVE THE MEAN RAISES THE MEAN -- 433.4398 -> 433.6397 -- and
    `product_median_loc` ticked 313 -> 313.5 for the same reason every cut in the
    decomposition programme worsened it: adding any file above the median shifts
    the median. Neither is the tree getting worse; both are the measure seeing a
    file count rather than a size. Recorded as accepted with drift, exactly as
    the 2026-08-16 and 2026-08-17 entries above recorded the mirror-image case.

    2026-08-20: static UPX unpacking added a documented four-field outcome to
    `FunctionDiscoveryStats` and its entry point to `analysis/cfg.rs`, taking the
    largest owner 2,482 -> 2,575. The entry point came straight back out into
    `analysis/cfg/packed.rs` (76 lines, and a self-contained question: *which
    image do we analyse*), which recovered 69 of them. The residual +24 is the
    stats fields and their doc comments, which belong on the struct they
    describe; cutting them would be deleting documentation to satisfy a number.
    `product_mean_loc` and both medians IMPROVED in the same change, because the
    split added a small file. Accepted as a deliberate ratchet.

    2026-08-27: the ARM word-table dispatch recogniser, and the structured
    variable inventory (`ir::recovered_variables` -- the half of DecBench's
    requested JSON schema that does not need instruction origin). Raw growth took
    `analysis/cfg.rs` to 2,531 and put `analysis/dispatch.rs` past 1,000 for the
    first time. TWO CUTS FIRST, in the order this docstring insists on.
    `analysis/cfg/dispatch_resolution.rs` (111 lines -- "which targets does this
    dispatch reach", three encodings deep now, and not something the largest file
    in the tree also needs to host) recovered 80, taking the largest owner
    2,531 -> 2,451, BELOW the previous baseline of 2,468.
    `analysis/dispatch/arm_tables.rs` (61 lines -- `ArmPcMode` and
    `ArmWordTableBranch`, an ARM concern no x86 rule references) recovered 51.
    `product_max_loc`, `product_mean_loc` and both medians all IMPROVED as a
    result.

    The residual is `analysis/dispatch.rs` at 1,128, accepted rather than cut
    again: what is left are `arm_adr_target` and `arm_word_table_branch`, which
    read `self.regs`, `self.bounded` and `self.arm_pc_mode`. Moving them out
    would expose the tracker's internals to a sibling module -- worse design
    adopted to satisfy a number, which is the failure mode the 2026-08-20 entry
    above names. `product_files_above_1000` 26 -> 27 and the two totals that
    follow from it are that one file and nothing else.

    2026-08-29 (fourth): the moving-base rule in `ir/variable_addresses.rs`,
    +88 lines. `product_mean_loc` 427.518 -> 427.726; `loc_above_1000` and
    `files_above_1000` unchanged, because the file is well under the threshold.
    This is a CORRECTNESS fix, not growth for its own sake: real binaries
    exposed 34 addresses attributed to the wrong storage -- a `push` is
    `rsp = rsp - 8` plus `store [rsp + 0]` at one `va`, so it matched a
    `(sp, 0)` slot exactly while naming different bytes. The rule and the four
    tests that pin it are what stop that.

    2026-08-29 (third): +14 lines, all of them the module docstring recording
    what the objdump sweep measured -- where the join is silent, and the two
    chunked-function addresses that fall outside a contiguous extent.
    `product_mean_loc` 427.485 -> 427.518; `pct_loc_above_1000` IMPROVED.
    Documentation deleted to keep a number flat is the drift this measure
    exists to surface, per the 2026-08-19 entry below, so it stays.

    2026-08-29 (second): `ir/variable_addresses.rs`, per-variable machine
    addresses. THREE OF FOUR MEASURES IMPROVED, which is what a new file under
    the threshold is supposed to do: `product_mean_loc` 428.00 -> 427.48,
    `product_pct_loc_above_1000` 22.105 -> 22.083, `product_median_loc`
    310 -> 309. The new module is 156 product lines and does one thing.

    The one measure that got worse is `product_loc_above_1000`, +6, because the
    two call sites live in `python_bindings/ir.rs` (already oversized). The cut
    came first and was worth making on its own terms: the join was initially
    inlined at BOTH sites, +24, and collapsing it into
    `recovered_variables_from_llir` took it to +6. That is a better API as well
    as a smaller number -- "join the coordinates, then build the inventory" is
    an ordering every caller would otherwise have to know and could get wrong.
    The residual +6 is the parameter itself.

    2026-08-29: the analyst-prototype overlay. +39 product lines, and the
    measure earned its keep by REJECTING my first cut. The prototype ->
    `CallPrototype` construction started inline in `python_bindings/ir.rs`
    (already 1,626 lines); moving it to `CallPrototype::from_analyst` in
    `ir/call_contracts.rs` made every number WORSE, because that file is itself
    ~1,039 product lines and the move landed 20 lines on the far side of the
    same threshold. Both candidate homes are oversized -- which is a fact about
    `call_contracts.rs`, not about these 39 lines.

    The constructor stayed on the type anyway. A constructor for `CallPrototype`
    belongs with `CallPrototype`; the binding's job is to fetch three strings,
    not to know what authority a human carries. Reverting it to satisfy the
    counter would be the mistake the 2026-08-20 entry above names. What was cut
    instead was the rationale comment duplicated at the call site, now that the
    constructor carries it.

    Residual accepted: the `analyst_prototype` parameter threaded through
    `decompile_at_py` / `decompile_at_session`, the constructor and its
    reasoning, and the loader. `product_files_above_1000` and `product_max_loc`
    are unchanged at 26 and 2,451 -- no file crossed the threshold and the
    largest owner did not grow.

    2026-08-28: THAT REASONING WAS WRONG, and the cut was made. `arm_tables` is
    a CHILD of `dispatch`, not a sibling, and a child module may already read
    its ancestors' private items -- so moving the three ARM recognisers there
    exposes nothing new. The only visibility that widened is
    `arm_adr_target`, from private-to-module to `pub(super)`, which is the same
    module either way; the crate-facing surface is unchanged. Rust permits an
    inherent `impl` in any module of the defining crate, so `DispatchTracker`
    stays one type.

    `analysis/dispatch.rs` is 1,128 -> 997 product lines, back under the
    threshold, and `test_large_module_review` is green again on it.
    `product_files_above_1000` 27 -> 26, `product_loc_above_1000` 40,933 ->
    39,886, `product_pct_loc_above_1000` 22.71 -> 22.09. The single measure that
    got worse is `product_mean_loc`, 427.05 -> 427.91, from +363 product lines
    of analyst-annotation plumbing in `ir/stack_locals.rs`,
    `ir/name_resolve.rs`, `ir/symbol_env.rs` and `python_bindings/ir.rs`.
    Accepted: the mean rose while the concentration fell, which is the
    direction this program wants.
    """
    with BASELINE.open(encoding="utf-8") as handle:
        baseline = json.load(handle)
    assert baseline["measures"] == {
        "ir_files_above_1000": 13,
        "ir_median_loc": pytest.approx(404.0),
        "product_files_above_1000": 23,
        "product_files_above_2000": 3,
        "product_loc_above_1000": 33327,
        "product_max_loc": 2268,
        "product_mean_loc": pytest.approx(408.3421633554084),
        "product_median_loc": pytest.approx(303),
        "product_pct_loc_above_1000": pytest.approx(18.016639726671677),
    }


# --- CLI smoke test -----------------------------------------------------------


def test_cli_check_ratchet_exits_zero_on_the_real_tree():
    import subprocess

    result = subprocess.run(
        ["python3", str(TOOL), "--check-ratchet"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, result.stdout + result.stderr
    assert "no regressions" in result.stdout


# --- median tolerance --------------------------------------------------------
#
# Medians are order statistics over a population whose SIZE changes when a file
# is added, so they move for reasons unrelated to the tree getting worse. Three
# legitimate improvements tripped a median ceiling on 2026-08-17, every one of
# them a change that made the largest owner SMALLER. See the comment on
# `_MEDIAN_KEYS` in the tool.


def test_medians_are_reported_but_never_ratcheted(fr):
    """A median is an order statistic over a population whose SIZE changes when a
    file is added, so it moves by an amount set by the local gap in the size
    distribution -- which is unbounded. A 2-LOC tolerance was tried and defeated
    within a day: calibrated where neighbours were 1 LOC apart, then hit a 17-LOC
    gap (`value_split.rs` 493, `regview.rs` 510) that moved `ir_median_loc` to
    501.5 with no file changing size near the median.

    They stay in TARGETS, reported against the end-state goal. They are not
    ceilings a change can violate."""
    baseline = {"measures": dict.fromkeys(fr.RATCHET_KEYS, 0.0)}
    current = {"measures": dict(baseline["measures"])}
    baseline["measures"]["product_median_loc"] = 276.0
    current["measures"]["product_median_loc"] = 999.0
    baseline["measures"]["ir_median_loc"] = 492.0
    current["measures"]["ir_median_loc"] = 501.5
    assert fr.check_ratchet(current, baseline) == []
    # ...but they are still MEASURED and still carry an end-state target.
    assert "product_median_loc" in fr.RATCHET_KEYS
    assert {"product_median_loc", "ir_median_loc"} <= {k for k, _l, _t in fr.TARGETS}


def test_the_measures_that_track_the_program_keep_zero_tolerance(fr):
    """`product_max_loc` is what the decomposition is FOR, and the "files above
    N" counts are exact. None of them may borrow the median's slack."""
    for key, before, after in (
        ("product_max_loc", 8247, 8248),
        ("product_files_above_1000", 30, 31),
        ("product_files_above_2000", 15, 16),
        ("ir_files_above_1000", 16, 17),
    ):
        baseline = {"measures": dict.fromkeys(fr.RATCHET_KEYS, 0)}
        current = {"measures": dict(baseline["measures"])}
        baseline["measures"][key] = before
        current["measures"][key] = after
        assert fr.check_ratchet(current, baseline) == [
            f"{key}: {before} -> {after} (worse)"
        ], key


def test_the_absolute_above_1000_measure_sees_a_cut_to_a_non_largest_file(fr):
    """Why `product_loc_above_1000` exists. `product_max_loc` watches only the
    single worst owner, so a cut to the THIRD-largest file leaves it unchanged
    and no measure records the work. Modelled on the real 2026-08-17 `lift_x86`
    packed-family cut: 815 LOC out of a 4,998-LOC file into an 846-LOC one."""
    baseline = {"measures": dict.fromkeys(fr.RATCHET_KEYS, 0)}
    current = {"measures": dict(baseline["measures"])}
    baseline["measures"]["product_max_loc"] = 7920
    current["measures"]["product_max_loc"] = 7920  # blind: not the largest file
    baseline["measures"]["product_loc_above_1000"] = 74204
    current["measures"]["product_loc_above_1000"] = 73389
    assert fr.check_ratchet(current, baseline) == []
    # And it is a real ceiling, not decoration: moving LOC the other way fails.
    current["measures"]["product_loc_above_1000"] = 74205
    assert fr.check_ratchet(current, baseline) == [
        "product_loc_above_1000: 74204 -> 74205 (worse)"
    ]


# --- cfg(all(test, ...)) ------------------------------------------------------
#
# Matching only the bare `#[cfg(test)]` spelling counted 1,053 lines of test code
# as PRODUCT code tree-wide -- 877 of them in one module in `src/analysis/cfg.rs`,
# which the bug inflated by 19%. Found 2026-08-17 while splitting that file.


def test_a_target_guarded_test_module_is_stripped(fr):
    """`src/analysis/cfg.rs`'s `#[cfg(all(test, target_arch = "x86_64"))] mod
    gcc_dispatch_corpus_tests` -- 877 lines, the single largest instance."""
    text = (
        "fn product() {}\n"
        '#[cfg(all(test, target_arch = "x86_64"))]\n'
        "mod gcc_dispatch_corpus_tests {\n"
        "    fn a_case() {}\n"
        "}\n"
        "fn more_product() {}\n"
    )
    stripped = fr.strip_test_items(text)
    assert "gcc_dispatch_corpus_tests" not in stripped
    assert "product()" in stripped and "more_product()" in stripped


def test_a_feature_guarded_test_module_is_stripped(fr):
    """`src/symbolic/solver/mod.rs` has two, 176 lines between them."""
    text = (
        "fn product() {}\n"
        '#[cfg(all(test, feature = "solver-z3"))]\n'
        "mod z3_tests {\n    fn t() {}\n}\n"
    )
    assert "z3_tests" not in fr.strip_test_items(text)


def test_cfg_not_test_is_product_code_and_is_kept(fr):
    """The most product-like code there is: it exists only in the SHIPPED build.
    A stripper that treated `not(test)` as test-only would delete it."""
    text = "#[cfg(not(test))]\nfn only_in_release() {\n    real_work();\n}\n"
    assert "only_in_release" in fr.strip_test_items(text)


def test_cfg_any_test_is_not_test_only_and_is_kept(fr):
    """`any(test, ...)` also holds when the other alternative does, so the item
    is present in non-test builds too."""
    text = '#[cfg(any(test, feature = "fuzzing"))]\nfn helper() {\n    x();\n}\n'
    assert "helper" in fr.strip_test_items(text)


def test_a_feature_literally_named_test_is_not_a_test_predicate(fr):
    text = '#[cfg(feature = "test")]\nfn shipped() {\n    x();\n}\n'
    assert "shipped" in fr.strip_test_items(text)


# --- per-owner trend ----------------------------------------------------------
#
# Every ratcheted measure is an aggregate over the whole tree, so a single file
# growing is only visible if no other file shrank by as much in the same
# baseline window. `check_owner_trend` is the per-file view. Added 2026-08-18
# after `src/ir/ast/dec_render.rs` went 1,727 -> 1,788 with the ratchet
# reporting "no regressions" throughout, and was noticed only by hand-auditing
# a stale table in the roadmap.


def test_one_owner_growing_is_reported(fr):
    baseline = {"oversized_files": {"ir/ast/dec_render.rs": 1727}}
    current = {"oversized_files": {"ir/ast/dec_render.rs": 1788}}
    assert fr.check_owner_trend(current, baseline) == [
        "ir/ast/dec_render.rs: 1727 -> 1788 (+61)"
    ]


def test_an_owner_that_shrank_is_not_reported(fr):
    baseline = {"oversized_files": {"ir/ast.rs": 2195}}
    current = {"oversized_files": {"ir/ast.rs": 1661}}
    assert fr.check_owner_trend(current, baseline) == []


def test_the_aggregate_ratchet_cannot_see_what_the_per_owner_view_sees(fr):
    """The reason this measure exists, as one assertion.

    `product_loc_above_1000` is a SUM over oversized files. One owner growing by
    61 while another is cut by 500 leaves the sum 439 lines BETTER, so the
    ratchet passes -- correctly, by its own definition. Modelled on the real
    2026-08-18 numbers: the committed baseline's sum was 55,210 against a
    measured 39,232, which is 15,978 lines of slack for any single file to grow
    into unseen.
    """
    measures_before = dict.fromkeys(fr.RATCHET_KEYS, 0)
    measures_before["product_loc_above_1000"] = 55210
    measures_after = dict(measures_before)
    measures_after["product_loc_above_1000"] = 55210 - 500 + 61
    baseline = {
        "measures": measures_before,
        "oversized_files": {"ir/ast/dec_render.rs": 1727, "analysis/cfg.rs": 3120},
    }
    current = {
        "measures": measures_after,
        "oversized_files": {"ir/ast/dec_render.rs": 1788, "analysis/cfg.rs": 2620},
    }
    assert fr.check_ratchet(current, baseline) == []  # blind, and not wrong
    assert fr.check_owner_trend(current, baseline) == [
        "ir/ast/dec_render.rs: 1727 -> 1788 (+61)"
    ]


def test_a_brand_new_owner_is_left_to_the_review_gate(fr):
    """A file that crossed 1,000 for the first time has no baseline size to have
    grown from. `test_large_module_review.py` already refuses it until a review
    is written, so reporting it here would be a second voice on one decision."""
    baseline = {"oversized_files": {"ir/ast.rs": 1661}}
    current = {"oversized_files": {"ir/ast.rs": 1661, "ir/brand_new.rs": 1200}}
    assert fr.check_owner_trend(current, baseline) == []


def test_growth_is_reported_largest_first(fr):
    baseline = {"oversized_files": {"a.rs": 1000, "b.rs": 2000, "c.rs": 3000}}
    current = {"oversized_files": {"a.rs": 1010, "b.rs": 2100, "c.rs": 3001}}
    assert fr.check_owner_trend(current, baseline) == [
        "b.rs: 2000 -> 2100 (+100)",
        "a.rs: 1000 -> 1010 (+10)",
        "c.rs: 3000 -> 3001 (+1)",
    ]


def test_the_trend_works_against_a_baseline_written_before_the_measure_existed(fr):
    """`oversized_files` is new; every committed baseline predating it carries
    only the top-15 `largest_files` list. The check falls back to that list
    rather than requiring a baseline regeneration first -- a measure whose first
    act is to rewrite its own reference point can only ever record the state it
    was born into."""
    baseline = {"largest_files": [{"path": "ir/ast/dec_render.rs", "loc": 1727}]}
    current = {"oversized_files": {"ir/ast/dec_render.rs": 1788}}
    assert fr.check_owner_trend(current, baseline) == [
        "ir/ast/dec_render.rs: 1727 -> 1788 (+61)"
    ]


def test_the_real_tree_records_every_oversized_file_not_just_the_top_15(fr):
    report = fr.build_report(SRC)
    oversized = report["oversized_files"]
    assert len(oversized) == report["measures"]["product_files_above_1000"]
    assert len(oversized) > len(report["largest_files"])
    assert all(loc > fr.OVERSIZED_LOC for loc in oversized.values())


def test_the_committed_baseline_shows_the_growth_this_measure_was_added_for(fr):
    """Not a synthetic case: the tree as committed. If one of these files is
    later split, or its growth is deliberately accepted into a regenerated
    baseline, this assertion is the thing that must be updated, which is the
    point.

    2026-08-19: the list is EMPTY, and that is the update the docstring above
    predicted. `ir/ast/dec_render.rs` (1,727 -> 2,013) and `ir/value_number.rs`
    (1,965 -> 1,991) both grew, both were surfaced by this measure while
    `check_ratchet` reported nothing, and the larger one was then RE-REVIEWED at
    its new size before the baseline was regenerated. An empty list here means
    "every oversized file is at a size someone has looked at", not "nothing
    grew" -- and the six synthetic cases above are what prove the measure still
    fires, so this one going empty costs no coverage.

    `ir/value_number.rs` joined the list when `live_in_arg_slots_llir` stopped
    treating a versioned read as live-in evidence. The growth is the rule's
    justification -- the worked `37_heapsort` case that makes a one-token
    predicate legible -- and it is listed here rather than trimmed to fit the
    counter, because a comment deleted to keep a number flat is exactly the
    drift this measure exists to surface.

    2026-08-31: regenerated after four splits, and EVERY measure improved --
    `files_above_1000` 26 -> 23, `files_above_2000` 4 -> 3,
    `loc_in_files_above_1000` 39,931 -> 33,255 (-6,676), `max_loc` 2,451 ->
    2,268, `mean_loc` 427.7 -> 408.6, `pct_loc_above_1000` 22.07 -> 18.08. The
    cut came first, as the docstring below requires. A day of optimisation work
    had grown four files past the sizes their reviews examined -- `analysis/cfg.rs`
    2,451 -> 2,535, `ir/value_number.rs` 1,991 -> 2,071, `ir/copy_prop.rs`
    1,631 -> 1,856, `ir/structure.rs` 1,668 -> 1,843 -- and this measure plus
    `test_large_module_review` were the only things that said so, while
    `cargo test`, `dectest` and a byte-identity sweep over the whole fixture
    corpus all stayed green. All four were split rather than blessed: 2,535 ->
    293, 2,071 -> 430, 1,856 -> 412, 1,843 -> 486, into 24 modules cut on
    ownership, each proving byte-identical output over the fixture corpus
    first. Three files remain listed here at small growth from the same work
    (`ir/ast.rs` +2, `ir/const_fold.rs` +32, `python_bindings/ir.rs` +28); they
    are recorded rather than trimmed, for the reason the 2026-08-19 note gives.

    2026-08-28: the baseline was regenerated after the analyst-annotation work.
    Only ONE measure got worse -- `product_mean_loc` 427.05 -> 427.91 -- and
    every concentration measure improved: `files_above_1000` 27 -> 26,
    `loc_in_files_above_1000` 40,933 -> 39,886 (-1,047),
    `pct_loc_above_1000` 22.71 -> 22.09. The cut came first, as the docstring
    below requires: `analysis/dispatch.rs` had grown back past 1,000 product
    lines while adding the ARM word-table recogniser, and its three ARM
    recognisers (`arm_adr_target`, `arm_word_table_branch`,
    `thumb_table_branch`, 131 lines) moved into the `dispatch::arm_tables`
    submodule that already held the ARM *types* they read -- none of them is
    referenced by the x86 rules, so that is a narrower API and not arbitrary
    fragmentation. `test_large_module_review` had gone red on that file and is
    green again.

    The residual `mean_loc` rise is +363 product lines across
    `ir/stack_locals.rs`, `ir/name_resolve.rs`, `ir/symbol_env.rs` and
    `python_bindings/ir.rs`: the analyst-name overlay, the analyst-locals join,
    `SymbolEnv::rename_display`, and the parameters that carry them. It is
    accepted rather than trimmed because the mean rose while the concentration
    fell, which is the direction this program wants -- new behaviour landing in
    the files that own it instead of accreting in the largest ones.

    2026-08-21: `ir/types_recover.rs` grew 1,898 -> 1,906 (+8) and the baseline
    was regenerated. The measure did its job twice on the way. It first fired at
    +110, which was the whole `copied_live_in_pointer_hint` walk sitting in the
    driver; that became `types_recover/copies.rs`, beside the two spill-shaped
    producers it is the `-O2` counterpart to. It fired again at +17, which was a
    twelve-line comment explaining why the new evidence is MERGED into the hint
    chain rather than chained onto it -- so that moved to
    `copies::combine_pointer_evidence`, the function whose contract it states,
    and the call site kept a pointer to it. The residual +8 is the call site
    itself plus `mod copies;` and its `use`: irreducible without deleting the
    reasoning, which is the thing this measure protects.
    """
    baseline = fr.load_baseline(BASELINE)
    current = fr.build_report(SRC)
    assert fr.check_ratchet(current, baseline) == []
    grown = fr.check_owner_trend(current, baseline)
    assert [row.split(":")[0] for row in grown] == []


def test_owner_growth_is_never_fatal(fr):
    """Deliberate: an oversized file grows when a defect inside it is fixed, and
    a gate that fails on that teaches people to stop fixing them. The claim is
    only that the growth is impossible to not see."""
    baseline = {
        "measures": dict.fromkeys(fr.RATCHET_KEYS, 0),
        "oversized_files": {"ir/ast/dec_render.rs": 1727},
    }
    current = {
        "measures": dict.fromkeys(fr.RATCHET_KEYS, 0),
        "oversized_files": {"ir/ast/dec_render.rs": 1788},
    }
    assert fr.check_owner_trend(current, baseline) != []
    assert fr.check_ratchet(current, baseline) == []
