"""`docs/reference/environment-variables.md` must match the tree it scans.

There used to be no single index of the environment variables this
repository reads. `docs/history/docs-rewrite-2026-09/audit/01-claude-agents-readme.md`
ledger #85 found `CLAUDE.md` naming one, `GLAURUNG_AGENT_ROUTE`, that appears
nowhere in code -- a reference that cannot be checked drifts exactly that
way. `tools/gen_env_reference.py` walks the tree itself instead of copying a
list, so this test -- same shape as `test_native_stub_current.py` -- fails
whenever the committed page stops matching what the generator finds.
"""

from __future__ import annotations

import importlib.util
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
GENERATOR = ROOT / "tools" / "gen_env_reference.py"
OUT_PATH = ROOT / "docs" / "reference" / "environment-variables.md"

SHA_LINE_RE = re.compile(
    r"^<!-- generated by [^ ]+ at [0-9a-f]+; do not edit -->$", re.MULTILINE
)


def _load_generator():
    spec = importlib.util.spec_from_file_location("_gen_env_reference", GENERATOR)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _normalize(text: str) -> str:
    return SHA_LINE_RE.sub("<!-- generated; do not edit -->", text)


def test_generator_and_output_are_present() -> None:
    assert GENERATOR.is_file(), f"missing {GENERATOR}"
    assert OUT_PATH.is_file(), f"missing {OUT_PATH}"


def test_generated_reference_matches_committed_file() -> None:
    gen = _load_generator()
    generated = gen.generate()
    committed = OUT_PATH.read_text()
    assert _normalize(generated) == _normalize(committed), (
        f"{OUT_PATH.relative_to(ROOT)} is stale against tools/gen_env_reference.py; "
        "regenerate with `uv run python tools/gen_env_reference.py`"
    )


def test_kind_and_status_banner_present() -> None:
    head = "\n".join(OUT_PATH.read_text().splitlines()[:5])
    assert "**Kind:** reference" in head
    assert "**Status:** generated" in head


def test_agent_route_does_not_appear() -> None:
    """`GLAURUNG_AGENT_ROUTE` is the specific false-positive this scan must
    not reintroduce: it appears nowhere in code, only historically in prose
    (ledger 01 #85). A scan of docs would find it via `--route`-adjacent
    text; a scan of code must not find it at all.
    """
    text = OUT_PATH.read_text()
    assert "GLAURUNG_AGENT_ROUTE" not in text


def test_every_purposes_entry_has_a_matching_read_site() -> None:
    """A `PURPOSES` entry for a variable that no longer appears in the scan
    is stale documentation for a dead name -- the generator surfaces this in
    its own output rather than silently keeping it, so assert that surfaced
    list stays empty rather than duplicating the scan here.
    """
    gen = _load_generator()
    findings = gen.collect()
    stale = sorted(set(gen.PURPOSES) - set(findings.sites))
    assert not stale, f"PURPOSES entries with no matching read site: {stale}"


def test_every_found_variable_is_documented() -> None:
    """The generator is allowed to report undocumented variables (that is
    the point -- the gap should be visible), but the committed reference
    should have no such gaps left open: every variable this run of the scan
    finds should have a `PURPOSES` entry.
    """
    gen = _load_generator()
    findings = gen.collect()
    undocumented = sorted(set(findings.sites) - set(gen.PURPOSES))
    assert not undocumented, (
        f"variables found with no PURPOSES entry: {undocumented}; "
        "add them to PURPOSES in tools/gen_env_reference.py"
    )


def test_check_mode_exits_zero_against_the_committed_file() -> None:
    gen = _load_generator()
    assert gen.main(["--check"]) == 0
