"""Every decompiler failure the fixture corpus can currently demonstrate.

**874 of them**, measured rather than asserted, each one a strict xfail that
turns red the day it is fixed.

Why this file
-------------

A suite that is green over a decompiler with known trade-offs is not measuring
the trade-offs. Before this, the estate could tell you that output *behaved*
correctly (the execution differential) and roughly how *readable* it was in
aggregate (the readability census), but it could not name a single function
whose recovered prototype disagreed with the source, and it could not name the
713 functions that emit `goto` for source containing none.

Two axes, both against ground truth rather than against yesterday's output:

**types** (82) — the recovered prototype versus the DWARF the compiler
emitted. DWARF states the source signature exactly, so a disagreement is a
recovery gap, not a stylistic choice. 72 are signedness, 10 are width.

**structure** (713, totalling 6,823 `goto` statements) — a `goto` in recovered
C for a function whose source file contains no `goto` anywhere. This is the
class `docs/development/decompiler-parity-backlog.md` measures at 28.8% of
scored DecBench functions, and the execution differential is blind to it by
construction: goto soup is faithful, compiles, and returns the right answer for
every input. It simply is not the control flow the programmer wrote.

How it behaves
--------------

Each entry asserts the CORRECT behaviour under
`@pytest.mark.xfail(strict=True)`. Today they xfail and the report names them.
When one is fixed it XPASSes, strict turns that red, and the message says to
regenerate the inventory — so an improvement announces itself instead of
sliding by. That is the opposite of pinning current output, which makes a fix
indistinguishable from a regression.

The inventory is `tests/open_defects/known_failures.json`, regenerated by
`tools/gen_known_failures.py` (44.6 seconds over 1,676 objects with eight bounded
workers on the recorded 2026-09-05 run). It is evidence, not configuration: do
not hand-edit it.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent.parent
BUILD = ROOT / "tests" / "decompiler_fixtures" / "build"
INVENTORY = ROOT / "tests" / "open_defects" / "known_failures.json"
sys.path.insert(0, str(ROOT / "tools"))

import diff_decompile as D  # ty: ignore[unresolved-import]  # added above

# The SAME parameter splitter and type classifier the inventory was built with.
# Re-implementing them here is how the first version produced 36 spurious
# XPASSes: a naive `split(",")` disagrees with the generator's depth-aware
# split on any signature containing nested parentheses, so the two disagreed
# about which parameter `arg2` even is.
import gen_known_failures as G  # ty: ignore[unresolved-import]  # added above

#: The measured inventory. Typed explicitly because `json.loads` returns
#: `Any | list | dict`, so every `.get` below is an unresolved-attribute error
#: against the list arm until the union is narrowed.
_DATA: dict[str, object] = (
    json.loads(INVENTORY.read_text())
    if INVENTORY.is_file()
    else {"types": [], "structure": [], "counts": {}}
)


def _rows(key: str) -> list[dict]:
    value = _DATA.get(key, [])
    return value if isinstance(value, list) else []


def _counts() -> dict:
    value = _DATA.get("counts", {})
    return value if isinstance(value, dict) else {}


def _summary(name: str) -> dict:
    value = _DATA.get(name, {})
    return value if isinstance(value, dict) else {}


#: One native batch per object, shared across every inventory axis.  The old
#: cache avoided duplicate rows only after starting one CLI process per
#: function; on Rust runtime-heavy objects that still made this test file take
#: hours.  Keep the batch keyed by VA because closure names are not unique.
_OBJECT_CACHE: dict[str, dict[int, str]] = {}


def _inventory_vas(obj: str) -> list[int]:
    """All authoritative entry addresses this test file needs from an object."""
    return list(
        dict.fromkeys(
            int(row["va"])
            for axis in G.AXES
            for row in _rows(axis)
            if row["obj"] == obj
        )
    )


def _render(obj: str, va: int) -> str | None:
    """Decompile an object's required VAs together, never by name.

    Rust emits many functions called `{closure#0}`; a name-keyed lookup takes
    whichever one `signatures()` yields first, which is how the first version
    of this file produced 41 spurious XPASSes on rust fixtures.
    """
    if obj not in _OBJECT_CACHE:
        path = BUILD / obj
        recovered = {}
        if path.is_file():
            try:
                recovered = D.decompiled_many_c(str(path), _inventory_vas(obj))
            except Exception:
                recovered = {}
        _OBJECT_CACHE[obj] = recovered
    return _OBJECT_CACHE[obj].get(int(va))


def _require_corpus(obj: str) -> None:
    if not BUILD.is_dir():
        pytest.skip(
            f"{BUILD.relative_to(ROOT)} is gitignored and absent; build the "
            "fixture matrix to run the known-failure corpus"
        )
    if not (BUILD / obj).is_file():
        pytest.skip(f"{obj} not built in this checkout")


def _signature_of(text: str) -> str | None:
    for line in text.splitlines():
        if line.startswith("//") or not line.strip():
            continue
        if "(" in line:
            return line.split("{")[0].strip()
    return None


def _type_params():
    for r in _rows("types"):
        want = f"width {r['want']} bytes" if r["kind"] == "width" else str(r["want"])
        yield pytest.param(
            r,
            id=f"{r['obj']}::{r['fn']}@{r['va']:#x}::arg{r['arg']}::{r['kind']}",
            marks=pytest.mark.xfail(
                strict=True,
                reason=(
                    f"OPEN DEFECT (prototype {r['kind']}): {r['fn']} arg{r['arg']} "
                    f"is {want} in the DWARF the compiler emitted, recovered as "
                    f"`{r['got']}`. Ground truth, not preference."
                ),
            ),
        )


def _structure_params():
    for r in _rows("structure"):
        yield pytest.param(
            r,
            id=f"{r['obj']}::{r['fn']}@{r['va']:#x}::goto",
            marks=pytest.mark.xfail(
                strict=True,
                reason=(
                    f"OPEN DEFECT (structuring): {r['fn']} emits {r['gotos']} "
                    "`goto` statement(s) for a source file containing none. The "
                    "execution differential passes it -- goto soup is faithful, "
                    "compiles and returns the right answer; it is simply not the "
                    "control flow that was written."
                ),
            ),
        )


def _return_params():
    for r in _rows("returns"):
        want = "a pointer" if r["kind"] == "ptr_lost" else f"{r['want']} bytes wide"
        yield pytest.param(
            r,
            id=f"{r['obj']}::{r['fn']}@{r['va']:#x}::return::{r['kind']}",
            marks=pytest.mark.xfail(
                strict=True,
                reason=(
                    f"OPEN DEFECT (return type): {r['fn']} returns {want} in "
                    f"DWARF, recovered as `{r['got']}`. A wrong return type is "
                    "what makes a function look `void` -- the shape both the "
                    "-flto collapse and the AArch64 FMA gap produce."
                ),
            ),
        )


def _unrecovered_params():
    for r in _rows("unrecovered"):
        yield pytest.param(
            r,
            id=f"{r['obj']}::{r['fn']}@{r['va']:#x}::unrecovered",
            marks=pytest.mark.xfail(
                strict=True,
                reason=(
                    f"OPEN DEFECT (unrecovered construct): {r['fn']} emits "
                    f"{r['n']} `unrecovered` marker(s) -- the renderer stating "
                    "outright that it could not model something. Unlike goto "
                    "soup this is not even faithful-but-ugly; it is a hole."
                ),
            ),
        )


@pytest.mark.parametrize("row", list(_return_params()))
def test_recovered_return_type_matches_dwarf(row):
    """The return type the compiler recorded must survive recovery."""
    _require_corpus(row["obj"])
    text = _render(row["obj"], row["va"])
    assert text, f"{row['obj']}::{row['fn']} produced no body"
    sig = _signature_of(text)
    assert sig, f"no signature line:\n{text[:200]}"
    head = sig.split("(")[0]
    got = G.classify(head.rsplit(" ", 1)[0])["raw"] if " " in head else head
    assert got != row["got"], f"{row['fn']} still returns `{row['got']}`"


@pytest.mark.parametrize("row", list(_unrecovered_params()))
def test_no_unrecovered_construct_remains(row):
    """`unrecovered` in the output is the renderer conceding a hole."""
    _require_corpus(row["obj"])
    text = _render(row["obj"], row["va"])
    assert text, f"{row['obj']}::{row['fn']} produced no body"
    hits = [ln.strip() for ln in text.splitlines() if "unrecovered" in ln]
    assert not hits, f"{len(hits)} unrecovered construct(s):\n  " + "\n  ".join(
        hits[:3]
    )


def test_the_inventory_is_present_and_populated():
    """A vacuity guard: every xfail below would vanish over an empty file."""
    assert INVENTORY.is_file(), (
        f"{INVENTORY.name} missing; regenerate with "
        "`uv run python tools/gen_known_failures.py`"
    )


def test_inventory_reports_language_split_counts():
    """Rust-heavy axes must not obscure the primary C defect totals."""
    by_language = _summary("counts_by_language")
    assert by_language.get("c") == {
        "types": 0,
        "structure": 619,
        "returns": 15,
        "pointers": 0,
        "unrecovered": 34,
        "no_body": 0,
        "goto_statements": 6257,
    }
    assert by_language.get("rust") == {
        "types": 82,
        "structure": 94,
        "returns": 26,
        "pointers": 0,
        "unrecovered": 4,
        "no_body": 0,
        "goto_statements": 566,
    }
    for axis, total in _counts().items():
        assert by_language["c"][axis] + by_language["rust"][axis] == total


def test_inventory_reports_provenance_deduplicated_counts():
    """Matching O2/debug-stripped defect observations count once."""
    deduplicated = _summary("deduplicated_counts")
    assert deduplicated == {
        "types": 65,
        "structure": 472,
        "returns": 33,
        "pointers": 0,
        "unrecovered": 25,
        "no_body": 0,
        "goto_statements": 4655,
    }
    deduplicated_by_language = _summary("deduplicated_counts_by_language")
    for axis, total in deduplicated.items():
        assert (
            deduplicated_by_language["c"][axis] + deduplicated_by_language["rust"][axis]
            == total
        )


def test_binary_identity_uses_real_content_not_filename_convention():
    """Most stripped pairs are identical, while seven Rust pairs are not."""
    if not BUILD.is_dir():
        pytest.skip("fixture matrix is absent")
    c_o2 = BUILD / "02_integer_widths-gcc-O2.so"
    c_stripped = BUILD / "02_integer_widths-gcc-O2strip.dwarf.so"
    rust_o2 = BUILD / "166_rust_generics-rustc-O2.so"
    rust_stripped = BUILD / "166_rust_generics-rustc-O2strip.dwarf.so"
    if not all(path.is_file() for path in (c_o2, c_stripped, rust_o2, rust_stripped)):
        pytest.skip("required real O2/stripped fixture pairs are absent")
    identities = G.binary_content_identities([c_o2, c_stripped, rust_o2, rust_stripped])
    assert identities[c_o2.name] == identities[c_stripped.name]
    assert identities[rust_o2.name] != identities[rust_stripped.name]


def test_generator_help_exits_without_starting_a_corpus_run(tmp_path):
    """`--help` must never silently launch the expensive generator."""
    output = tmp_path / "must-not-exist.json"
    proc = subprocess.run(
        [
            sys.executable,
            str(ROOT / "tools" / "gen_known_failures.py"),
            "--help",
            "--output",
            str(output),
        ],
        capture_output=True,
        text=True,
        cwd=ROOT,
        timeout=10,
        check=False,
    )
    assert proc.returncode == 0, proc.stderr
    assert "--language" in proc.stdout
    assert "--jobs" in proc.stdout
    assert not output.exists()


@pytest.mark.parametrize(
    ("declaration", "expected"),
    (
        ("char *arg0", "char *"),
        ("char * arg0", "char *"),
        ("unsigned int n", "unsigned int"),
    ),
)
def test_generator_strips_names_without_erasing_pointer_stars(declaration, expected):
    """Renderer whitespace must not manufacture pointer-loss defects."""
    assert G.strip_name(declaration) == expected


def test_generator_batches_real_fixtures_deterministically(tmp_path):
    """A filtered batch must agree across serial and parallel scheduling."""
    objects = (
        "02_integer_widths-clang-O2.so",
        "02_integer_widths-gcc-O2.so",
    )
    for obj in objects:
        _require_corpus(obj)

    outputs = []
    checkpoint = tmp_path / "objects.jsonl"
    for jobs in (1, 2):
        output = tmp_path / f"jobs-{jobs}.json"
        argv = ["--jobs", str(jobs), "--no-progress", "--output", str(output)]
        if jobs == 1:
            argv.extend(("--checkpoint", str(checkpoint)))
        for obj in objects:
            argv.extend(("--fixture", obj))
        assert G.main(argv) == 0
        payload = json.loads(output.read_text())
        assert payload["objects_scanned"] == 2
        assert all(row["obj"] in objects for axis in G.AXES for row in payload[axis])
        payload.pop("elapsed_seconds")
        outputs.append(payload)
    assert outputs[0] == outputs[1]

    resumed = tmp_path / "resumed.json"
    argv = [
        "--jobs",
        "2",
        "--no-progress",
        "--checkpoint",
        str(checkpoint),
        "--resume",
        "--output",
        str(resumed),
    ]
    for obj in objects:
        argv.extend(("--fixture", obj))
    assert G.main(argv) == 0
    payload = json.loads(resumed.read_text())
    payload.pop("elapsed_seconds")
    assert payload == outputs[0]
    assert len(checkpoint.read_text().splitlines()) == 2


def test_generated_inventory_summaries_are_current():
    """Committed summary metadata must match the measured row inventory."""
    rows = {axis: _rows(axis) for axis in G.AXES}
    by_language, deduplicated, deduplicated_by_language = G.inventory_summaries(rows)
    assert _summary("counts_by_language") == by_language
    assert _summary("deduplicated_counts") == deduplicated
    assert _summary("deduplicated_counts_by_language") == deduplicated_by_language
    counts = _counts()
    assert sum(v for k, v in counts.items() if k != "goto_statements") == 874, (
        f"the inventory records only {counts}; it should hold the 874 "
        "failures the corpus demonstrates. An empty inventory makes this whole "
        "file silently vacuous."
    )
    weak_fold = [
        row
        for row in rows["structure"]
        if row["obj"] == "158_weak_symbols-gcc-O2.so" and row["fn"] == "weak_fold"
    ]
    assert [row["gotos"] for row in weak_fold] == [2], (
        "shared return-tail ownership must not replace weak_fold's two direct "
        "loop-exit returns with extra gotos"
    )


@pytest.mark.parametrize("row", list(_type_params()))
def test_recovered_prototype_matches_dwarf(row):
    """The recovered parameter type must match what the compiler recorded."""
    _require_corpus(row["obj"])
    text = _render(row["obj"], row["va"])
    assert text, f"{row['obj']}::{row['fn']} produced no body"
    sig = _signature_of(text)
    assert sig, f"no signature line:\n{text[:200]}"
    decls = G.split_params(sig)
    assert decls is not None, sig
    assert row["arg"] < len(decls), f"arg{row['arg']} beyond {sig}"
    got = G.classify(G.strip_name(decls[row["arg"]]))["raw"]
    assert got != row["got"], (
        f"{row['fn']} arg{row['arg']} still recovers as `{row['got']}`"
    )


@pytest.mark.parametrize("row", list(_structure_params()))
def test_goto_free_source_recovers_without_goto(row):
    """Source with no `goto` must not recover with one."""
    _require_corpus(row["obj"])
    text = _render(row["obj"], row["va"])
    assert text, f"{row['obj']}::{row['fn']} produced no body"
    gotos = re.findall(r"\bgoto\s+\w+\s*;", text)
    assert not gotos, f"{len(gotos)} goto statement(s) in {row['fn']}"


def test_the_failure_count_does_not_grow():
    """The ratchet over the whole corpus.

    Individual xfails catch a fix; this catches a regression that adds NEW
    failures, which would otherwise appear as entries nobody recorded.
    """
    counts = _counts()
    assert counts.get("types", 0) <= 82, (
        f"prototype mismatches grew to {counts.get('types')} (recorded 82)"
    )
    assert counts.get("structure", 0) <= 715, (
        f"functions with unwanted goto grew to {counts.get('structure')} (recorded 715)"
    )
    assert counts.get("goto_statements", 0) <= 6825, (
        f"goto statements grew to {counts.get('goto_statements')} (recorded 6,825)"
    )
    assert counts.get("returns", 0) <= 41, (
        f"return-type mismatches grew to {counts.get('returns')} (recorded 41)"
    )
    assert counts.get("unrecovered", 0) <= 42, (
        f"unrecovered constructs grew to {counts.get('unrecovered')} (recorded 42)"
    )
    # These two are ZERO today, which is worth pinning as an achievement
    # rather than leaving as an absence: a DWARF pointer parameter never
    # degrades to a scalar, and every function DWARF names produces a body.
    assert counts.get("pointers", 0) == 0, (
        f"{counts.get('pointers')} pointer parameter(s) now recover as scalars; "
        "recovered C would dereference an integer"
    )
    assert counts.get("no_body", 0) == 0, (
        f"{counts.get('no_body')} function(s) DWARF names now produce no body"
    )
