#!/usr/bin/env python3
"""Merge the surveyed inventory fragments into the published index.

WHY THIS EXISTS. The test estate had grown past the point where anyone could
say what covered what, or -- the question that actually matters -- what nothing
runs. Five surveys walked disjoint territories against one schema; this merges
their JSONL, validates it, and writes the index plus the derived views under
`docs/test-inventory/`.

The merge is deliberately strict. Every entry must parse, every `path` must
exist, and every `domain` must come from the fixed vocabulary. An inventory that
quietly admits a stale path is worse than none, because it reads as authority.

    uv run python tools/build_test_inventory.py --fragments <dir> --out docs/test-inventory
"""

from __future__ import annotations

import argparse
import json
import subprocess
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

DOMAINS = {
    "triage",
    "formats",
    "disasm",
    "decompiler",
    "ir",
    "analysis",
    "strings",
    "symbols",
    "demangle",
    "flirt",
    "similarity",
    "entropy",
    "kb",
    "llm",
    "cli",
    "docker",
    "packers",
    "containers",
    "java",
    "windows",
    "symbolic",
    "decbench",
    "infra",
    "docs",
}


#: `gated_by` free text collapses to these buckets for the coverage view. The
#: distinction that matters is not "how is it run" but "does anything run it
#: without a human deciding to".
def reach(entry: dict) -> str:
    g = (entry.get("gated_by") or "").lower()
    if "nothing" in g or "dead" in g or "never" in g or "orphan" in g:
        return "unreachable"
    if "ci" in g or "workflow" in g:
        return "ci"
    if "default" in g:
        return "default-suite"
    if "slow" in g or "gate" in g or "decbench" in g or "opt-in" in g or "manual" in g:
        return "opt-in"
    return "other"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--fragments", type=Path, required=True)
    ap.add_argument("--out", type=Path, required=True)
    args = ap.parse_args()

    rows, problems = [], []
    for frag in sorted(args.fragments.glob("*.jsonl")):
        for n, line in enumerate(frag.read_text().splitlines(), 1):
            line = line.strip()
            if not line:
                continue
            try:
                entry = json.loads(line)
            except json.JSONDecodeError as e:
                problems.append(f"{frag.name}:{n}: {e}")
                continue
            entry["territory"] = frag.stem
            path = entry.get("path")
            if not path or not (ROOT / path).exists():
                problems.append(f"{frag.name}:{n}: path does not exist: {path!r}")
                continue
            unknown = set(entry.get("domain") or []) - DOMAINS
            if unknown:
                problems.append(f"{frag.name}:{n}: unknown domain(s) {sorted(unknown)}")
            entry["reach"] = reach(entry)
            rows.append(entry)

    if problems:
        print(f"REFUSING: {len(problems)} problem(s)")
        for p in problems[:20]:
            print("  ", p)
        return 1

    rows.sort(key=lambda r: (r["kind"], r["path"]))
    commit = subprocess.run(
        ["git", "rev-parse", "--short=8", "HEAD"],
        capture_output=True,
        text=True,
        cwd=ROOT,
    ).stdout.strip()

    by_kind = Counter(r["kind"] for r in rows)
    by_domain: Counter = Counter()
    for r in rows:
        by_domain.update(r.get("domain") or ["(none)"])
    by_reach = Counter(r["reach"] for r in rows)
    tests = sum(r.get("count") or 0 for r in rows if "test" in r["kind"])

    index = {
        "generated_from": "tools/build_test_inventory.py",
        "commit": commit,
        "counts": {
            "entries": len(rows),
            "test_functions": tests,
            "by_kind": dict(by_kind.most_common()),
            "by_domain": dict(by_domain.most_common()),
            "by_reach": dict(by_reach.most_common()),
        },
        "domains": sorted(DOMAINS),
        "entries": rows,
    }
    args.out.mkdir(parents=True, exist_ok=True)
    (args.out / "index.json").write_text(json.dumps(index, indent=1) + "\n")

    # A YAML view for reading. Emitted by PyYAML rather than hand-rolled: the
    # first version of this quoted scalars itself and produced a document that
    # would not parse, because several notes describe literal backslash-n
    # sequences found in malformed fixture JSON. An inventory that calls itself
    # machine-readable has to survive its own loader.
    import yaml

    (args.out / "index.yaml").write_text(
        f"# Generated by tools/build_test_inventory.py at {commit}. Do not edit.\n"
        + yaml.safe_dump(
            {"commit": commit, "counts": index["counts"], "entries": rows},
            sort_keys=False,
            allow_unicode=True,
            width=100,
        )
    )

    # Derived view: what nothing runs.
    unreachable = [r for r in rows if r["reach"] == "unreachable"]
    (args.out / "unreachable.json").write_text(
        json.dumps(
            {"commit": commit, "count": len(unreachable), "entries": unreachable},
            indent=1,
        )
        + "\n"
    )

    print(f"{len(rows)} entries -> {args.out}")
    print(f"  test functions catalogued: {tests:,}")
    print(f"  by reach: {dict(by_reach.most_common())}")
    print(f"  unreachable: {len(unreachable)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
