#!/usr/bin/env python3
"""Generate the environment-variable reference from a grep over the tree.

`docs/reference/environment-variables.md` used to not exist at all: the
~40 `GLAURUNG_*`/`DECBENCH_*`/`AXEYUM_*`/`IOCTLANCE_*`/`BITWUZLA_*` vars this
codebase reads were scattered across Python, Rust, shell scripts and CI YAML
with no single index, and (per `docs/history/docs-rewrite-2026-09/audit/`
ledger 01 #85) `CLAUDE.md` named one, `GLAURUNG_AGENT_ROUTE`, that appears
nowhere in code. This generator walks the tree itself -- no `rg` subprocess,
so it works offline and its result is exactly what the regexes below say it
is -- and reports every variable actually read, with the sites that read it.
An unrecognized name is not hidden; it is marked
"(undocumented -- add to PURPOSES in the generator)" so the gap stays
visible instead of silently passing.

What counts as a "read"
------------------------

* Python: `os.environ["X"]` (not an assignment), `os.environ.get("X", ...)`,
  `os.getenv("X", ...)`.
* Rust: `env::var("X")` / `env::var_os("X")` (with or without the `std::`
  prefix), `option_env!("X")`.
* A one-hop constant indirection in both languages: `ENV_NAME = "X"` /
  `const ENV_NAME: &str = "X";` followed by `os.environ.get(ENV_NAME)` /
  `env::var(ENV_NAME)` elsewhere in the scanned tree. Several real vars are
  only reachable this way, e.g. `python/glaurung/windows_config.py`'s
  `ENV_CONFIG_PATH = "GLAURUNG_WINDOWS_ANALYSIS_CONFIG"` and every
  `*_ENV` constant in `src/symbolic/solver/axeyum_backend.rs`.
* A GitHub Actions workflow `env:` block's direct child keys (how
  `GLAURUNG_REQUIRE_TOOLCHAINS`, `GLAURUNG_FIXTURE_TMPDIR` and friends
  actually reach the process environment in CI).

`build.rs` (repo root) is scanned alongside `src/`, `benches/`, `examples/`
and `fuzz/` even though it is not literally inside any of those directories:
it is the only place `BITWUZLA_LIB_DIR`, `BITWUZLA_RUNTIME_LIB_DIRS` and
`GLAURUNG_BITWUZLA_TYPECHECK_ONLY` are actually read, and the task this
generator was built for explicitly wants `BITWUZLA_*` covered.

Usage::

    uv run python tools/gen_env_reference.py            # write
    uv run python tools/gen_env_reference.py --check    # exit 1 if stale
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from dataclasses import dataclass, field
from difflib import unified_diff
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_PATH = REPO_ROOT / "docs" / "reference" / "environment-variables.md"
GENERATOR_NAME = "tools/gen_env_reference.py"

# Directories to scan for Python-style reads (`os.environ`/`os.getenv`) and
# for building the Python constant-indirection map.
PY_DIRS = ("python/glaurung", "python/tests", "tools", "scripts")

# Directories to scan for Rust-style reads (`env::var`/`option_env!`) and for
# building the Rust constant-indirection map. `build.rs` is a single extra
# file at the repo root -- see the module docstring.
RS_DIRS = ("src", "benches", "examples", "fuzz")
RS_EXTRA_FILES = ("build.rs",)

# Directories to scan for GitHub Actions workflow `env:` blocks.
YAML_DIRS = (".github",)

#: Read generically, with no project-specific meaning, so excluded even
#: though they turn up in a handful of test/tooling reads.
GENERIC_EXCLUDE = frozenset({"HOME", "PATH"})

IDENT = r"[A-Za-z_][A-Za-z0-9_]*"

# --- Python read patterns ----------------------------------------------------
PY_ENVIRON_INDEX_RE = re.compile(
    r'os\.environ\[\s*[\'"](' + IDENT + r')[\'"]\s*\](?!\s*=(?!=))'
)
PY_ENVIRON_GET_RE = re.compile(r'os\.environ\.get\(\s*[\'"](' + IDENT + r')[\'"]')
PY_GETENV_RE = re.compile(r'os\.getenv\(\s*[\'"](' + IDENT + r')[\'"]')
# Bare-identifier indirection: `os.environ.get(SOME_CONST)`, `os.environ[SOME_CONST]`.
PY_ENVIRON_INDEX_IND_RE = re.compile(
    r"os\.environ\[\s*(" + IDENT + r")\s*\](?!\s*=(?!=))"
)
PY_ENVIRON_GET_IND_RE = re.compile(r"os\.environ\.get\(\s*(" + IDENT + r")\s*[,)]")
PY_GETENV_IND_RE = re.compile(r"os\.getenv\(\s*(" + IDENT + r")\s*[,)]")
# `NAME = "VALUE"` at column 0 -- the constant-definition side of the
# indirection above.
PY_CONST_DEF_RE = re.compile(r'^([A-Z][A-Z0-9_]*)\s*=\s*[\'"](' + IDENT + r')[\'"]\s*$')

# --- Rust read patterns -------------------------------------------------------
RS_ENV_VAR_LIT_RE = re.compile(r'(?:std::)?env::var(?:_os)?\(\s*"(' + IDENT + r')"')
RS_ENV_VAR_IND_RE = re.compile(
    r"(?:std::)?env::var(?:_os)?\(\s*(" + IDENT + r")\s*[,)]"
)
RS_OPTION_ENV_RE = re.compile(r'option_env!\(\s*"(' + IDENT + r')"')
RS_CONST_DEF_RE = re.compile(
    r"(?:pub(?:\(crate\))?\s+)?const\s+("
    + IDENT
    + r")\s*:\s*&'?\w*\s*str\s*=\s*\"([^\"]+)\""
)

SHA_LINE_RE = re.compile(
    r"^<!-- generated by [^ ]+ at [0-9a-f]+; do not edit -->$", re.MULTILINE
)
SHA_LINE_PLACEHOLDER = "<!-- generated by GENERATOR at SHA; do not edit -->"


def _short_sha() -> str:
    try:
        out = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            check=True,
        )
        return out.stdout.strip() or "unknown"
    except (OSError, subprocess.CalledProcessError):
        return "unknown"


def _normalize(text: str) -> str:
    return SHA_LINE_RE.sub(SHA_LINE_PLACEHOLDER, text)


@dataclass
class Findings:
    #: variable name -> sorted set of repo-relative paths that read it.
    sites: dict[str, set[str]] = field(default_factory=dict)

    def add(self, name: str, path: Path, line_no: int) -> None:
        if name in GENERIC_EXCLUDE:
            return
        rel = path.relative_to(REPO_ROOT).as_posix()
        # Paths only: line numbers would make --check stale on every edit
        # near an env read, which is exactly the churn a generated reference
        # exists to avoid. `line_no` is kept in the signature for callers.
        del line_no
        self.sites.setdefault(name, set()).add(rel)


#: This generator's own module docstring spells out example calls
#: (`os.environ["X"]`, `env::var("X")`, ...) to document the patterns it
#: looks for. Those examples are themselves valid matches, so the file
#: would otherwise "find" a bogus variable named `X` in itself every run.
_SELF = Path(__file__).resolve()


def _iter_files(dirs: tuple[str, ...], suffixes: tuple[str, ...]) -> list[Path]:
    out: list[Path] = []
    for d in dirs:
        base = REPO_ROOT / d
        if not base.exists():
            continue
        for suffix in suffixes:
            out.extend(p for p in base.rglob(f"*{suffix}") if p.resolve() != _SELF)
    return sorted(set(out))


def _line_no(text: str, offset: int) -> int:
    return text.count("\n", 0, offset) + 1


#: `for name, attr in (("GLAURUNG_X", "attr_x"), ...): ... os.getenv(name)` --
#: a table-driven read used by `llm/config.py`'s budget-env block. The outer
#: tuple literal is matched as one non-nested-parens run per inner tuple,
#: which is exact for this codebase's style (inner tuples never nest
#: further); a loop var used by `os.getenv`/`os.environ.get` within the next
#: 600 characters after the header is treated as consuming it.
FOR_TUPLE_HEADER_RE = re.compile(
    r"for\s+(" + IDENT + r")\s*,\s*" + IDENT + r"\s+in\s*\(\s*"
    r"((?:\([^()]*\)\s*,?\s*)+)\)\s*:"
)
TUPLE_FIRST_STR_RE = re.compile(r'\(\s*"(' + IDENT + r')"\s*,')


def _scan_for_loop_env_tuples(text: str, path: Path, findings: Findings) -> None:
    for header in FOR_TUPLE_HEADER_RE.finditer(text):
        loop_var = header.group(1)
        tail = text[header.end() : header.end() + 600]
        use = re.search(
            r"os\.(?:getenv|environ\.get)\(\s*" + re.escape(loop_var) + r"\b", tail
        )
        if not use:
            continue
        line_no = _line_no(text, header.end() + use.start())
        for name_m in TUPLE_FIRST_STR_RE.finditer(header.group(2)):
            findings.add(name_m.group(1), path, line_no)


def _scan_python(findings: Findings) -> None:
    files = _iter_files(PY_DIRS, (".py",))

    const_map: dict[str, str] = {}
    file_text: dict[Path, str] = {}
    for path in files:
        try:
            text = path.read_text(errors="ignore")
        except OSError:
            continue
        file_text[path] = text
        for line in text.splitlines():
            m = PY_CONST_DEF_RE.match(line)
            if m:
                const_map[m.group(1)] = m.group(2)

    for path, text in file_text.items():
        for pat in (PY_ENVIRON_INDEX_RE, PY_ENVIRON_GET_RE, PY_GETENV_RE):
            for m in pat.finditer(text):
                findings.add(m.group(1), path, _line_no(text, m.start()))
        for pat in (PY_ENVIRON_INDEX_IND_RE, PY_ENVIRON_GET_IND_RE, PY_GETENV_IND_RE):
            for m in pat.finditer(text):
                resolved = const_map.get(m.group(1))
                if resolved:
                    findings.add(resolved, path, _line_no(text, m.start()))
        _scan_for_loop_env_tuples(text, path, findings)


def _scan_rust(findings: Findings) -> None:
    files = _iter_files(RS_DIRS, (".rs",))
    files.extend(REPO_ROOT / f for f in RS_EXTRA_FILES if (REPO_ROOT / f).is_file())
    files = sorted(set(files))

    const_map: dict[str, str] = {}
    file_text: dict[Path, str] = {}
    for path in files:
        try:
            text = path.read_text(errors="ignore")
        except OSError:
            continue
        file_text[path] = text
        for line in text.splitlines():
            for m in RS_CONST_DEF_RE.finditer(line):
                const_map[m.group(1)] = m.group(2)

    for path, text in file_text.items():
        for m in RS_ENV_VAR_LIT_RE.finditer(text):
            findings.add(m.group(1), path, _line_no(text, m.start()))
        for m in RS_OPTION_ENV_RE.finditer(text):
            findings.add(m.group(1), path, _line_no(text, m.start()))
        for m in RS_ENV_VAR_IND_RE.finditer(text):
            resolved = const_map.get(m.group(1))
            if resolved:
                findings.add(resolved, path, _line_no(text, m.start()))


def _scan_yaml_env_blocks(findings: Findings) -> None:
    files = _iter_files(YAML_DIRS, (".yml", ".yaml"))
    key_re = re.compile(r"^\s*(" + IDENT + r"):")
    for path in files:
        try:
            lines = path.read_text(errors="ignore").splitlines()
        except OSError:
            continue
        i = 0
        while i < len(lines):
            if lines[i].strip() == "env:":
                env_indent = len(lines[i]) - len(lines[i].lstrip(" "))
                j = i + 1
                while j < len(lines):
                    candidate = lines[j]
                    if not candidate.strip():
                        j += 1
                        continue
                    indent = len(candidate) - len(candidate.lstrip(" "))
                    if indent <= env_indent:
                        break
                    if indent == env_indent + 2:
                        m = key_re.match(candidate)
                        if m:
                            findings.add(m.group(1), path, j + 1)
                    j += 1
            i += 1


def collect() -> Findings:
    findings = Findings()
    _scan_python(findings)
    _scan_rust(findings)
    _scan_yaml_env_blocks(findings)
    return findings


# --- Hand-maintained purposes -------------------------------------------------
#
# Seeded from docs/history/docs-rewrite-2026-09/audit/ ledger 01 §5.4 (the 18
# GLAURUNG_* Python vars) and ledger 04 (the solver/axeyum ground truth), then
# checked against the actual read sites `collect()` finds. A name `collect()`
# finds that is NOT a key here renders as undocumented -- that gap is the
# point, not a bug to silence by adding a vague entry.
PURPOSES: dict[str, str] = {
    # --- Python: LLM / analyst surface ---------------------------------
    "GLAURUNG_CACHE_DIR": "Override the on-disk cache directory used by LLM/type-sync tooling.",
    "GLAURUNG_INPUT_TOKENS_LIMIT": "Cap input tokens per LLM request.",
    "GLAURUNG_JVM_TOOLS_JAR": "Path to a JDK `tools.jar` for Java agent workflows.",
    "GLAURUNG_LLM_MODEL": "Override the default `provider:model` string (see CLAUDE.md's LLM model policy).",
    "GLAURUNG_LLM_TEMPERATURE": "Override the default LLM sampling temperature.",
    "GLAURUNG_MAX_FILE_SIZE": "Cap the file size the triage/LLM pipeline will read.",
    "GLAURUNG_MAX_OUTPUT_TOKENS": "Cap output tokens per LLM request.",
    "GLAURUNG_MAX_READ_BYTES": "Cap bytes read per file/window in analysis tooling.",
    "GLAURUNG_OPENAI_SERVICE_TIER": "OpenAI `service_tier` (`flex`/`default`/`priority`); see CLAUDE.md's LLM model policy.",
    "GLAURUNG_PDB_CACHE": "Directory for cached downloaded/parsed Windows PDBs.",
    "GLAURUNG_REQUEST_LIMIT": "Cap the number of LLM requests a run may issue.",
    "GLAURUNG_REQUIRE_LLM": "Fail (instead of skip) when a test needs a live LLM key and none is set.",
    "GLAURUNG_TOOL_STRICT": "Make LLM tool-call validation fail closed on malformed arguments.",
    "GLAURUNG_TOTAL_TOKENS_LIMIT": "Cap total tokens (input+output) across an LLM run.",
    "GLAURUNG_TYPES_DIR": "Directory holding generated/synced type data (`glaurung types sync`).",
    "GLAURUNG_VERIFY_DEFS": "Toggle extra def-use verification in the decompiler pipeline.",
    "GLAURUNG_WINDOWS_ANALYSIS_CONFIG": "Path to the Windows analysis config JSON (default project/pdb settings).",
    "GLAURUNG_LIVE_LLM": "Opt a test into a live LLM call instead of a recorded/mocked one.",
    "GLAURUNG_RUN_NETWORK_TESTS": "Opt a test into making real network calls.",
    # --- Python: fixture / decompiler-test harness ----------------------
    "GLAURUNG_FIXTURE_GO": "Enable the Go-toolchain lane of the decompiler fixture matrix (opt-in).",
    "GLAURUNG_FIXTURE_JOBS": "Parallelism for the decompiler fixture build/run.",
    "GLAURUNG_FIXTURE_OBSERVED": "Where the fixture matrix writes its observed-results JSON (CI: `${{ runner.temp }}/observed.json`).",
    "GLAURUNG_FIXTURE_RUST": "Select an alternate Rust toolchain for building fixture binaries.",
    "GLAURUNG_FIXTURE_TMPDIR": "Scratch directory for the fixture build (CI: `${{ runner.temp }}`).",
    "GLAURUNG_FIXTURE_TOOLCHAIN": "Select the pinned fixture-toolchain Docker image tag.",
    "GLAURUNG_REQUIRE_TOOLCHAINS": "Fail (instead of skip) a test that needs a compiler toolchain and finds none; set by CI's `rust`/`symbolic` jobs.",
    "GLAURUNG_REDECOMP_FORCE": "Force re-decompilation even when cached output looks current.",
    "GLAURUNG_TRACE_ORACLE_VERSION": "Runtime version tag recorded into ordered-trace oracle output.",
    # --- Python: decbench (opt-in evaluation harness) -------------------
    "DECBENCH_DIR": "Path to the out-of-tree DecBench checkout.",
    "DECBENCH_SAMPLE_TREE": "Path to a local decbench-sample-set-glaurung-tree checkout for `tools/decbench_redecompile_tree.py`.",
    "DECBENCH_PYTHON": "Interpreter used to run DecBench's own scripts.",
    "DECBENCH_COLUMN": "Result-column name DecBench records this run under.",
    "GLAURUNG_DECBENCH_JOBS": "Parallelism for a DecBench matrix run.",
    # --- Third-party model/tooling comparison ---------------------------
    "OPENAI_API_KEY": "OpenAI credential for `glaurung ask`/`name-func`/the LLM agent stack.",
    "ANTHROPIC_API_KEY": "Anthropic credential; the configured fallback model family.",
    "GOOGLE_API_KEY": "Google/Gemini credential for LLM configs that select a Google model.",
    "GEMINI_API_KEY": "Alternate Gemini credential name some SDKs read instead of `GOOGLE_API_KEY`.",
    "ANGR_PYTHON": "Interpreter with `angr` installed, for `tools/compare_decompilers.py`.",
    "GHIDRA_PYTHON": "Interpreter used to drive Ghidra headless analysis for comparison tooling.",
    "GHIDRA_INSTALL_DIR": "Path to a local Ghidra install (comparison tooling; JDK 21 required).",
    "ASB_REPO": "Path to the sibling agentic-security-bot repo holding `data/kg/pe-*.yaml` (sources/sinks/gates) the Windows analyst tools read.",
    "XDG_CACHE_HOME": "Base cache directory `glaurung types sync` falls back to when `GLAURUNG_CACHE_DIR` is unset.",
    "_NT_SYMBOL_PATH": "Windows symbol-server search path some PDB tooling honours.",
    "TMPDIR": "Repo-wide convention (CLAUDE.md ground rule): every temp file must go under this, never `/tmp`.",
    "PROBE_OUT": "Internal to `test_cli_startup_is_lazy.py`'s own subprocess probe -- a scratch path for passing a result back, not a project configuration variable.",
    # --- Rust: decompiler pass tracing / IR ------------------------------
    "GLAURUNG_DUMP_PASSES": "Dump each IR pipeline pass's output for inspection.",
    "GLAURUNG_PASS_HEALTH": "Emit per-pass health/diagnostic accounting.",
    "GLAURUNG_PASS_STATS": "Emit per-pass timing/statistics.",
    "GLAURUNG_ACCOUNT_STRUCTURE": "Emit structuring-pass accounting output.",
    "GLAURUNG_LOWERING_STACK_MB": "Override the stack size (MB) reserved for the AST-lowering pass.",
    "GLAURUNG_PIPELINE_PROFILE": "Enable the decompile pipeline's phase profiler.",
    "GLAURUNG_IOCTL_DEBUG": "Verbose logging for IOCTL surface analysis.",
    "GLAURUNG_IOCTL_FIXTURES": "Directory of IOCTL-analysis fixtures for tests.",
    "GLAURUNG_PERF_BASELINE": "Path to the perf-gate baseline JSON `tools/perf_gate.py` compares against.",
    "GLAURUNG_ARGV_LOG": "Log a subprocess's argv for debugging test harnesses.",
    "GLAURUNG_ALLOW_STALE": "Suppress `tools/build_guard.py`'s stale-`.so` check.",
    "GLAURUNG_BIN": "Path to a `glaurung`-built binary a script should invoke.",
    "GLAURUNG_PYTHON": "Interpreter used to invoke `glaurung` from a non-Python caller.",
    "GLAURUNG_REAL_BIN": "Path to the real (non-wrapper) binary under test.",
    "GLAURUNG_VERSION": "Version string stamped into build/test output.",
    # --- Rust: symbolic execution / solver -------------------------------
    "GLAURUNG_SHADOW_DIFF": "Run two solver backends on the same query and diff their results (shadow-mode verification).",
    "GLAURUNG_DUMP_QUERIES": "Directory to dump raw SMT queries sent to the solver.",
    "GLAURUNG_DUMP_SHADOW_SPLITS": "Directory to dump shadow-mode query splits.",
    "GLAURUNG_FAIR_SHADOW": "Alternate shadow-mode backend selection policy for fairness comparisons.",
    "GLAURUNG_CONCRETIZATION_POLICY": "Select the symbolic-address concretization policy.",
    "GLAURUNG_CANONICAL_MODEL_CHOICE": "Legacy name for selecting the canonical solver model choice.",
    "GLAURUNG_ENGINE_CONSTRAINT_CACHE": "Toggle/configure the symbolic engine's constraint cache.",
    "GLAURUNG_SMT_SOLVER": "Force the `PipeSolver` to use a specific solver binary on PATH.",
    "GLAURUNG_CHECK_TIMEOUT_MS": "Per-query solver timeout in milliseconds.",
    "GLAURUNG_Z3_RLIMIT": "Z3 `rlimit` resource bound override.",
    "GLAURUNG_AXEYUM_PROGRESS_CHECK_LIMIT": "axeyum backend progress-check iteration limit.",
    "GLAURUNG_BITWUZLA_TERMINATION_POLL_LIMIT": "Bitwuzla backend termination-poll iteration limit.",
    "GLAURUNG_AXEYUM_SOURCE_REPO": "Path to a local axeyum checkout for native ordered-replay.",
    "GLAURUNG_ENGINE_CACHE_FACTORIAL_MODE": "Ordered-replay factorial-mode cache policy.",
    "GLAURUNG_AXEYUM_PROFILE_DIR": "Directory the axeyum backend writes profiling output to.",
    "GLAURUNG_AXEYUM_CNF_SNAPSHOT_DIR": "Directory the axeyum backend writes CNF snapshots to.",
    "GLAURUNG_AXEYUM_WARM_REUSE": "Toggle axeyum warm-path reuse.",
    "GLAURUNG_AXEYUM_WARM_OWNER_TRANSFER": "Toggle axeyum warm-path ownership transfer between siblings.",
    "GLAURUNG_AXEYUM_WARM_SERIAL_SIBLING_REUSE": "Toggle serial sibling reuse of axeyum warm paths.",
    "GLAURUNG_AXEYUM_DIRECT_DELTA": "Toggle axeyum's direct-delta incremental solving mode.",
    "GLAURUNG_AXEYUM_WARM_TIMEOUT_COLD_RETRY": "Toggle a cold retry when a warm axeyum path times out.",
    "GLAURUNG_AXEYUM_WARM_TIMEOUT_CONTINUE": "Toggle continuing on a warm axeyum path timeout instead of failing.",
    "GLAURUNG_AXEYUM_INTERNAL_AND_FLATTENING": "Toggle axeyum's internal AND-flattening optimization.",
    "GLAURUNG_AXEYUM_REPLAY_SAT_CACHE": "Cache policy for axeyum replay SAT results.",
    "GLAURUNG_AXEYUM_WARM_MAX_LIVE_PATHS": "Cap the number of live warm axeyum paths kept.",
    "GLAURUNG_AXEYUM_WARM_MAX_ASSERTIONS_PER_PATH": "Cap assertions per warm axeyum path.",
    "GLAURUNG_ORDERED_TRACE_DIR": "Directory ordered symbolic traces are written to/read from.",
    "GLAURUNG_SYMBOLIC_CVE_OBJECT_ID": "Object identifier for the `linux_symbolic_cve` example run.",
    "GLAURUNG_FLIRT_LIB": "Path to a FLIRT signature library override.",
    "IOCTLANCE_ANNOTATE_CONFIDENCE": "Annotate IOCTL findings with the confidence-partition label (see reference/docs on taint provenance).",
    "IOCTLANCE_ALL": "Report every candidate IOCTL finding, not just high-confidence ones.",
    "IOCTLANCE_HOPS": "Max call-graph hops the `ioctlance` example explores from an entry point.",
    "IOCTLANCE_SOLVE_BUDGET": "Solver step budget for the `ioctlance` example.",
    "IOCTLANCE_SOLVE_SECS": "Per-query solver time budget (seconds) for the `ioctlance` example.",
    "IOCTLANCE_DEADLINE_SECS": "Overall wall-clock deadline (seconds) for an `ioctlance` run.",
    "IOCTLANCE_MAX_ANALYZED_FUNCTIONS": "Cap the number of functions the `ioctlance` example analyzes.",
    "IOCTLANCE_STATEFUL_BLOCKS": "Cap stateful-block exploration in the `ioctlance` example.",
    "IOCTL_SCAN_BUDGET": "Solver step budget for the `ioctl_scan` example.",
    "IOCTL_SCAN_TRACE": "Enable trace logging in the `ioctl_scan` example.",
    "BITWUZLA_LIB_DIR": "Path to the Bitwuzla 0.9.1 shared library `build.rs` links against for `solver-bitwuzla`.",
    "BITWUZLA_RUNTIME_LIB_DIRS": "Extra runtime library search paths for the linked Bitwuzla library.",
    "GLAURUNG_BITWUZLA_TYPECHECK_ONLY": "Skip Bitwuzla's link setup in `build.rs` for a link-free `cargo check` (used by the feature-build gate and lint scripts).",
    "CARGO_FEATURE_SOLVER_BITWUZLA": "Set automatically by Cargo when the `solver-bitwuzla` feature is enabled; `build.rs` reads it to decide whether to run the Bitwuzla link step at all.",
    "CARGO_TARGET_DIR": "Cargo's build-output directory; the identity-retrieval protocol test reads it to place its evaluation artifacts beside the build rather than in the source tree.",
    "GLAURUNG_IDENTITY_CORPUS": "Path to a populated `tests/decompiler_fixtures/build` -- the matched-build corpus the function-identity lanes score against, so a worktree can point at a checkout that has one. Unset and absent in-tree, those lanes skip loudly. The *external* corpus (Cisco Talos Dataset-1) is `GLAURUNG_CISCO_CORPUS`, which this table cannot see: it is read from `tests/identity_retrieval/cisco.rs` and the Rust walk covers `src, benches, examples, fuzz` only. See `docs/development/identity-measurement.md` and `docs/development/corpora.md`.",
    "GLAURUNG_ARMTC": "Root of an `arm-gnu-toolchain-*-arm-none-eabi` extraction (e.g. release 13.2.Rel1), read by `tools/harvest_armtc.py --toolchain-root` and by the live-toolchain check in `python/tests/test_flirt_cortex_m_fixture.py`, which skips loudly when unset. Feeds the Cortex-M FLIRT signature libraries; see `docs/reference/function-signature-libraries.md#cortex-m-bare-metal` and `docs/development/corpora.md`.",
    # --- CI workflow env: blocks -----------------------------------------
    "REGISTRY": "Container registry host for the samples-docker publish workflow.",
    "IMAGE_NAME": "Container image name/tag prefix for the samples-docker publish workflow.",
    "MATURIN_PYPI_TOKEN": "PyPI upload token for the release workflow's `maturin publish` step.",
    "BUILD_CORPUS_MANIFEST": "Windows target-pipeline workflow input: corpus manifest path.",
    "CORPUS_ROOT": "Windows target-pipeline workflow input: binary corpus root.",
    "PROJECT_ROOT": "Windows target-pipeline workflow input: `.glaurung` project root.",
    "TARGET_ID": "Windows target-pipeline workflow input: which target to run.",
    "MAX_TARGETS": "Windows target-pipeline workflow input: cap on targets processed.",
    "MAX_PACKETS_PER_TARGET": "Windows target-pipeline workflow input: cap on packets per target.",
    "PATCH_DIFF_BINARY_A": "Windows target-pipeline workflow input: baseline binary for a patch diff.",
    "PATCH_DIFF_BINARY_B": "Windows target-pipeline workflow input: candidate binary for a patch diff.",
    "PATCH_DIFF_FUNCTION_IDENTITY_PATH": "Windows target-pipeline workflow input: function-identity map for a patch diff.",
}


def _truncate_paths(paths: list[str], limit: int = 3) -> str:
    shown = paths[:limit]
    text = ", ".join(f"`{p}`" for p in shown)
    if len(paths) > limit:
        text += f", … (+{len(paths) - limit} more)"
    return text


def render(findings: Findings) -> str:
    lines: list[str] = [
        "# Environment variables",
        "",
        "> **Kind:** reference · **Status:** generated",
        f"<!-- generated by {GENERATOR_NAME} at {_short_sha()}; do not edit -->",
        "",
        "Every environment variable this repository reads, found by walking "
        f"`{', '.join(PY_DIRS)}` for Python reads, `{', '.join(RS_DIRS)}` "
        "(plus `build.rs`) for Rust reads, and `.github` for workflow `env:` "
        "blocks -- see `tools/gen_env_reference.py` for the exact patterns "
        "and the one-hop constant indirection it resolves. A variable with "
        "no entry in the generator's `PURPOSES` dict is marked undocumented "
        "so the gap is visible rather than silently dropped. Regenerate "
        "with `uv run python tools/gen_env_reference.py`; `--check` fails "
        "the build when this file is stale.",
        "",
        f"{len(findings.sites)} variables found, "
        f"{sum(1 for k in findings.sites if k in PURPOSES)} documented.",
        "",
        "| Variable | Read in | Purpose |",
        "| --- | --- | --- |",
    ]
    for name in sorted(findings.sites):
        paths = sorted(findings.sites[name])
        purpose = PURPOSES.get(
            name, "(undocumented — add to PURPOSES in the generator)"
        )
        lines.append(f"| `{name}` | {_truncate_paths(paths)} | {purpose} |")
    lines.append("")

    unused_purposes = sorted(set(PURPOSES) - set(findings.sites))
    if unused_purposes:
        lines.append(
            "The following `PURPOSES` entries no longer match any read site "
            "found by the scan above (renamed or removed -- update the "
            "generator):"
        )
        lines.append("")
        for name in unused_purposes:
            lines.append(f"- `{name}`")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def generate() -> str:
    return render(collect())


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if the generated reference differs",
    )
    args = parser.parse_args(argv)

    content = generate()
    existing = OUT_PATH.read_text() if OUT_PATH.exists() else None

    if args.check:
        if existing is not None and _normalize(existing) == _normalize(content):
            return 0
        print(f"stale: {OUT_PATH.relative_to(REPO_ROOT)}", file=sys.stderr)
        old_lines = _normalize(existing or "").splitlines(keepends=True)
        new_lines = _normalize(content).splitlines(keepends=True)
        diff = unified_diff(
            old_lines, new_lines, fromfile="committed", tofile="generated"
        )
        sys.stderr.writelines(diff)
        print(f"\nrun: uv run python {GENERATOR_NAME}", file=sys.stderr)
        return 1

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(content)
    print(f"wrote {OUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
