#!/usr/bin/env python3
"""Generate the CLI reference from the actual `glaurung` argument parsers.

`docs/reference/cli.md` used to be hand-maintained prose that drifted from
`python/glaurung/cli/main.py`'s `_REGISTRY` (see
`tools/gen_native_stub.py` for why hand-maintained mirrors of a live surface
are a standing liability). This script builds the real parser tree --
`GlaurungCLI().create_parser(only=None)` -- and reads every command's
`argparse.ArgumentParser` back through its public `_actions` list, so the
page can never claim an option, default, or help string the CLI does not
actually have.

Building the full parser tree imports every command module (`only=None`
registers all of them, per `create_parser`'s own docstring), which is the
same cost `python/tests/test_cli_startup_is_lazy.py` exists to keep out of a
single `glaurung <command>` invocation. That test asserts a *subprocess*
running one subcommand does not import the heavy modules; it says nothing
about a documentation generator, which by design has to see all 40.

Usage::

    uv run python tools/gen_cli_reference.py            # write
    uv run python tools/gen_cli_reference.py --check    # exit 1 if stale
"""

from __future__ import annotations

import argparse
import importlib
import re
import subprocess
import sys
from difflib import unified_diff
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_PATH = REPO_ROOT / "docs" / "reference" / "cli.md"
GENERATOR_NAME = "tools/gen_cli_reference.py"

#: dest names covered once in the "Common flags" section instead of on every
#: one of the 40 per-command sections. `base.py::add_common_arguments` adds
#: exactly these to every command.
COMMON_DESTS = ("format", "json", "no_color", "quiet", "verbose")

SHA_LINE_RE = re.compile(
    r"^<!-- generated by [^ ]+ at [0-9a-f]+; do not edit -->$", re.MULTILINE
)
SHA_LINE_PLACEHOLDER = "<!-- generated by GENERATOR at SHA; do not edit -->"

_NO_VALUE_ACTIONS = (
    argparse._HelpAction,
    argparse._VersionAction,
    argparse._StoreTrueAction,
    argparse._StoreFalseAction,
    argparse._StoreConstAction,
    argparse._CountAction,
)


def _short_sha() -> str:
    try:
        out = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            check=True,
        )
        return out.stdout.strip() or "unknown"
    except (OSError, subprocess.CalledProcessError):
        return "unknown"


def _normalize(text: str) -> str:
    """Drop the sha so a diff never fires on the commit alone."""
    return SHA_LINE_RE.sub(SHA_LINE_PLACEHOLDER, text)


def _escape_cell(text: str | None) -> str:
    if not text:
        return ""
    return text.replace("|", "\\|").replace("\n", " ").strip()


def _takes_value(action: argparse.Action) -> bool:
    return not isinstance(action, _NO_VALUE_ACTIONS) and not isinstance(
        action, argparse._SubParsersAction
    )


def _metavar(action: argparse.Action) -> str:
    if isinstance(action.metavar, str):
        return action.metavar
    if action.choices:
        return "{" + ",".join(str(c) for c in action.choices) + "}"
    return action.dest.upper()


def _flag_cell(action: argparse.Action) -> str:
    text = ", ".join(action.option_strings)
    if _takes_value(action):
        text += f" {_metavar(action)}"
    return f"`{text}`"


def _default_cell(action: argparse.Action) -> str:
    default = action.default
    if default is argparse.SUPPRESS:
        return "n/a"
    if default is None:
        return "`None`"
    return f"`{default!r}`"


def _usage_line(command_path: str, actions: list[argparse.Action]) -> str:
    """A deterministic usage line built from the action list.

    Not `parser.format_usage()`: argparse wraps that to the *terminal
    width* it is run in (`shutil.get_terminal_size()`), which is not
    reproducible between an interactive shell and `--check` running
    headless in CI. Building the line from `_actions` directly keeps it
    stable regardless of where the generator runs.
    """
    tokens: list[str] = [f"glaurung {command_path}"]
    has_options = False
    for action in actions:
        if isinstance(action, argparse._HelpAction):
            continue
        if action.option_strings:
            has_options = True
            continue
        if isinstance(action, argparse._SubParsersAction):
            tokens.append("{" + ",".join(action.choices) + "} ...")
            continue
        name = action.metavar if isinstance(action.metavar, str) else action.dest
        if action.nargs == "?":
            tokens.append(f"[{name}]")
        elif action.nargs == "*":
            tokens.append(f"[{name} ...]")
        elif action.nargs == "+":
            tokens.append(f"{name} [{name} ...]")
        else:
            tokens.append(f"<{name}>")
    if has_options:
        tokens.insert(1, "[options]")
    return " ".join(tokens)


def _subparsers_action(
    parser: argparse.ArgumentParser, *, dest: str
) -> argparse._SubParsersAction:
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction) and action.dest == dest:
            return action
    raise AssertionError(f"parser has no subparsers action with dest={dest!r}")


def _nested_subparsers(
    sp: argparse.ArgumentParser,
) -> argparse._SubParsersAction | None:
    for action in sp._actions:
        if isinstance(action, argparse._SubParsersAction):
            return action
    return None


def _command_section(name: str, sp: argparse.ArgumentParser) -> list[str]:
    lines = [f"## `glaurung {name}`", ""]

    nested = _nested_subparsers(sp)
    lines.append("```")
    lines.append(_usage_line(name, sp._actions))
    lines.append("```")
    lines.append("")

    positionals = [
        a
        for a in sp._actions
        if not a.option_strings and not isinstance(a, argparse._SubParsersAction)
    ]
    optionals = [
        a
        for a in sp._actions
        if a.option_strings and not isinstance(a, argparse._HelpAction)
    ]
    extra_optionals = [a for a in optionals if a.dest not in COMMON_DESTS]

    if positionals:
        lines.append("Positional arguments:")
        lines.append("")
        lines.append("| Argument | Help |")
        lines.append("| --- | --- |")
        for a in positionals:
            name_cell = a.metavar if isinstance(a.metavar, str) else a.dest
            lines.append(f"| `{name_cell}` | {_escape_cell(a.help)} |")
        lines.append("")

    if extra_optionals:
        lines.append("Options (beyond the [common flags](#common-flags)):")
        lines.append("")
        lines.append("| Flag | Default | Help |")
        lines.append("| --- | --- | --- |")
        for a in extra_optionals:
            lines.append(
                f"| {_flag_cell(a)} | {_default_cell(a)} | {_escape_cell(a.help)} |"
            )
        lines.append("")

    if nested is not None:
        lines.append(f"Subcommands (`{nested.dest}`):")
        lines.append("")
        lines.append("| Subcommand | Help |")
        lines.append("| --- | --- |")
        for choice_action in nested._choices_actions:
            lines.append(
                f"| `{choice_action.dest}` | {_escape_cell(choice_action.help)} |"
            )
        lines.append("")

    return lines


def generate() -> str:
    climain = importlib.import_module("glaurung.cli.main")
    cli = climain.GlaurungCLI()
    top = cli.create_parser(only=None)
    cmd_action = _subparsers_action(top, dest="cmd")
    registry = climain._REGISTRY
    help_by_name = {ca.dest: ca.help for ca in cmd_action._choices_actions}

    lines: list[str] = [
        "# Glaurung CLI reference",
        "",
        "> **Kind:** reference · **Status:** generated",
        f"<!-- generated by {GENERATOR_NAME} at {_short_sha()}; do not edit -->",
        "",
        "Every subcommand `uv run glaurung --help` prints, generated from the "
        f"live `argparse` parsers in `python/glaurung/cli/commands/`. {len(registry)} "
        "commands, in the order `python/glaurung/cli/main.py`'s `_REGISTRY` "
        "declares them. Regenerate with "
        "`uv run python tools/gen_cli_reference.py` after any parser change; "
        "`--check` fails the build when this file is stale.",
        "",
        "## Common flags",
        "",
        "Every command accepts these, added once by "
        "`BaseCommand.add_common_arguments`:",
        "",
        "| Flag | Default | Help |",
        "| --- | --- | --- |",
    ]

    # The five common flags are identical across every command (added by the
    # same `add_common_arguments` call), so any one command's parser gives
    # the canonical set. `_REGISTRY` order is deterministic; pick its first
    # entry rather than hardcoding a command name.
    first_name = next(iter(registry))
    first_sp = cmd_action.choices[first_name]
    for a in first_sp._actions:
        if a.option_strings and a.dest in COMMON_DESTS:
            lines.append(
                f"| {_flag_cell(a)} | {_default_cell(a)} | {_escape_cell(a.help)} |"
            )
    lines.append("")

    lines.append("## Commands")
    lines.append("")
    lines.append("| Command | Help | Module |")
    lines.append("| --- | --- | --- |")
    for name in registry:
        module_name = registry[name][0]
        lines.append(
            f"| [`{name}`](#glaurung-{name.replace(' ', '-')}) "
            f"| {_escape_cell(help_by_name.get(name))} | `commands/{module_name}.py` |"
        )
    lines.append("")

    for name in registry:
        lines.extend(_command_section(name, cmd_action.choices[name]))

    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if the generated reference differs",
    )
    args = parser.parse_args(argv)

    content = generate()
    existing = OUT_PATH.read_text() if OUT_PATH.exists() else None

    if args.check:
        if existing is not None and _normalize(existing) == _normalize(content):
            return 0
        print(f"stale: {OUT_PATH.relative_to(REPO_ROOT)}", file=sys.stderr)
        old_lines = _normalize(existing or "").splitlines(keepends=True)
        new_lines = _normalize(content).splitlines(keepends=True)
        diff = unified_diff(
            old_lines, new_lines, fromfile="committed", tofile="generated"
        )
        sys.stderr.writelines(diff)
        print(f"\nrun: uv run python {GENERATOR_NAME}", file=sys.stderr)
        return 1

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(content)
    print(f"wrote {OUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
