#!/usr/bin/env python3
"""Generate the Cargo feature reference from `Cargo.toml`, `src/lib.rs`,
`pyproject.toml`, and `scripts/feature-build-gate.sh`.

Why this needs a generator and not prose: CLAUDE.md's own history is a
record of this exact table going stale. Ledger 02 §1.1
(`docs/development/docs-audit-2026-09-02/02-code-ground-truth.md`) found the
feature list, the gate lane count, and the "what does `cargo test` actually
build" claims all drifting independently -- most consequentially, `cargo
test --features python-ext` does NOT build `src/symbolic/` (`symbolic` is in
neither `default` nor `python-ext`), which cost real debugging time before
anyone wrote it down. This script computes the feature-activation closure
the way Cargo itself does (a feature's dependency array can name other
features, transitively) for five representative build commands plus all 12
`feature-build-gate.sh` lanes, so "what compiles" is derived, not asserted.

Usage::

    uv run python tools/gen_feature_reference.py            # write
    uv run python tools/gen_feature_reference.py --check    # exit 1 if stale
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
import tomllib
from difflib import unified_diff
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_PATH = REPO_ROOT / "docs" / "reference" / "cargo-features.md"
GENERATOR_NAME = "tools/gen_feature_reference.py"

SHA_LINE_RE = re.compile(
    r"^<!-- generated by [^ ]+ at [0-9a-f]+; do not edit -->$", re.MULTILINE
)
SHA_LINE_PLACEHOLDER = "<!-- generated by GENERATOR at SHA; do not edit -->"


def _short_sha() -> str:
    try:
        out = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            check=True,
        )
        return out.stdout.strip() or "unknown"
    except (OSError, subprocess.CalledProcessError):
        return "unknown"


def _normalize(text: str) -> str:
    return SHA_LINE_RE.sub(SHA_LINE_PLACEHOLDER, text)


def _load_cargo_toml() -> dict:
    with (REPO_ROOT / "Cargo.toml").open("rb") as fh:
        return tomllib.load(fh)


def _load_pyproject_toml() -> dict:
    with (REPO_ROOT / "pyproject.toml").open("rb") as fh:
        return tomllib.load(fh)


def _feature_gated_modules() -> dict[str, list[str]]:
    """`#[cfg(feature = "X")]` immediately above `pub mod Y;` in `src/lib.rs`.

    Only the direct `mod` gate, matching the task this generator serves
    ("which modules each gates"). `python-ext` also gates several
    `#[pymodule]`/`#[pyfunction]` items later in the same file (the `_native`
    entry point and its top-level helpers) -- real, but not a *module*, so
    they are reported separately rather than inflating this map.
    """
    text = (REPO_ROOT / "src" / "lib.rs").read_text()
    gated: dict[str, list[str]] = {}
    for m in re.finditer(
        r'#\[cfg\(feature\s*=\s*"([^"]+)"\)\]\s*\n\s*pub\s+mod\s+(\w+);', text
    ):
        gated.setdefault(m.group(1), []).append(m.group(2))
    return gated


def _python_ext_extra_items(feature: str) -> int:
    """Non-`mod` items in `src/lib.rs` itself gated on `feature`.

    Reported as a count next to the module list rather than folded into it,
    since `#[pymodule] fn _native` and its `#[pyfunction]` helpers are not
    modules.
    """
    text = (REPO_ROOT / "src" / "lib.rs").read_text()
    gate = f'#[cfg(feature = "{feature}")]'
    non_mod = 0
    for m in re.finditer(re.escape(gate) + r"\s*\n\s*(pub\s+)?(\w[\w:!<>]*)", text):
        if not re.match(r"pub\s+mod\s", text[m.start() : m.start() + len(gate) + 40]):
            non_mod += 1
    return non_mod


def _site_counts() -> dict[str, int]:
    """`feature = "X"` occurrences (inside `#[cfg(...)]`/`cfg!(...)`) across
    `src/` and `benches/`, per feature name from `Cargo.toml`."""
    text = ""
    for d in ("src", "benches"):
        base = REPO_ROOT / d
        if not base.exists():
            continue
        for path in base.rglob("*.rs"):
            text += path.read_text(errors="ignore")
    counts: dict[str, int] = {}
    for m in re.finditer(r'feature\s*=\s*"([^"]+)"', text):
        counts[m.group(1)] = counts.get(m.group(1), 0) + 1
    return counts


def _closure(requested: list[str], features: dict[str, list[str]]) -> set[str]:
    """The set of project features active when `requested` are enabled.

    Mirrors Cargo's own resolution for the one relationship that matters
    here: a feature's array can name *another feature*, which is then
    activated too, transitively. Entries that are not feature names --
    `dep:z3`, `pyo3/extension-module`, `axeyum-solver/full` -- name optional
    dependencies or their sub-features, not project features, and are left
    out of the closure (they still appear verbatim in the "enables" column).
    """
    closure: set[str] = set()
    stack = list(requested)
    while stack:
        name = stack.pop()
        if name in closure or name not in features:
            continue
        closure.add(name)
        stack.extend(features[name])
    return closure


def _gate_lanes() -> list[tuple[str, str, str, str]]:
    """Parse `scripts/feature-build-gate.sh`'s `lanes=(...)` array.

    Each entry is `"label|needs|cargo_args"` or, for the one lane pointing
    at the separate `fuzz/` crate, `"label|needs||manifest_path"`. Returned
    as (label, needs, cargo_args, manifest_path).
    """
    text = (REPO_ROOT / "scripts" / "feature-build-gate.sh").read_text()
    m = re.search(r"lanes=\(\n(.*?)\n\)\n", text, re.DOTALL)
    assert m is not None, "scripts/feature-build-gate.sh: lanes=(...) not found"
    lanes: list[tuple[str, str, str, str]] = []
    for line in m.group(1).splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        entry = re.match(r'^"(.*)"\s*$', line)
        if not entry:
            continue
        parts = entry.group(1).split("|")
        label = parts[0]
        needs = parts[1] if len(parts) > 1 else ""
        args = parts[2] if len(parts) > 2 else ""
        manifest = parts[3] if len(parts) > 3 else ""
        lanes.append((label, needs, args, manifest))
    return lanes


def _lane_requested_features(
    args: str, features: dict[str, list[str]]
) -> list[str] | None:
    """Features `cargo check --all-targets {args}` requests, or None for
    `--all-features` (every feature in the table, Cargo's own semantics)."""
    if "--all-features" in args:
        return None
    m = re.search(r"--features[= ]([^\s]+)", args)
    if not m:
        return []
    return m.group(1).split(",")


def render() -> str:
    cargo = _load_cargo_toml()
    pyproject = _load_pyproject_toml()
    features: dict[str, list[str]] = cargo["features"]
    gated_modules = _feature_gated_modules()
    site_counts = _site_counts()

    lines: list[str] = [
        "# Cargo features",
        "",
        "> **Kind:** reference · **Status:** generated",
        f"<!-- generated by {GENERATOR_NAME} at {_short_sha()}; do not edit -->",
        "",
        f"`Cargo.toml`'s `[features]` table has {len(features)} entries. Feature "
        "activation is transitive (a feature's array can name another "
        "feature, which is then active too); the tables below compute that "
        "closure the way Cargo does, rather than asserting it. Regenerate "
        "with `uv run python tools/gen_feature_reference.py`; `--check` "
        "fails the build when this file is stale.",
        "",
        "## Features",
        "",
        '| Feature | Enables | Gates in `src/lib.rs` | `feature = "…"` sites (`src/` + `benches/`) |',
        "| --- | --- | --- | --- |",
    ]
    for name, enables in features.items():
        enables_cell = ", ".join(f"`{e}`" for e in enables) if enables else "—"
        modules = gated_modules.get(name)
        if modules:
            gates_cell = ", ".join(f"`{m}`" for m in modules)
        else:
            gates_cell = "nothing"
        lines.append(
            f"| `{name}` | {enables_cell} | {gates_cell} | {site_counts.get(name, 0)} |"
        )
    lines.append("")
    lines.append(
        "`python-ext` additionally gates the `#[pymodule] fn _native` entry "
        "point and its top-level `#[pyfunction]` helpers directly in "
        "`src/lib.rs` (not a separate module, so not listed in the "
        '"Gates" column above).'
    )
    lines.append("")

    # --- What each build compiles ------------------------------------------
    lines.append("## What each build compiles")
    lines.append("")
    lines.append(
        "The active-feature closure for five representative commands, and "
        "which of the feature-gated `src/` modules from the table above "
        "that closure includes."
    )
    lines.append("")
    lines.append(
        "| Command | Active features | Feature-gated `src/` modules included |"
    )
    lines.append("| --- | --- | --- |")

    def modules_for(closure: set[str]) -> str:
        included = sorted({m for feat in closure for m in gated_modules.get(feat, [])})
        return ", ".join(f"`{m}`" for m in included) if included else "none"

    commands: list[tuple[str, list[str]]] = [
        ("`cargo test`", ["default"]),
        ("`cargo test --features python-ext`", ["default", "python-ext"]),
        ("`cargo test --features symbolic`", ["default", "symbolic"]),
    ]
    for label, requested in commands:
        closure = _closure(requested, features)
        lines.append(
            f"| {label} | {', '.join(f'`{f}`' for f in sorted(closure))} | "
            f"{modules_for(closure)} |"
        )

    wheel_features: list[str] = list(pyproject["tool"]["maturin"]["features"])
    wheel_project_features = [f for f in wheel_features if f in features]
    wheel_closure = _closure(["default", *wheel_project_features], features)
    wheel_extra = [f for f in wheel_features if f not in features]
    wheel_enables = ", ".join(f"`{f}`" for f in sorted(wheel_closure)) + (
        (", " + ", ".join(f"`{f}`" for f in wheel_extra)) if wheel_extra else ""
    )
    lines.append(
        f"| the wheel (`[tool.maturin] features` in `pyproject.toml`) | "
        f"{wheel_enables} | {modules_for(wheel_closure)} |"
    )
    lines.append("")

    # --- Gate lanes ----------------------------------------------------------
    lanes = _gate_lanes()
    lines.append(f"## `scripts/feature-build-gate.sh` lanes ({len(lanes)})")
    lines.append("")
    lines.append(
        "Each lane runs `cargo check --all-targets`, which type-checks "
        "every target (including `#[cfg(test)]` code) but does not run "
        "anything -- see CLAUDE.md's `cargo check` vs `cargo test` rule."
    )
    lines.append("")
    lines.append(
        "| # | Lane | Needs | `cargo check` args | Active features | Modules included |"
    )
    lines.append("| --- | --- | --- | --- | --- | --- |")
    for i, (label, needs, args, manifest) in enumerate(lanes, start=1):
        if manifest:
            lines.append(
                f"| {i} | {label} | {needs or '—'} | `--manifest-path {manifest}` | "
                "(separate crate, own feature set) | n/a |"
            )
            continue
        requested = _lane_requested_features(args, features)
        if requested is None:
            closure = set(features)
            active_cell = "*(all)* " + ", ".join(f"`{f}`" for f in sorted(closure))
        else:
            closure = _closure(["default", *requested], features)
            active_cell = ", ".join(f"`{f}`" for f in sorted(closure))
        args_cell = f"`{args}`" if args else "*(none)*"
        lines.append(
            f"| {i} | {label} | {needs or '—'} | {args_cell} | {active_cell} | "
            f"{modules_for(closure)} |"
        )
    lines.append("")

    # --- Examples --------------------------------------------------------
    cargo_examples = cargo.get("example", [])
    lines.append(f"## Examples (`[[example]]` in `Cargo.toml`, {len(cargo_examples)})")
    lines.append("")
    lines.append("| Example | Required features |")
    lines.append("| --- | --- |")
    for ex in cargo_examples:
        req = ex.get("required-features", [])
        req_cell = ", ".join(f"`{f}`" for f in req) if req else "*(none)*"
        lines.append(f"| `{ex['name']}` | {req_cell} |")
    lines.append("")

    # --- Benches -----------------------------------------------------------
    cargo_benches = cargo.get("bench", [])
    lines.append(f"## Benches (`[[bench]]` in `Cargo.toml`, {len(cargo_benches)})")
    lines.append("")
    lines.append("| Bench | Required features |")
    lines.append("| --- | --- |")
    for b in cargo_benches:
        req = b.get("required-features", [])
        req_cell = ", ".join(f"`{f}`" for f in req) if req else "*(none)*"
        lines.append(f"| `{b['name']}` | {req_cell} |")
    lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def generate() -> str:
    return render()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if the generated reference differs",
    )
    args = parser.parse_args(argv)

    content = generate()
    existing = OUT_PATH.read_text() if OUT_PATH.exists() else None

    if args.check:
        if existing is not None and _normalize(existing) == _normalize(content):
            return 0
        print(f"stale: {OUT_PATH.relative_to(REPO_ROOT)}", file=sys.stderr)
        old_lines = _normalize(existing or "").splitlines(keepends=True)
        new_lines = _normalize(content).splitlines(keepends=True)
        diff = unified_diff(
            old_lines, new_lines, fromfile="committed", tofile="generated"
        )
        sys.stderr.writelines(diff)
        print(f"\nrun: uv run python {GENERATOR_NAME}", file=sys.stderr)
        return 1

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(content)
    print(f"wrote {OUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
