//! F-16: per-translation-unit resolution.
//!
//! [`crate::csource::joern::parity_cfgs`] resolves name collisions *within* one
//! translation unit (F-15: on a repeated name, keep the CFG with more nodes).
//! A real project is many TUs, and DecBench's published corpus stores exactly
//! one CFG per `(binary, function)` -- so something has to pick a winner across
//! TUs too. This module reproduces DecBench's `resolved_source_for_binary`
//! (`decbench/utils/cfg.py`), which every published `source_cfgs/<stem>.json`
//! was generated by, so a name defined in several TUs resolves exactly as the
//! stored corpus resolves it.
//!
//! # What the corpus (and the reference implementation) actually do
//!
//! `resolved_source_for_binary` is **two rules applied in order**, not one
//! lexicographic comparison:
//!
//! 1. Start from the **cross-TU fallback**: for every name, across every TU of
//!    the project, keep the highest-ranked candidate on
//!    `(is_non_degenerate, node_count)` (`_source_rank` / `best_source_by_name`).
//!    This step *is* a lexicographic max.
//! 2. Then, for every name the binary's **own TU** defines, **unconditionally
//!    overwrite** the fallback with the own-TU CFG -- but only when the own-TU
//!    CFG is non-degenerate. There is no size comparison here: a binary's own,
//!    smaller `main` beats a larger same-named `main` pulled in from another
//!    TU of the same project.
//!
//! Mining `~/.cache/glaurung/decbench-full/tree/*/*/source_cfgs/*.json`
//! confirms step 2 is real, not a corner case: in `O2/coreutils`, `main`
//! appears in 108 binaries' JSONs with wildly different shapes (`link` 19
//! nodes, `numfmt` 152 nodes, `date` 101 nodes, `df` 108 nodes) -- each
//! binary's own TU, not one shared "biggest main" picked by rank. Conversely,
//! of the 11,915 function names shared by two or more binaries of the same
//! project, 11,691 (98.1%) serialize identically everywhere: real shared
//! helpers (gnulib code, static library functions) correctly fall back to the
//! *same* cross-TU CFG in every binary that doesn't define its own. And across
//! all 800 published files / 91,548 functions, not one name has both a
//! degenerate and a non-degenerate serialized variant inside the same
//! project -- confirming step 2's degenerate check: an own-TU placeholder body
//! never survives once a real body exists anywhere in the project.
//!
//! So the inventory's one-line summary ("lexicographic max on the rank
//! `(is_non_degenerate, node_count)`; the binary's own TU wins") describes
//! rule 1 correctly but **understates** rule 2: "own TU wins" is not a
//! comparison against the fallback's rank, it is an unconditional override
//! whenever the own-TU body is real. This module follows the reference
//! implementation and the corpus, not the summary sentence.
//!
//! `resolved_source_for_binary` also takes an optional DWARF `function_owners`
//! map (decl-file provenance, `decbench/utils/binfmt.py`) that outranks the
//! binary-stem convention for an unambiguous owner. That input comes from
//! reading a compiled binary's debug info, which this module has no access to
//! (it operates purely over parsed TU text) -- so only the two rules above are
//! implemented here; a caller that also has DWARF owner data can layer that
//! priority on top by overwriting `resolved` a third time, exactly as the
//! reference does.

use std::collections::BTreeMap;

use super::ParityCfg;

/// A translation unit's stem, e.g. `nologin` for `nologin.i`.
pub type TuStem = String;

/// A function name as it appears in `parity_cfgs`' output.
pub type FnName = String;

/// One project's parsed CFGs, per translation unit.
pub type ProjectCfgs = BTreeMap<TuStem, BTreeMap<FnName, ParityCfg>>;

/// Sort key preferring a non-degenerate, then larger, CFG.
///
/// Mirrors `decbench.utils.cfg._source_rank` exactly -- this is the piece of
/// `resolved_source_for_binary` that genuinely is a lexicographic max.
fn rank(cfg: &ParityCfg) -> (bool, usize) {
    (!cfg.degenerate, cfg.nodes.len())
}

/// Collapse per-TU CFGs to one-per-name, preferring the real, larger body.
///
/// The cross-TU fallback used when a binary's own TU doesn't define a name at
/// all, or defines it only as an empty prototype. Mirrors
/// `decbench.utils.cfg.best_source_by_name`.
pub fn best_by_name(by_tu: &ProjectCfgs) -> BTreeMap<FnName, ParityCfg> {
    let mut best: BTreeMap<FnName, ParityCfg> = BTreeMap::new();
    for cfgs in by_tu.values() {
        for (name, cfg) in cfgs {
            match best.get(name) {
                Some(existing) if rank(existing) >= rank(cfg) => {}
                _ => {
                    best.insert(name.clone(), cfg.clone());
                }
            }
        }
    }
    best
}

/// The function CFGs to score one binary against, TU-aware.
///
/// `binary_tu_stem` is the binary-stem convention: the TU whose stem matches
/// the binary's own name (`nologin` binary <-> `nologin.i`). Mirrors
/// `decbench.utils.cfg.resolved_source_for_binary` *without* its DWARF
/// `function_owners` step (see the module docs) -- rule 1 (cross-TU fallback)
/// then rule 2 (unconditional own-TU override when non-degenerate).
pub fn resolve_for_binary(
    binary_tu_stem: &str,
    by_tu: &ProjectCfgs,
    best_by_name_map: &BTreeMap<FnName, ParityCfg>,
) -> BTreeMap<FnName, ParityCfg> {
    let mut resolved = best_by_name_map.clone();
    if let Some(own_tu) = by_tu.get(binary_tu_stem) {
        for (name, cfg) in own_tu {
            // Unconditional: no comparison against `resolved`'s current rank.
            // A real own-TU body always wins, however small.
            if !cfg.degenerate {
                resolved.insert(name.clone(), cfg.clone());
            }
        }
    }
    resolved
}

/// Resolve every TU of a project as if it were its own binary.
///
/// Convenience for callers with no separate binary/TU-stem mapping (e.g. a
/// bare directory of translation units): each TU stands in for the binary
/// built from it, per the binary-stem convention `resolve_for_binary` also
/// uses. `tools/source_cfg_export.py` is exactly such a caller.
pub fn resolve_project(by_tu: &ProjectCfgs) -> ProjectCfgs {
    let fallback = best_by_name(by_tu);
    by_tu
        .keys()
        .map(|stem| (stem.clone(), resolve_for_binary(stem, by_tu, &fallback)))
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::csource::joern::parity_cfgs;

    /// Two TUs each define `main`; each binary keeps its own, not the
    /// larger one -- rule 2, and the acceptance test the inventory names:
    /// "reproduce `resolved_source_for_binary` on a project with a colliding
    /// `main`".
    #[test]
    fn own_tu_main_wins_over_a_larger_cross_tu_main() {
        let mut by_tu: ProjectCfgs = BTreeMap::new();
        // `a.c`'s main is a single early return -- small.
        by_tu.insert("a".to_string(), parity_cfgs("int main(void){ return 0; }"));
        // `b.c`'s main has real branching -- larger.
        by_tu.insert(
            "b".to_string(),
            parity_cfgs("int main(int argc){ if (argc) { return 1; } return 0; }"),
        );

        let fallback = best_by_name(&by_tu);
        let a_main = &by_tu["a"]["main"];
        let b_main = &by_tu["b"]["main"];
        assert!(
            b_main.nodes.len() > a_main.nodes.len(),
            "the fixture must actually have a larger `b` main, or this test proves nothing"
        );
        // The cross-TU fallback picks the higher-ranked (larger) one.
        assert_eq!(fallback["main"], *b_main, "fallback picks the higher rank");

        // But binary `a` keeps ITS OWN (smaller) main, not the fallback's.
        let resolved_a = resolve_for_binary("a", &by_tu, &fallback);
        assert_eq!(
            resolved_a["main"], *a_main,
            "own TU wins unconditionally, even though it is the smaller graph"
        );
        // And binary `b` keeps its own too (here it happens to equal the fallback).
        let resolved_b = resolve_for_binary("b", &by_tu, &fallback);
        assert_eq!(resolved_b["main"], *b_main);
    }

    /// A name the binary's own TU never defines falls back to the best
    /// cross-TU candidate -- the statically-linked-helper case
    /// `resolved_source_for_binary`'s docstring names explicitly.
    #[test]
    fn a_name_absent_from_the_own_tu_falls_back_cross_tu() {
        let mut by_tu: ProjectCfgs = BTreeMap::new();
        by_tu.insert(
            "a".to_string(),
            parity_cfgs("int main(void){ return helper(); }"),
        );
        by_tu.insert(
            "helpers".to_string(),
            parity_cfgs("int helper(void){ if (1) { return 2; } return 3; }"),
        );

        let fallback = best_by_name(&by_tu);
        let resolved_a = resolve_for_binary("a", &by_tu, &fallback);
        assert_eq!(
            resolved_a["helper"], by_tu["helpers"]["helper"],
            "helper isn't in a's own TU, so it must come from the cross-TU fallback"
        );
        assert!(
            resolved_a.contains_key("main"),
            "a's own main must still be present"
        );
    }

    /// A degenerate own-TU placeholder never survives once a real body exists
    /// anywhere in the project -- confirmed on the corpus: of 91,548
    /// published functions across 800 files, zero names have both a
    /// degenerate and a non-degenerate serialized variant.
    #[test]
    fn a_degenerate_own_tu_prototype_is_replaced_by_the_real_body() {
        let mut by_tu: ProjectCfgs = BTreeMap::new();
        // `a.c` only forward-declares `helper` -- no function body reaches the
        // parser, so `parity_cfgs` never emits an entry for it at all here;
        // simulate the "declaration-only view" DecBench's Joern front end
        // produces (a single degenerate block) directly.
        by_tu.insert(
            "a".to_string(),
            BTreeMap::from([(
                "helper".to_string(),
                ParityCfg {
                    nodes: vec![],
                    edges: vec![],
                    entry: vec![],
                    exit: vec![],
                    degenerate: true,
                },
            )]),
        );
        by_tu.insert(
            "helpers".to_string(),
            parity_cfgs("int helper(void){ if (1) { return 2; } return 3; }"),
        );

        let fallback = best_by_name(&by_tu);
        let resolved_a = resolve_for_binary("a", &by_tu, &fallback);
        assert_eq!(
            resolved_a["helper"], by_tu["helpers"]["helper"],
            "a degenerate own-TU entry must not shadow the real cross-TU body"
        );
        assert!(!resolved_a["helper"].degenerate);
    }

    /// `best_by_name` itself is the lexicographic max: non-degenerate beats
    /// degenerate regardless of node count, and among two non-degenerate
    /// candidates the larger one wins. Mirrors `_source_rank` /
    /// `best_source_by_name` directly.
    #[test]
    fn best_by_name_is_non_degenerate_then_node_count() {
        let degenerate_but_present = ParityCfg {
            nodes: vec![0, 1, 2, 3, 4, 5],
            edges: vec![],
            entry: vec![],
            exit: vec![],
            degenerate: true,
        };
        let small_real = ParityCfg {
            nodes: vec![0],
            edges: vec![],
            entry: vec![0],
            exit: vec![0],
            degenerate: false,
        };
        let mut by_tu: ProjectCfgs = BTreeMap::new();
        by_tu.insert(
            "a".to_string(),
            BTreeMap::from([("f".to_string(), degenerate_but_present.clone())]),
        );
        by_tu.insert(
            "b".to_string(),
            BTreeMap::from([("f".to_string(), small_real.clone())]),
        );
        let fallback = best_by_name(&by_tu);
        assert_eq!(
            fallback["f"], small_real,
            "a 1-node real body must outrank a 6-node degenerate one"
        );
    }

    /// Whole-project convenience: every TU resolves as if it were the binary
    /// built from it, so a name unique to one TU is visible in every other
    /// TU's resolved map (the fallback), while a name multiple TUs define
    /// stays TU-specific.
    #[test]
    fn resolve_project_gives_every_tu_its_own_plus_the_shared_fallback() {
        let mut by_tu: ProjectCfgs = BTreeMap::new();
        by_tu.insert("a".to_string(), parity_cfgs("int main(void){ return 0; }"));
        by_tu.insert(
            "b".to_string(),
            parity_cfgs("int main(int argc){ if (argc) { return 1; } return 0; }"),
        );
        let resolved = resolve_project(&by_tu);
        assert_eq!(resolved["a"]["main"], by_tu["a"]["main"]);
        assert_eq!(resolved["b"]["main"], by_tu["b"]["main"]);
    }
}
