// main.c
// Recovered from hello-gfortran-O2 by glaurung source-recovery

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

/* Task Q: extern prototypes for libgfortran / Fortran-runtime symbols referenced below. */
extern void _gfortran_set_args(int argc, char **argv);
extern void _gfortran_set_options(int n, int *opts);
extern void MAIN__(void);

/* Bug W: gfortran's compile-time options array (originally `options.6.2`,
 * file-scope LOCAL static at 0x20d0 in the binary). 7 int entries
 * encode language standard / range-check / backtrace flags. Values
 * are the actual bytes recovered from .rodata so a re-compile of the
 * recovered source produces identical runtime behaviour. */
static int options[7] = {
    0x844,    /* GFC_STD_F95_OBS | F2003 | F2008 | LEGACY (lang-standard mask) */
    0x0fff,   /* runtime-warn mask */
    0x0,      /* pedantic */
    0x1,      /* backtrace */
    0x1,      /* sign-zero */
    0x0,      /* range-check */
    0x1f,     /* fpe + denormal trap mask */
};

/**
 * @brief Program entry point for a GNU Fortran-compiled executable.
 *
 * Performs the standard libgfortran runtime initialization sequence
 * required before transferring control to the Fortran user program:
 *   1. Forwards the command-line arguments to the runtime via
 *      `_gfortran_set_args`, so that intrinsics such as
 *      `COMMAND_ARGUMENT_COUNT` and `GET_COMMAND_ARGUMENT` work.
 *   2. Installs the compile-time runtime option vector via
 *      `_gfortran_set_options(7, options)` (7 entries describing
 *      language standard, backtrace, range-check, etc.).
 *   3. Invokes `MAIN__`, the mangled name of the Fortran `PROGRAM`
 *      unit, where the actual user code executes.
 *
 * After `MAIN__` returns normally, the function returns 0 to the OS.
 * This is the canonical `main` emitted by gfortran when linking a
 * Fortran program against libgfortran.so.5.
 *
 * @param argc Argument count, as supplied by the C runtime.
 * @param argv Argument vector, as supplied by the C runtime; passed
 *             through unmodified to `_gfortran_set_args`.
 *
 * @return Always 0; the Fortran program signals errors through
 *         `STOP`/`ERROR STOP` (which call `exit` directly) rather
 *         than via this return value.
 * @retval 0 `MAIN__` ran to completion without aborting the process.
 *
 * @note The `options` array referenced here is a file-scope constant
 *       generated by the gfortran front-end; its 7 elements encode
 *       the runtime flags selected at compile time.
 * @note This function is not intended to be called from user code;
 *       it is the program's startup routine.
 */
int main(int argc, char **argv)
{
    _gfortran_set_args(argc, argv);
    _gfortran_set_options(7, options);
    MAIN__();
    return 0;
}

